### ISSUE TITLE
Implement rendering masks

### ISSUE THREAD

**Issue by LaurentGomila** [SFML/SFML#1]
Add a sf::ClippingMask class, which is used to clip rendered objects to a specific region of 2D world.

There are many OpenGL options to implement it, the best one should be clip planes.

**Comment by LaurentGomila** [comment]
> scissor buffer

Stencil buffer ;)

The stencil buffer is well supported and allows a wide range of possibilities, so it is the best candidate. However since it can be disabled (and is currently not enabled by default) in the context settings, it implies that the user can disable clipping masks, without even knowing it. So this must be at least well documented, and even enforced if possible.

So the main problem is to decide what we use to define the clipping area. We could start with a ```const sf::Drawable*``` to have maximum flexibility.

Another question is: do we allow only one active mask, or do we provide the ability to add multiple masks?

We should think about the most common use cases of clipping masks in order to answer efficiently to these questions.

**Comment by Mischa-Alff** [comment]
If the application uses the stencil buffer (via an `sf::ClipMask`), it can simply enable it, no?

Regarding the clipping area, I think the user might want to define a mask using multiple shapes if possible.

In my opinion, there are many uses for clipping masks, but the single one that comes up most often is probably UI stuff.

**Comment by LaurentGomila** [comment]
> If the application uses the stencil buffer (via an sf::ClipMask), it can simply enable it, no?

It must be decided at window creation. And wouldn't it be worst to force stencil buffer if the user had explicitly disabled it?

> Regarding the clipping area, I think the user might want to define a mask using multiple shapes if possible.

Keep in mind that we must keep the API simple enough. Which often means not providing everything that can be done. But yes, that's a possibility.

> In my opinion, there are many uses for clipping masks, but the single one that comes up most often is probably UI stuff.

Yes, this is probably the most common one.

**Comment by CelticMinstrel** [comment]
This sounds good so far. As I mentioned earlier, my personal need is for elliptical clipping regions (so, an sf::Shape) and for pixel-based masks (so, using a monochrome image to specify the exact extent of the mask). I wasn't able to solve the latter problem with the stencil buffer, though I feel like I should have been able to.

I don't think it's terribly complicated to make a class that will compose an arbitrary number of sf::Shapes into a region - then when populating the stencil buffer, you just need to "draw" those shapes in sequence. You can even allow subtraction of a shape from the region, rather than addition.

It might be complicated to support pixel-based masks, though.

**Comment by zsbzsb** [comment]
4 years later and 841 issues/pulls later...... #842   check it out

**Comment by aaaaaaaaargh** [comment]
I just came back to SFML after a couple of years and I'm honestly nearly losing all my hopes about why this it not fixed by now.

There is a PR by @zsbzsb which looks nice and well implemented, so I'm wondering why noone else seems to be considering this a massive lack of a basic feature here.

I mean, I was working with a hell lot of libraries over the past 20 years and this is something that even old libraries like allegro come up with since decades.

I am calling on you to please check and merge @zsbzsb 's proposal as soon as possible.

Really no offense guys, you do great work maintaining SFML, so consider this just a serious reminder of how important clip masks are.

**Comment by binary1248** [comment]
@aaaaaaaaargh So... since you mention allegro... what concrete functions does allegro provide that provides non-rectangular clipping? That is the point that is so contentious now. If you wanted rectangular clipping, just use an `sf::View`. There is no need to hold your breath for this feature.

**Comment by aaaaaaaaargh** [comment]
@binary1248 allegro 4 had masked_blit() which pretty much does what you're asking for.
When speaking about 5 i am not sure, but I guess you could do it using al_draw_bitmap_region or something like that. Please remember that due to its heritage allegro 5 implements must of its graphics functions using global application states just as GL does, so this might not be too hard to achieve.

I'm afraid I wasn't talking about rectangular clipping at all, I am talking about opacity or clip maps which, at least in my humble opinion, should be a feature in a graphics library nowadays.

Again, I don't wan't to discredit your work, I know how demanding it can be to work for free on such a big thing like SFML. I was just pointing out that work has already been done like 4 years ago by @zsbzsb and I think that deserves a little bit of attention as well.

**Comment by binary1248** [comment]
@aaaaaaaaargh Skimming through https://liballeg.org/stabledocs/en/alleg014.html and https://liballeg.org/a5docs/trunk/graphics.html I couldn't find any functions that provide support for anything non-rectangular.

What many people tend to easily forget is that we aren't talking about the feature in and of itself, we are also talking about its concrete implementation. sfml-graphics does its drawing fully hardware-accelerated, and we want to keep it that way. No matter how sought after a feature is, if it cannot be done on a GPU to keep frame rates acceptable it won't be done.

@zsbzsb's implementation was surely the first to show up, but there were at least 2 other proposals, including mine which was a bit too low level for some people. If there is no consensus on how to proceed API-wise or implementation-wise then features, as much as they are sought after, will just end up in a deadlock like this one.

The best thing you can do is either start a new discussion or continue [the existing one](https://en.sfml-dev.org/forums/index.php?topic=18042.0) and try to muster support and someone who will champion an implementation that is ripe enough for a formal review.

As painful as it might sound, even if you find a feature useful the main reason why it hasn't been worked on is that there just hasn't been an overwhelming amount of interest from the community for it, regardless of how old it is.

**Comment by eXpl0it3r** [comment]
Closing this, as #1451 has been merged on `master`

...finally! 🥳
