### ISSUE TITLE
Window - toggle fullscreen / change style at runtime

### ISSUE THREAD

**Issue by Zuzu-Typ** [SFML/SFML#1113]
Dear Developers,

As seen in the title, I'd like to request the ability to switch between windowed and fullscreen mode at runtime, since I seem to run into problems, like destroying my additional GLEW OpenGL context when simply re-creating the window with a different style by myself.

And I don't consider having to restart my application as an option.

Maybe this is just me, having done a mistake in my code (like not re-creating the context as well), but I think if this was do-able, it would be used by many.

Thank you for your time and have a nice software,
--Zuzu_Typ--

**Comment by eXpl0it3r** [comment]
Please use the [forum](http://en.sfml-dev.org/forums/) for discussions like this as stated in the [Contribution Guidelines](http://www.sfml-dev.org/contribute.php).

Switching between window and fullscreen mode requires the recreation of the window and I'm not certain, but pretty sure that this is done so because of technical limitations.

If you lose some OpenGL states during a switch, you'll simply have to make sure to reset them. There's no need to restart the whole application.

But again, please continue this discussion on the forum and provide code example and a description of what your problem actually is.
