### ISSUE TITLE
OS X 10.11 Audio Warning

### ISSUE THREAD

**Issue by KraXarN** [SFML/SFML#1120]
When compiling a test app with sfml-audio the following warning is put in the console:
`WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.`
It seems to be an issue with 10.11.x only, but I'm not sure.
I'm running OS X 10.11.6 with Xcode 7.3.1

**Comment by mantognini** [comment]
You are more than welcome to discuss your issue on the forum first as we try to keep this issue tracker for confirmed issues only. The procedure to open a bug/feature request is explained in [the contribution guidelines](http://www.sfml-dev.org/contribute.php). Thanks.

Note: This was discussed in #1000 and fixed with its related PR. Make sure you use latest master version when testing.
