### ISSUE TITLE
Implicit conversion loses integer precision in MacOS

### ISSUE THREAD

**Issue by halowine** [SFML/SFML#1145]
I have some warnings when compiling the SFML with Xcode on MacOS 10.11 (+ #1122 ).

The "std::size_t" in the 64-bit environment of MacOS is not an 'int' but a 'unsigned long' ([https://developer.apple.com/library/mac/documentation/Darwin/Conceptual/64bitPorting/transition/transition.html](url)). Several functions are passing an 'int' to an 'unsigned long' which loses the integer precision. It shouldn't be an issue in this direction but I still have several warnings.

There is the same issue with 'ssize_t' giving a 'long' instead of an 'int'.

**Comment by eXpl0it3r** [comment]
I'm sure @mantognini will have a look. Keep in mind however that according to our [Contribution Guidelines](http://www.sfml-dev.org/contribute.php) we like to use the issue tracker for confirmed issues only. :wink:

**Comment by mantognini** [comment]
Can't reproduce with CI. Please open a discussion on the forum with precise step to reproduce the said warnings if you really have such an issue with SFML and not your code.

**Comment by MarioLiebisch** [comment]
Maybe I just learned it under a different term, but what's "integer precision" and why should it be lost on upcasting? A `long int` can represent all values an `int` might take. Of course there's the signed/unsigned difference, but even there no data is lost.

MSVC spits out a few warnings regarding implicit casting as well, but these are pretty much just cosmetic (sane values won't cause problems).

Could you name any specific examples of problematic lines or lines the compiler complains about?

**Comment by SirSharpest** [comment]
What compiler are you using? Clang and gcc didn't give me warnings on Unix
(Yeah I k ow it's different but compilers should have similar
functionality)

On 10 Sep 2016 07:03, "Mario Liebisch" <notifications@github.com> wrote:

Maybe I just learned it under a different term, but what's "integer
precision" and why should it be lost on upcasting? A long int can represent
all values an int might take. Of course there's the signed/unsigned
difference, but even there no data is lost.

MSVC spits out a few warnings regarding implicit casting as well, but these
are pretty much just cosmetic (sane values won't cause problems).

Could you name any specific examples of problematic lines or lines the
compiler complains about?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/SFML/SFML/issues/1145#issuecomment-246092325>, or mute
the thread
