### ISSUE TITLE
Joystick-related lag spike (up to 500ms) when joystick disconnected

### ISSUE THREAD

**Issue by alexander-brett** [SFML/SFML#1179]
Related to this forum thread: http://en.sfml-dev.org/forums/index.php?topic=19082.0

I'm on Windows 10, and when I have my xbox 360 controller disconnected, calling `Window.pollEvent` causes a lag spike of 200-400ms every second. This behaviour didn't happen before the first time I connected my controller.

There should be a flag to control joystick update checking so that I can detect that it is not connected and not retry unless I'm in the settings menu or similar.

**Comment by eliasdaler** [comment]
+1 for the flag.
I notice big overhead of joystick event polling even if it's not connected in the first place.

**Comment by JonnyPtn** [comment]
forum thread in OP seems to digress a bit, but I've been investigating this today and wondered if handling the WM_DEVICECHANGE message had been ruled out already?

If the previous fix was just to make it poll less frequently, then it looks like that could be further improved by only polling when WM_DEVICECHANGE message is received (may mean a lag spike when other non-joystick devices are added/removed, but I'd say that's better than a lag spike every half a second?)

furthermore, if you register for the device notifications you can just use the messages to detect when a device is dis/connected and do away with the polling altogether, although that might be a longer term project, whereas just using the default message to know when to poll might be a decent short-term fix to this problem.

if anyone knows if this has already been ruled out for some reason then let me know, otherwise I'll get some code changes together in the next few days for people to test

**Comment by eXpl0it3r** [comment]
@LaurentGomila would be the one to know.

**Comment by LaurentGomila** [comment]
I don't remember investigating WM_DEVICECHANGE, and it seems to be supported from XP, so it might be worth trying.

**Comment by MarioLiebisch** [comment]
Tried it yesterday for a bit and it worked for me (not that complicated to implement). You'll get the window message with `wParam` set to `DBT_DEVNODES_CHANGED` when plugging (2 messages) and unplugging (1 message) my Xbox One controller. I couldn't get the more advanced messages, even though I tried subscribing to everything. Overhead isn't that bad (essentially one `unsigned int` to determine whether SFML has any window handle receiving messages, plus one or two static functions to update that value). There aren't any signif

I'm still getting a heap corruption down inside ntdll, if I plug/unplug the controller while SFML is running, but I guess that's a driver issue (getting it with current `master` branch as well.

**Comment by JonnyPtn** [comment]
To get more advanced messages such as device type etc. you need to register for the notifications using [RegisterDeviceNotification](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363431(v=vs.85).aspx). I tested this and for my xbox 360 controller I correctly get the device arrival/removal messages, as well as the device type (interface, in this case). For what it's worth I didn't notice any crashes whilst testing this, and must have un/plugged the controller dozens of times (just using the green circle tutorial code)

**Comment by MarioLiebisch** [comment]
Exactly the call I couldn't get working (using the provided example code). The crashing might be related to the Xbox One in combination with Windows 10. It's a heap corruption happening outside SFML (while calling `getJoyInfoEx()`).

**Comment by JonnyPtn** [comment]
I've made some changes to just update the joystick on any device change (saves faffing about with registering devices) which should be a big imrpovement, so if anybody can test it that would be brilliant, seems to work great here on windows 10 with x360 controller.

@MarioLiebisch I think I had to fiddle with the GUID to get it working properly, as the one in the example is deprecated (but don't quote me on that). Based on what I've tried, I'm not sure how much benefit there is right now to getting the advanced info. The problem I got stuck on was trying to work out which controller ID had been un/plugged, otherwise the only benefit I can see from the advanced details would be filtering it down to just poll when an interface device has been plugged in, but I'm not sure if that's worth the risk of any side-effects from getting device notifications.

On the other hand, I can see the advanced details having some use to identify controller types (something I've seen raised in IRC a few times) so it's worth considering, but probably as part of a larger joystick overhaul

**Comment by MarioLiebisch** [comment]
No, I don't think it's really necessary to use the advanced ones. The basic one is fine, I only thought that's related to my heap corruption in the driver(?), but since it's happening without the event, it's not related.

**Comment by eXpl0it3r** [comment]
This should be fixed with #1195 in f053871a6c041292ecc059a8a2a435416f176390.

**Comment by matt77hias** [comment]
Hey, I call `RegisterDeviceNotification` and receive `WM_DEVICECHANGE` messages with `wParam == DBT_DEVNODES_CHANGED` **only** upon connecting/disconnecting a XBox One Controller. I wonder whether it is possible to receive a message as well, upon pressing a button or moving a thumbstick, indicating a change (**without** specifying the specific change)? This would allow me to lazily query the controller state **if and only if** such a message is received since the last update.
