### ISSUE TITLE
[Suggestion] Rendering sf::Texture directly

### ISSUE THREAD

**Issue by RUSshy** [SFML/SFML#1200]
Hello

Sometimes i just need to render directly a Texture (for a BG for example) without having to wrap it in a Sprite or Shape

Would be cool if it was possible

Thanks

**Comment by LaurentGomila** [comment]
Hi

First, please use the forum for this kind of questions. The tracker is reserved for confirmed bugs and tasks.

Then, to answer your question, drawing a texture doesn't make sense. You need to setup some geometry, with at least a position and size, on which to map that texture so that it can be rasterized and drawn. And this is exactly what sf::Sprite does. I can't imagine any good reason why you would not want to use a sf::Sprite.

**Comment by RUSshy** [comment]
Oh yes you are right, i come from libGDX and we can draw textres directly but i forgot that it's because of the batching so it internally create a quad.. im stupid

Thanks
