### ISSUE TITLE
Sound playback doesn't switch to newly selected device on Linux

### ISSUE THREAD

**Issue by naezith** [SFML/SFML#1225]
I can't test this myself but a full-time Linux user reported it,

He has a monitor with speakers. He opens the game, all the sounds come from the monitor speakers. Then he plugs in the headset, normally all the sounds switch to headset but the game keeps using the monitor speaker. 

Can someone with similar setup try this?

**Comment by MarioLiebisch** [comment]
Might be related to how Linux provides the output devices, considering SFML doesn't offer you a selection so far.

**Comment by sjaustirni** [comment]
This sometimes (not always) happens to me with Firefox on Arch Linux, so it may not be SFML-specific.

**Comment by danieljpetersen** [comment]
This is indeed an issue. I just reported it here before realizing it was a duplicate and closing it, https://github.com/SFML/SFML/issues/2340. That link contains some more information and an example test program.

I'll also add that while it may be possible other applications are also handling this incorrectly, I've never experienced this issue with any apps other than SFML ones. Playing audio and switching in firefox / vlc / mpv / whatever works correctly for me.

**Comment by eXpl0it3r** [comment]
Does this still happen with the `master` branch, now that we switched away from OpenAL?

**Comment by binary1248** [comment]
This might still happen with miniaudio since we enumerate devices only when the `AudioDevice` instance is created. As long as the `AudioDevice` instance sticks around it will use the same device even if new ones are added to the system.

It all depends on how the selected audio driver represents itself. It might provide a single virtual device that intelligently routes all sound to the "right" hardware even when new hardware is made available, or it might present each hardware device as its own device and leave it up to the application to intelligently make the switch when it learns new devices are available.

Either way, sfml-audio still lacks support for the user to select which device they want to playback audio on, and until there is such support, the second scenario I mentioned won't be implementable by the user.

I would keep this issue open at least until we provide audio device selection support and re-evaluate then.

**Comment by danieljpetersen** [comment]
I just tested it on my system and the sound did correctly switch after connecting bluetooth headphones to my laptop. I was one of the people who noticed the old incorrect behavior, so I think that's a pretty good indication.

**Comment by binary1248** [comment]
Closing this now since #3029 will allow the user to select their desired playback device at runtime.

While miniaudio does provide a system of notifying the user when _something_ audio-hardware-related changes on the system, it is not supported to the same level on all platforms and some might not notify of anything at all. Because of the varying levels of support, this isn't something SFML users can rely on in a portable way, thus we can't support it.
