### ISSUE TITLE
Add support for mipmaps

### ISSUE THREAD

**Issue by luiscubal** [SFML/SFML#123]
Currently, drawing a sprite with a low zoom(inferior to 1), so that the texture is "zoomed out", gives a very bad result, even if Smooth is set.
Although there are ways to force mipmaps to be created using SFML's Bind() and OpenGL commands, this is still worse than having proper support in SFML.

I propose the following solutions(any will do):

1. Have a bool parameter in the Texture constructor telling SFML to generate mipmaps, and automatically enable them with Smooth=true(or a separate property useMipmapsIfSmooth)
2. Have some function to enable mipmap support.
3. Have mipmap support always enabled(perhaps not recommended since it will cause problems for images with Smooth=false)

Mipmaps seem to be available since OpenGL 1.4 (although there seem to have been some changes to how mipmaps are created in OpenGL 3.0), so I don't think this would cause problems to anyone. If compatibility is a problem, then some static method to detect mipmap support could be added(similar to how SFML handles shaders?)

As far as I know, adding mipmap support should be as simple as adding the following lines of code:

glTexParameteri(GL_TEXTURE_2D, GL_GENERATE_MIPMAP, GL_TRUE);
glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR_MIPMAP_LINEAR);

See also: http://en.sfml-dev.org/forums/index.php?topic=6266.0

**Comment by binary1248** [comment]
So... time to resurrect this issue.

Right now, there are 2 routes we can go down to implement mipmap support:
* Use `GL_SGIS_generate_mipmap`
* Use `GL_EXT_framebuffer_object`

(I'm not even considering the GLU option, since... it's GLU and is not hardware accelerated at all)

One possible implementation of the first route exists as #498. Mipmap generation relies on setting a texture parameter which instructs the GL to automatically generate mipmaps _every time the texture is modified after that parameter is set_. This can and will be a problem if the user intends to update the texture frequently or in multiple smaller segments. In order to preserve performance in this case, they would have to disable mipmaps, update the texture as they need to and re-enable mipmaps _before their last update_. If you ask me, this sounds very troublesome and almost unusable. In fact, because this makes the GL generate mipmaps every time the texture is modified, it doesn't even work on textures that are used as framebuffer object images, another disadvantage. The only real advantage I can think of with this variant is that it is supported in OpenGL since version 1.4 or on systems that support `GL_SGIS_generate_mipmap`.

The second route makes mipmap generation explicit so the user will have full control over when they are allocated and generated. This means that once they are done modifying the texture in any way they need to, they can finally call a method to generate the mipmap based on the current texture data. It's that simple really. Because it's that simple, it is also supported on textures that are used as framebuffer object images, which is the reason why it was introduced in the corresponding extension. The user would just draw to a `RenderTexture` as usual, and once they are done drawing everything, they can manually generate the mipmap for the new texture data. The only disadvantage (if you can even call it that) is that this route relies on a more recent extension (`GL_EXT_framebuffer_object`) which is already used by the `RenderTexture` implementation when it is supported.

So, there you have it, we will have to choose between implicit/automatic mipmap generation or explicit mipmap generation, the latter being more powerful for users who know when and how to use it. Seeing as mipmaps will probably only be interesting to more advanced users anyway, I favour the second option. Bear in mind that when thinking of support for OpenGL ES 2.0+ (which is required for shader support), there really only is the second option.

**Comment by MarioLiebisch** [comment]
Never checked what GLU does. Does it really generate the mipmaps in software? Or is it some kind of fallback?

**Comment by binary1248** [comment]
It really does _everything_ in software. Back when GLU was written, there was no such thing as "hardware acceleration" like there is nowadays. All the hardware did was really basic rendering/rasterization, manage framebuffer memory and drive the output to the monitor essentially.

In this case, GLU basically takes the texture data you pass to it (in CPU memory), generates the mipmap chain in memory and uploads all of that stuff to the GPU once it's done. You can still generate your own mipmaps in software and upload yourself nowadays if you really wanted to, but as you can imagine nobody ever does it any more since it is all properly hardware accelerated these days.

**Comment by TankOs** [comment]
I guess the second option is the only sane one, then.

**Comment by Cleroth** [comment]
Software mipmapping is still useful when you want a better downsizing algorithm. As far as I'm aware the only algorithms that are hardware-accelerated are either linear or bicubic sampling (in RGB...), neither of which is very good at downsizing. Lanczos would be one option.

Point being, if you want high-quality mipmaps, software is the way to go. But like you said, nobody really bothers to do high-quality mipmaps yet. It may be coming into fashion though, as people become more aware of their existence.

**Comment by TankOs** [comment]
I'm no graphics expert, so bear with me, but isn't a Lanczos filter also possible through a fragment shader?

**Comment by MarioLiebisch** [comment]
You can implement pretty much any filter in a shader, but it'll cause runtime costs rather than some static one-time cost when generating mipmaps.

**Comment by binary1248** [comment]
Fragment shaders are executed per fragment, as their name implies. Even if one were to ignore the constant cost of having to add an extra pass every frame, this still doesn't fix the problem that mipmapping is meant to fix. Mipmapping applies solely to the texture space before it even gets pulled into the rendering process through a sampler. Some might even use mipmapping not for the potentially improved aesthetics but more for the improved performance that GPUs can deliver because less texture data has to be processed in total at lower LODs. Fragment shaders are used for post-processing effects, stuff that applies to the actual scene and not to specific data sources for that scene, although I'm pretty sure hell-bent people will still find a way to do this as well, as usual...

**Comment by wintertime** [comment]
> One possible implementation of the first route exists as #498.

Actually, there have been commits for automatically choosing between ARB_FBO, EXT_FBO and SGIS_MIPMAP, depending on whats available: https://github.com/wintertime/SFML/commits/mipmaps
Its just, after all this time, its probably bitrotted and you need to adapt or reimplement it.

**Comment by binary1248** [comment]
I glanced over those other commits and I still don't get why you chose to emulate `GL_SGIS_generate_mipmap` behaviour even when `glGenerateMipmap` is available. The whole reason why `glGenerateMipmap` was necessary is so that the user can choose themselves when the mipmaps actually get generated. Making it happen automatically as with the older extension and not giving the user any control over it whatsoever eliminates all the advantages `glGenerateMipmap` is supposed to have.

If SFML is going to support mipmap generation, it will have to be explicit, as part of the public API. The users who don't know/care about mipmaps can just ignore it and those who do know/care about mipmaps will know when to generate their them manually anyway (if mipmaps are even beneficial in their scenario).

**Comment by wintertime** [comment]
The reason had been that SFML code had to have support for ancient OpenGL 1.x and therefore the inferior method using the texture parameter had to be supported and that is the only way this method can be used.
Its also the least intrusive method, allowing full backwards compatibility (which was mandated for SFML code, as RenderTexture was also maintaining the fallback path without EXT_FBO) - people can just ignore the method to activate mipmapping and would have the same texture only doing ugly nearest filtering they always had.
I did not watch SFML development anymore, have you finally ditched support for ancient OpenGL meanwhile?

Btw., most people would only load most textures from file once, then use it. If the PR had required them to explicitly call mipmap generation it would have had even less chance of being merged and might have been closed with "thats not what the S in SFML says, our beginner users would never know if/when this new redundant call is necessary".

**Comment by binary1248** [comment]
SFML hasn't ditched support for ancient OpenGL. That also doesn't mean that support for mipmap generation has to be mandatory.

As you said yourself, if mipmap generation isn't supported in the way SFML needs it to be, then the user will just have to stick with textures without mipmaps. It doesn't break anything in any way and doesn't cut out users with really old hardware. In fact, most users who could use it probably wouldn't anyway since they wouldn't benefit from it in the first place.

Mipmaps only really provide a benefit if you minify your textures, meaning that a texel is going to be smaller than a logical pixel on the final framebuffer. Providing a sub-optimal implementation that automatically creates mipmaps whenever a texture gets updated will make mipmap generation less appealing to users who have the required hardware and who know/understand that they will benefit from mipmaps (e.g. a lot of zoomed out sprites, OpenGL interoperation, etc.), and that is the target audience of mipmap support in SFML.

SFML hasn't, and probably won't for a while, ditched old hardware. It's just time that the library started to support _optional_ functionality that users with newer hardware might want to take advantage of. `sf::Shader` already did it long ago, I don't see why it can't be done in other areas as well.

**Comment by eXpl0it3r** [comment]
Merged in 259811d59c7aedc3b5b477685dfd027fb9f961b4
