### ISSUE TITLE
IOS Port - a few weird points and get-arounds.

### ISSUE THREAD

**Issue by LiO2** [SFML/SFML#1231]
SFML 2.4.2 (2017-05-08) IOS Port:

the new version I downloaded on the 2017-05-08 and tried has some issues:

1. In cmake the audio module has been removed by default for the IOS target? 
Why? I re-enabled it manually (SFML_BUILD_AUDIO=TRUE), built my test project... sound works fine.

2. A bit more annoying is the fact that, while the ios-extlibs have been updated (thanks a lot) a little note about the necessity to link with libz and libbz2 (for freetype2.a) would have been nice.

cheers.

Also, When the IOS Device (iPad)  is reorientated, it is detected but the resize event sends the same width and height whatever the orientation.

**Comment by eXpl0it3r** [comment]
Thanks for the hints.

We currently lack a person who is willing to help maintain the iOS port, meaning there hasn't been anyone who tested the complete iOS code base in a while.

> In cmake the audio module has been removed by default for the IOS target?

I'm not quite sure why the audio module is disabled by default. It might be because back when the code was first written we still used libsndfile which can't be statically linked, so we couldn't implement the audio module for iOS. If you say it works fine, we probably could change that option,

> A bit more annoying is the fact that, while the ios-extlibs have been updated (thanks a lot) a little note about the necessity to link with libz and libbz2 (for freetype2.a) would have been nice.

Since libraries get linked statically, all the dependencies need to be linked. On all the other platforms freetype hasn't needed libz or libbz2, as such there isn't any hint. A quick Google search shows that there are options to "remove" the dependencies when building freetype.

If you have the time, maybe others will appreciate if you could summarize your steps for getting SFML work for iOS, for example on the [community wiki](https://github.com/SFML/SFML/wiki/Tutorials).

> Also, When the IOS Device (iPad) is reorientated, it is detected but the resize event sends the same width and height whatever the orientation.

Would you be willing to help us fix this issue?

**Comment by LiO2** [comment]
Thks for the quick answer Lukas,
I'll be posting a how-to IOS on the wiki in a while (I put a pin in it)It won't in the short future though. I'm currently working on a OSX/IOSgame using SFML and I'm getting a bit rushed for time. But the moment I'm done, I'll take some time to write a few articles and even to help with the IOS part of SFML.
Best regards,Lio.

 


      De : Lukas Dürrenberger <notifications@github.com>
 À : SFML/SFML <SFML@noreply.github.com> 
Cc : LiO2 <chezlio@yahoo.com>; Author <author@noreply.github.com>
 Envoyé le : Mardi 9 mai 2017 13h15
 Objet : Re: [SFML/SFML] IOS Port - a few weird points and get-arounds. (#1231)
   
Thanks for the hints.We currently lack a person who is willing to help maintain the iOS port, meaning there hasn't been anyone who tested the complete iOS code base in a while.
In cmake the audio module has been removed by default for the IOS target?
I'm not quite sure why the audio module is disabled by default. It might be because back when the code was first written we still used libsndfile which can't be statically linked, so we couldn't implement the audio module for iOS. If you say it works fine, we probably could change that option,
A bit more annoying is the fact that, while the ios-extlibs have been updated (thanks a lot) a little note about the necessity to link with libz and libbz2 (for freetype2.a) would have been nice.
Since libraries get linked statically, all the dependencies need to be linked. On all the other platforms freetype hasn't needed libz or libbz2, as such there isn't any hint. A quick Google search shows that there are options to "remove" the dependencies when building freetype.If you have the time, maybe others will appreciate if you could summarize your steps for getting SFML work for iOS, for example on the community wiki.
Also, When the IOS Device (iPad) is reorientated, it is detected but the resize event sends the same width and height whatever the orientation.
Would you be willing to help us fix this issue?—

**Comment by eXpl0it3r** [comment]
I'm closing this for now, but feel free to discuss potential changes on [our forum](https://en.sfml-dev.org/forums/index.php). We're still looking for people to help us out with iOS development!
