### ISSUE TITLE
Add support for MP3

### ISSUE THREAD

**Issue by dexter3k** [SFML/SFML#1232]
The longest-running [mp3- related patent](https://www.google.com/patents/US6009399) is **expired** as of 16th April, 2017. This makes `.mp3` patent-free in US too. Also licensing program [has been terminated](https://www.iis.fraunhofer.de/en/ff/amm/prod/audiocodec/audiocodecs/mp3.html).
So, why not to add support for it in the Audio module?

- [x] Implement decoder (reader): With [minimp3](https://github.com/lieff/minimp3), see #1851 ~~#1796~~
- [ ] Implement encoder (writer): See #2679

**Comment by j4cobgarby** [comment]
Correct me if I'm wrong but as far as I can tell, the actual specification for the mp3 format costs almost 200 euros.

**Comment by minirop** [comment]
not anymore. it's now in the public domain.

**Comment by j4cobgarby** [comment]
Oh okay, if someone assigns me to this I'll have a go

**Comment by MarioLiebisch** [comment]
Just do it, then create a pull request and refer to this issue by mentioning `#1232` in the text.

**Comment by j4cobgarby** [comment]
Okay, on it

**Comment by ricanteja** [comment]
How is development on this coming along @j4cobgarby? I might take it on myself if you take too long :)

**Comment by j4cobgarby** [comment]
@ricanteja Feel free to have a go yourself - I've got a lot going on and probably won't be able to make much progress for a couple of weeks :)

**Comment by ricanteja** [comment]
Okay so I've been spending way too much time on this and not really making any progress (while surviving a hurricane). I've looked into MAD, mpg123, LAME to try and figure this out but they all have their challenges. 
Challenge #1 is getting these libraries to build. Damn auto make. The build system is so convoluted good luck trying to figure out what broke.
Challenge #2 is licensing. MAD is GPL, while mpg123 and LAME are LGPL, but it doesn't matter because I can't build either one of them!

If anyone has any experience with GNU auto tools or has built mpg123 before please ping me in this thread. I'd love to get MP3 support in SFML but I'm starting to wonder if it is worth the headache. All this just to support 1 more file type?

**Comment by eXpl0it3r** [comment]
So we only got GPL or LGPL as option? Adding another must have shared library dependency doesn't sound very exciting...

I've played around with GNU auto tools on Windows a bit for the other dependencies, but it really isn't very nice, but still doable if their automake file is useful.

**Comment by ricanteja** [comment]
I don't even want to think about what compiling these libraries for mobile platforms will look like... *shudders*

I just don't think it is worth the headache at this point but I'm curious what others think.

**Comment by eXpl0it3r** [comment]
IMHO as long as we can't find a non GPL/LGPL MP3 decoder I wouldn't want to add it. Vorbis and soon [opus](https://github.com/SFML/SFML/pull/1259) offer better compression vs file size, but I do understand the wish for MP3 support as a multimedia library.

**Comment by feliwir** [comment]
I have used mpg123 in the past and it was working very nicely. I guess @ricanteja i struggeling to compile because of the assembler parts?

**Comment by lieff** [comment]
@eXpl0it3r Hi, I'm working on non GPL MP3 decoder: https://github.com/lieff/minimp3

**Comment by eXpl0it3r** [comment]
@lieff Interesting! 🙂 
Any plans on encoding support? 😉

**Comment by lieff** [comment]
Currently no plans about encoder, but I can reconsider if it's needed =)

**Comment by eXpl0it3r** [comment]
Fact is that SFML currently provides encoding and decoding for all the supported formats, as such the argument for adding a new format in an asymmetrical way, is harder to get accepted.

**Comment by MarioLiebisch** [comment]
I'd claim that MP3 would be popular/useful enough to even accept asynchronous handling for now, especially considering it would cover most popular use cases.

**Comment by LaurentGomila** [comment]
Audio encoders and decoders are clearly split exactly for this purpose: to allow some formats to only have one. In my opinion, it's totally fine to be able to read MP3 but not write it. It should not block its integration into SFML.

**Comment by eXpl0it3r** [comment]
@ricanteja Do you feel motivated to give this another go with minimp3?

**Comment by LaurentGomila** [comment]
@lieff what's the status of your library? It looks complete but you said you were working on it, so I'm wondering if it's ready to be used.

**Comment by lieff** [comment]
@LaurentGomila It's fully feature complete. I'm still working on test procedure checking, check more compilers and further optimization. I will look at encoder later, I think it's not so hard to create quality/speed unefficient encoder.

**Comment by lieff** [comment]
I found BSD 2-Clause mp3 encoder from Andreas Johansson. Is it good enough license?

**Comment by LaurentGomila** [comment]
Sure it is.

**Comment by lieff** [comment]
Well then, I'm created repo with it https://github.com/lieff/mp3-enc-bsd
Now we have both, decoder and encoder.

**Comment by LaurentGomila** [comment]
Do we have more information about this encoder? Has it been tested? Is it bug-free? etc.

**Comment by lieff** [comment]
Encoder testing is more complicated than decoder (because we have no precise reference to compare with). I've tested it briefly and found over-read problem ([mp3 @ 0x7fc72c002700] overread, skip -4 enddists: -1 -1), but files are playable and quality is acceptable. I will fix this problem later.

**Comment by lieff** [comment]
About encoder - I think It's from old freebsd/linux. Mentions can be found on old sites http://linux-sound.org/mpeg.html  http://sunsite.univie.ac.at/Linux-soundapp/mpeg.html but archive is hard to find.

**Comment by stackyjoe** [comment]
What is the status on this? Is the bottleneck the lack of volunteers to write the necessary SoundFileReader adapter class?

**Comment by lieff** [comment]
SoundFileReader should be easy. Is it's ok without SoundFileWriter, I can give it a try.
For writer here another option https://github.com/cpuimage/tinymp3
No mention of license though, but it should be GPLv2 like in shine.

**Comment by eXpl0it3r** [comment]
GPL doesn't work together with SFML's license.
If you can provide an SoundFileReader for minimp3, then we can certainly accept that and keep looking for encoder libraries.

**Comment by fdakgg** [comment]
If decoding is ready, can we add the play functionality? Encoding looks more complicated.

**Comment by MarioLiebisch** [comment]
As @eXpl0it3r mentioned, having it just read files for now certainly would be something nice to have, no need to wait for a writer. Just add a note somewhere that MP3s can be loaded, but not written.

**Comment by heretic13** [comment]
My vote for support MP3

**Comment by heretic13** [comment]
2,5 years of discussion. No result!!!

**Comment by Bromeon** [comment]
I agree that we should start with the decoder to read MP3. Encoding can be done separately. But it's sad if this whole sinks into oblivion because of the encoder alone.

@lieff are you still willing to integrate your decoder into SFML?

**Comment by lieff** [comment]
Well, yes. Will try get to this in next weekend.

**Comment by lieff** [comment]
Here rough mp3 reader support https://github.com/lieff/SFML/commit/f3e5c039a8302419c00a2c4eca009f67b5ec9dbc .

Currently whole file readed to memory at open() time. Need to finish mp3dec_ex_* api for proper streaming and seek to sample. Sample added to SFML/examples/sound/.

Is it enough to make first PR?

**Comment by LaurentGomila** [comment]
> Is it enough to make first PR?

If it's not finished (proper streaming) then you should probably complete it first :wink:

**Comment by lieff** [comment]
Not like it's not finished, It's dependent on usage pattern. Disadvantages of pre-decode whole file is memory usage and decode time. But since we need to fill info.sampleCount at open() time - this is whole file scan for mp3 anyway and there will be lag depending on hdd speed anyway. So it may be acceptable in some cases and may be not in others.

Here simple benchmark: one hour mp3 file (88 megabytes), 48000 Hz, stereo, 192 kb/s.
Decode time - 3.4 seconds on i7-6700K CPU. So for more common ~8mb ~6min track it will be 0.34 seconds which can be acceptable lag. This scheme also can be further optimized using multi-threaded decode (which can't be used in streaming mode since frames dependent from previous and it needs big chunks of file).

Streaming mode brings less memory usage and open() lag decreases to file load time, without decode part. If we do not need precise track length knowledge - we can also omit file scan, but it needs API change?

**Comment by LaurentGomila** [comment]
> Not like it's not finished, It's dependent on usage pattern.

The low-level decoding classes are supposed to be implemented using streaming; then it's up to higher-level classes to decide what to do (pre-load everything or stream content). Isn't streaming possible with MiniMP3?

> But since we need to fill info.sampleCount at open() time

We can usually know the total sample count without decoding the whole file (using metadata). I would be surprise if the MP3 format didn't allow that.

So, it would really be better if the MP3 back-end was implemented like all others. If the library is too limited then we can have a look at others.

**Comment by lieff** [comment]
OK, I will finish streaming mode first, just bit more code (probably next weekend again).

>We can usually know the total sample count without decoding the whole file (using metadata). I would be surprised if the MP3 format didn't allow that.

Yes, mp3 is more like elementary stream, not container format like ogg. Track length also can be stored in ID3 (TLEN Text information frame), but in milliseconds precision and may not present. There also can be "Info"/"Xing" VBR tags, but again it may not present in file and needed fields like num frames also optional. So we can avoid scan only if VBRTag found, needed fields present and this information is correct.

**Comment by lieff** [comment]
Here initial streaming version: https://github.com/lieff/SFML/commit/95018ee9ca8be5f89f657c823de09eed479f1b62

Still some improvements can be done:
 * Handle VBR Tag and omit file scan.
 * Use binary search for seek instead of index scan (not sure if it helps much in real scenarios).
 * Do not cache input file and re-read it after initial scan & rewinds?
 * Tune skip samples on seek. In mp3 not all frames can be decoded form start because of bit-reservoir.

Also seek() needs some testing. How to add seek test in Sound.cpp example properly?

**Comment by lieff** [comment]
All major improvements have been done. I'll wait for feedback a bit and then make a PR.

**Comment by ipatix** [comment]
Are there any updates on the progress (if there is at all)?

I was looking for a library that can do sound including MP3 without having to combine multiple libraries manually.

**Comment by lieff** [comment]
@ipatix You can try https://github.com/lieff/SFML master branch. Currently I do not know any issues related to SFML integration, but there 2 things which stops me from release a PR:
* Big APEv2 tag at end of file prevents it's removal in streaming manner, i.e. we need seek at the end of file, (virtually) remove the tag and seek back. This is the only case when we need such jumps, id3v1 and small APEv2 can be safely removed by reading file chunks linearly. I think how better support this case with minimal API changes, for callback support we need ftell() function, or provide file size on open.
* I want to add scan limit to not read whole big file in case if it's not mp3 file.

Otherwise, it's should be ready to use.

**Comment by 1aam2am1** [comment]
Is there mp3 support now in 2021 or are there some problems with it?

**Comment by lieff** [comment]
https://github.com/lieff/SFML branch should work, with issues mentioned above.

**Comment by eXpl0it3r** [comment]
@lieff For the APEv2 issue, what's the impact from the view point of SFML? Would it crash? Fail to stop?

I think, even if there are some limits with certain flavors of MP3 formats, it might be beneficial to add it for now, maybe with a warning regarding APEv2 tags.

Just tested it locally and it worked great. 🙂

**Comment by lieff** [comment]
@eXpl0it3r It should not crash, worst case APEv2 data will be treated as mp3 and very low chance some garbage decoded.

I guess your are right, it's probably already good enough. Here PR https://github.com/SFML/SFML/pull/1796 .
I'll just create another one when the new functionality is ready.

**Comment by dnr7** [comment]
I'm not sure if mp3 support for sfml is working or not. If it isn't miniaudio is public domain or mit which really means public domain, and it has an mp3 decoder.

**Comment by eXpl0it3r** [comment]
Closing this issue, to reduce confusion on the more commonly association of "MP3 support" with "playing MP3 files" and have opened #2679 instead.
