### ISSUE TITLE
Stop including all of windows.h from OpenGL.hpp

### ISSUE THREAD

**Issue by schmerm** [SFML/SFML#1234]
The SFML include file OpenGL.hpp #includes all of windows.h just for a handful of defines so that gl.h can be included. The comment itself reads:

    // The Visual C++ version of gl.h uses WINGDIAPI and APIENTRY but doesn't define them
    #ifdef _MSC_VER
        #include <windows.h>
    #endif

    #include <GL/gl.h>

windows.h is huge and pollutes the global namespace. Consider simply defining the necessary macros. See GLEW's glew.h to see how it solves the same problem.

**Comment by mantognini** [comment]
Unless those are officially and properly defined to something stable (i.e. it's not something implementation-defined), I don't think this is a good idea. I would not base the decision on some other 3rd party library having the same issue.

**Comment by MarioLiebisch** [comment]
They're essentially stable since at least Windows 3.11 I'd assume. Overall I'm not really happy with how SFML includes WinAPI headers here and there redefining versions etc. anyway, so think there's no problem changing this for SFML 3.x.

**Comment by eXpl0it3r** [comment]
This seems easy enough to replace:

```
#define WINAPI      __stdcall
#define APIENTRY    WINAPI
```

I'm not sure what the dependency for this one is with GDI though:
```
//
// Define API decoration for direct importing of DLL references.
//

#if !defined(_GDI32_)
#define WINGDIAPI DECLSPEC_IMPORT
#else
#define WINGDIAPI
#endif
```

There's also this line in my `gl.h`:
```
#pragma region Desktop Family
#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)
```

I don't know if changing the include really makes sense.

**Comment by binary1248** [comment]
Is this really an issue that has any measurable significance?

One has to consider the following points:
* MinGW's `<GL/gl.h>` has a `#include <windows.h>` in it, so you lost there already
* Nobody who wants to take OpenGL seriously will rely on the built-in `<GL/gl.h>` anyway. As you already know, they will always have to resort to some loader to get access to the good stuff
* What GLEW does in its header isn't easy to comprehend, and I have already had my share of fun combining glew.h with Windows headers in the past because of this (sarcasm intended)
* If you really rely only on the OpenGL 1.1 in the majority of your source files, you are going to have performance problems anyway
* I don't know about you, but I don't feel any difference whether defining the stuff myself or including windows.h in its entirety

I must admit, currently I can't think of a reason to use `#include <SFML/OpenGL.hpp>` over some form of loader, unless you are a beginner just starting out in the scene (which implies you have other things to worry about than compilation time). It is one of those historic things that should just be left to die away slowly in peace, just like GLU already did.

**Comment by binary1248** [comment]
Closing this issue for now since it doesn't bear enough significance to warrant a risky change.
