### ISSUE TITLE
Loading certain ogg files causes program to hang forever in 2.4.2 that loaded and played in 2.1

### ISSUE THREAD

**Issue by jamiltron** [SFML/SFML#1243]
Hello,

I am updating an application that uses sfml-audio from 2.1 to 2.4.2 that consistently hangs forever when loading certain ogg files. These files did not hang in 2.1, and it is only specific files that cause this.

Here is a link to one of the ogg files that causes our program to hang: https://www.dropbox.com/s/1gxh56ym6kk2nla/hangs_forever.ogg?dl=0

Here is a link to a minimal example showing the error, assuming the above ogg file is downloaded into the working directory: https://gist.github.com/jamiltron/ada86682674717ab0bd9e0f2f90343dc

The above fails if you remove the stream and change the .openFromStream(stream) to .openFromFile("hangs_forever.ogg"). This file plays fine in every media player I've tried, and also loads and plays using another client solution.

This happens on Windows 10 with both the 32-bit Visual Studio 2015 prebuilt, as well as a version built from source containing the following patch to libvorbis: https://trac.xiph.org/ticket/2327

This file plays fine in Windows Media Player, VLC, Audacity, and is

Any help is greatly appreciated!

**Comment by eXpl0it3r** [comment]
As already stated in your [previously reported "issue"](https://github.com/SFML/SFML/issues/1241). Please follow the [contribution guidelines](https://www.sfml-dev.org/contribute.php).

This issue track is reserved for confirmed bugs only. Use the forum instead to discuss your specific problems that may or may not be related to SFML itself.

Since this sound quite similar to your previous issue, did you confirm that this isn't an issue with your own code? If you don't use your own stream class does it load fine (yes it does)? If so, it more likely is an issue with your own stream class (as mentioned before) and not SFML itself.

**Comment by jamiltron** [comment]
> Since this sounds quite similar to your previous issue, did you confirm that this isn't an issue with your own code?

If its an issue with my stream implementation, why does it work fine in SFML 2.1 but not in SFML 2.4.2?

> If you don't use your own stream class does it load fine (yes it does)?

As I said in the issue above, it does not load fine.

**Comment by LaurentGomila** [comment]
> If its an issue with my stream implementation, why does it work fine in SFML 2.1 but not in SFML 2.4.2?

I guess we could check how libsndfile (used in SFML 2.1) was using libvorbis, compared to how SFML 2.4 now uses it directly.

**Comment by mantognini** [comment]
For quick reference: https://en.sfml-dev.org/forums/index.php?topic=22128.0
