### ISSUE TITLE
SFML fullscreen should not cover all monitors

### ISSUE THREAD

**Issue by bernardosulzbach** [SFML/SFML#1354]
I know that there is no support for configuring multiple monitors, and this is not what I am reporting. I am reporting behavior which really seems like a bug.

If I launch a sf::Style::Fullscreen window on my Linux computer I get a 3840 x 1080 window that completely covers both 1920 x 1080 monitors.

Specifying the resolution of a single monitor produces "The requested video mode is not available, switching to a valid mode" and I get the same 3840 x 1080 screen.

sf::VideoMode::getFullscreenModes() returns the following vector:

```
3840 x 1080
1440 x 900
1400 x 1050
1366 x 768
1280 x 1024
1280 x 800
1280 x 720
1152 x 864
1024 x 768
800 x 600
640 x 480
```

Using anything from this list which is not 3840 x 1080 causes some flickering and leaves me with a window (with title bar and close button) with the specified resolution.

I would expect fullscreen not to stretch to multiple monitors.

Tested with Linux 4.14.14-1 with Gnome 3.26.1, building from 341bc2a.

**Comment by eXpl0it3r** [comment]
Linux' window managers and X11 are really not easy to bend to your will...

* What's your display setup, meaning how did you set up your multiple screens?
* What GPU do you use?
* What GPU driver do you use?
* What's the example code you use?

I mean if the system reports the resolution as official fullscreen mode, it's not really surprising that this actually is used by SFML. However why it would flicker and show as window otherwise, seems a bit strange.

See also #1226, #1238 and potentially some more issues.

**Comment by mafagafogigante** [comment]
One is the primary, the other is the secondary (these are just the way openSUSE left them, I've never managed them myself).

It is a GTX 750 running the proprietary driver, version 384.111.

It was being created by something similar to this piece of code:

```cpp
  BK::U32 style = sf::Style::Fullscreen;
  BK::Resolution resolution{sf::VideoMode::getDesktopMode().width, sf::VideoMode::getDesktopMode().height};
  if (configuration.isWindowed()) {
    style = sf::Style::Titlebar | sf::Style::Close;
    if (preferences.getDefault().hasResolution()) {
      resolution = preferences.getResolution();
    }
  }
  sf::ContextSettings settings(24, 8, 8);
  const auto windowResolutionWidth = static_cast<unsigned int>(resolution.getWidth());
  const auto windowResolutionHeight = static_cast<unsigned int>(resolution.getHeight());
  const sf::VideoMode videoMode(windowResolutionWidth, windowResolutionHeight);
  sf::RenderWindow window(videoMode, "Window", style, settings);
```

Not only there is the "fallback" to windowed using what it considers a valid fullscreen resolution, but it also doesn't mention 1920 x 1080 as a fullscreen resolution. However, I do imagine that this might be due to the window manager and xrandr being difficult to deal with.

I do understand that figuring out how to fix this might be quite the hassle. I will probably change to SDL, but thought it was worth reporting. If you ever want me to test this with another revision of SFML just let me know.

**Comment by eXpl0it3r** [comment]
As we've introduced from fixes with #1226 for SFML 2.5.1 can you check SFML master again, if it solves your issue?

**Comment by bernardosulzbach** [comment]
I'm going to fetch and test that commit now.

**Comment by eXpl0it3r** [comment]
Thanks a lot for retesting this!
