### ISSUE TITLE
Add extlibs for arm64-v8a and x86_64 on android

### ISSUE THREAD

**Issue by AlexAUT** [SFML/SFML#1507]
The included extlibs do not provide binaries for all [supported ABIs](https://developer.android.com/ndk/guides/abis) of the current NDK.

I could update the scripts and make a PR but since it will contain binaries probably a team member should do it?

**Comment by MarioLiebisch** [comment]
Feel free to update the scripts, but maybe the better solution would be to find some way to allow people to build them themselves. I'm not a real fan of binaries in a repository. It's less about security for me, but bloat (thanks, slow internet connection!).

In theory, CMake is capable of downloading and building most dependencies as an external project. I think the only one which always gave me trouble is libFLAC.

**Comment by JonnyPtn** [comment]
Yes, Cmake has some great functionality to checkout and build dependencies, that would be my preferred way to handle them too

**Comment by DanielDorn** [comment]
the SFML team could always create a separate repository for dependencies and create build scripts for them and add the sfml-dependencies repository as a git submodule to the sfml repository thus providing both build scripts for all dependencies and by adding it as a submodule ensuring the end user receives the dependencies, you could even make the SFML cmake build script build dependencies if they haven't been already completely automating the process, i have already done this with my engine which uses SFML as its base, though my code wont be compatible since i merely used SFML source not the library directly

**Comment by eXpl0it3r** [comment]
This has been implemented with #2165
