### ISSUE TITLE
sf::Keyboard::isKeyPressed() bug

### ISSUE THREAD

**Issue by MrBattary** [SFML/SFML#1583]
## Subject of the issue

The program does not respond to pressing some keys.
"if" with "sf::Keyboard::isKeyPressed()" just skips.
This problem only appears when we use cheap keyboards, but when we had connected with help of pricey gaming keyboard, all had been working correctly.

## Your environment

* Your OS / distro / window manager used - Windows 10 64 bit
* Your version of SFML (2.5.0, git master, etc) - SFML-2.5.1-windows-vc15-64-bit
* Your compiler and compiler version used - VS17
* Special compiler flags used - none

**Comment by eXpl0it3r** [comment]
Sounds like you're pressing multiple keys at the same time and some don't get registered. That's a hardware issue and the reason it works with "Gaming" keyboard is because those are built with [n-key/multi-key rollover](https://en.wikipedia.org/wiki/Rollover_%28key%29#n-key_rollover).

Can you confirm that this is only an issue if you press multiple keys at the same time?

**Comment by MrBattary** [comment]
> Sounds like you're pressing multiple keys at the same time and some don't get registered. That's a hardware issue and the reason it works with "Gaming" keyboard is because those are built with [n-key/multi-key rollover](https://en.wikipedia.org/wiki/Rollover_%28key%29#n-key_rollover).
> 
> Can you confirm that this is only an issue if you press multiple keys at the same time?

Yeap, thats true. But, why does problem exist partially? W+D+C works correctly, W+S+C doesn't works.(The order of keystrokes doesn`t matter.)

**Comment by MarioLiebisch** [comment]
The term you're looking for is "ghosting" or "keyboard matrix". There should be tons of resources out there to learn more.

The short version: Typical keyboards have 100+ keys. To query those in the traditional and most obvious way you'd need 100 switches all connected to their own, individual digital inputs. To cut corners (space and costs), keyboards use (de-)multiplexing.

So instead of having individual inputs for each and every key, multiple keys are mapped to the same digital input. To differentiate which key has been pressed (since they'd all trigger the same input), you use multiple outputs to only power a specific subset of keys, forming a matrix. For example, if both keys for 1 and A are connected to an input and your input is only high when 1 is powered, you know that 1 has been pushed rather than A.

Randomly picked example clip on YouTube:
https://www.youtube.com/watch?v=RGkIHFQf8-w

Also worth noting, the actual patterns that work together or don't depend on the physical keyboard layout. This might differ between manufacturers, models, or even revisions. Don't rely on it.
