### ISSUE TITLE
Allow storing Sockets directly into SocketSelector

### ISSUE THREAD

**Issue by Shadowblitz16** [SFML/SFML#1621]
## Subject of the issue
Please add the ability to store, loop through and get sockets directly into a socketselector.
right now we have to store our sockets into a vectors or list which shouldn't be necessary since socket selector already holds onto sockets in some sort of way.

I propose that..
1. a indexer be made available.
2. a getCount() or getLength() method be made available .
3. allow the user to set a max amount of sockets of a socketSelector

## Your environment
Windows 7 Ultimate 64 bit
SFML 2.5.0
Visual Studio 2019 Community
*No compiler flags I know of*

**Comment by JonnyPtn** [comment]
I'm not convinced this is a good idea. While it may be suitable for your use case, it restricts a bunch of other different use cases, for example I couldn't have multiple vectors of sockets which all use one socket selector, I'd need to have multiple socket selectors?

Also how would you know the types of the socket, for example if I have a mixture of TCPListener, TCPSocket and UDPSocket in the selector, Am I expected to use runtime type information? Many people don't like that.

**Comment by Shadowblitz16** [comment]
it doesn't restrict anything because it would be a optional feature.

**Comment by Bromeon** [comment]
The main problem I see is ownership. You say it's an optional feature, but `sf::SocketSelector` would then have 2 APIs:
* one that stores sockets (the one you propose)
* one that references sockets (the existing one)

`addSocket()` would still only reference the sockets, and there would need to be a weirdly named counterpart for storing sockets. How would you even store the non-copyable sockets without move-semantics (SFML is still C++03)? Manual memory management is definitely a bad API choice.

And the problem @JonnyPtn mentioned is still there: when iterating sockets, you would need to do some sort of RTTI (`dynamic_cast`, `typeid` or manual type identifiers), or you might just store statically typed pointers elsewhere.

With all those problems and the extra confusion a dual API would bring, I don't really see the benefits. You might even store socket references separately in a GC language due to extra type safety (no downcast needed).

**Comment by Shadowblitz16** [comment]
I don't even remember why I posted this. 
I just know that setting up the networking required a lot of code which I felt could be shorter.
i'm closing this due to me not using the library anymore. I don't really like the c++ language anyway.
