### ISSUE TITLE
JACK audio output/input?

### ISSUE THREAD

**Issue by mxmilkiib** [SFML/SFML#1647]
Might [JACK audio](https://jackaudio.org/) output be a possibility some day in the future? The graph patchbay features are superb, and port metadata allows for pretty names and [CV](https://linuxmusicians.com/viewtopic.php?f=1&t=20701).

**Comment by MrZeusTheCoder** [comment]
Hmm. Very interesting. This sounds like a great feature! I wonder if it might be slightly out of scope of the current SFML audio module, though. I honestly don’t know though.

Also you may just want to flesh out what exactly think should be supported, and even make a PR if you got something working. Either way some ideas as to the API would be nice. Audio is one of my (probabbly too many) hobbies. I would love to take a stab at the JACK docs, but a goal is essential.

**Comment by MrZeusTheCoder** [comment]
Ok. Small bump. I had conversation on the [SFML Discord server](https://discord.com/invite/nr4X7Fh) a while ago asking about this. A few of the contributors said it was out of scope atleast for 2.6.0, but beyond that we were honestly just confused what you wanted to accomplish (and sort of what JACK was, :P). So it's kinda a bump on asking you what you want to see, @mxmilkiib. :smiley:, have a good one!

**Comment by mxmilkiib** [comment]
If the JACK homepage overview isn't enough, [this](https://www.youtube.com/watch?v=fEduGnD6ZKQ) unfa video is a good introduction. No worries though if it is out of scope.

**Comment by MrZeusTheCoder** [comment]
Thanks. +1 for the link.

Still my point stands that you need to flesh out what you mean by input/output before anyone deem it out of scope or not.

Anyway, have a good day, @mxmilkiib !

**Comment by eXpl0it3r** [comment]
We currently exclusively depend on OpenAL as our audio output backend. We may want to look into alternative backends, especially since iOS has deprecated the OpenAL APIs, but currently I don't really see this as any priority.
As for JACK itself, I don't really see the big advantage, nor does anyone have the capacity or priority to pick this up. If anyone would isolate the audio API calls and implement JACK as additional backend, I think we would accept such a PR, but it's quite a bit of work.
