### ISSUE TITLE
Build error: Missing item in X11_X11_LIB;X11_Xrandr_LIB

### ISSUE THREAD

**Issue by vapniks** [SFML/SFML#1654]
I get the following error when trying to build 2.5.1 from source on Ubuntu 18.04 with cmake 3.10.2: 
```
CMake Error at cmake/Macros.cmake:296 (message):                                                               
  Missing item in X11_X11_LIB;X11_Xrandr_LIB                                                                                                                            
Call Stack (most recent call first):                                                                                                                                    
  src/SFML/Window/CMakeLists.txt:239 (sfml_find_package)
```
I was following the instructions listed here: https://pryp.in/blog/12/build-sfml-and-csfml-on-linux.html

**Comment by LaurentGomila** [comment]
Have you tried to install the corresponding packages (X11, Xrandr)?

**Comment by eXpl0it3r** [comment]
The linked instructions are not uptodate. You'll also need xrandr and you don't need xcb, libsndfile, or libjpeg, plus it's probably better to install the mesa OpenGL driver, instead of glut. The [FAQ has a better list](https://www.sfml-dev.org/faq.php#tr-lnx-compile), but I think that one is still incomplete as it misses udev and xrandr.

Either way, please use [the forum](https://en.sfml-dev.org/forums/index.php#c3) when you need help with SFML, we try to reserve the issue tracker for actual issues related to SFML. 😉
