### ISSUE TITLE
Guide to use SFML .Net Core on MacOS X

### ISSUE THREAD

**Issue by daybson** [SFML/SFML#1678]
I did everything until the step "Basic Application" on this tutorial: 
https://github.com/SFML/SFML/wiki/Tutorial:-SFML.Net-on-OSX

But I'm no able to follow this tutorial on MacOS to install SFML.net.
"Fixing library paths" step seems to be missing some screenshot, and also, seems to be related to Mono.NET and not .NetCore.

Also seems to be way too complicated (I'm new on MacOS)... All of this still necessary on 2.5 version?
Has someone installed and used with success SFML NET on MacOS ? I could use some help.
Thanks

**Comment by ret394** [comment]
SFML and installation convenience are not on speaking  terms. At least for the C bindings, and consequently for other bindings.

Try to use something else. 3 basic tutorials are not enough. The one linked is complicated due to non-technical reasons, that is, human error.

thanks. have a nice day. keep up the great work. 👏

[ret394](https://github.com/ret394)

**Comment by eXpl0it3r** [comment]
We currently don't have an official guide and unfortunately also no official builds included in the NuGet package.
I hope we can change the last part in the future, which then makes the guide kind of obsolete, as installing a NuGet package, isn't exactly something SFML specific.

If you need help with something, please use the [forum](https://en.sfml-dev.org/forums/index.php?board=14.0). 🙂
