### ISSUE TITLE
[feature] more operators for sf::Vector2

### ISSUE THREAD

**Issue by vfjpl** [SFML/SFML#1727]
This is just a suggestion. std::pair have relational operators https://en.cppreference.com/w/cpp/utility/pair/operator_cmp. 

Would it make sens to also write them for sf::Vector?
"less" than operator would be useful so sf::Vector2 could be used in std::map as a key.

**Comment by Bromeon** [comment]
Geometrically, such an operator makes no sense (a vector cannot be less than another; only its length), as such an overloaded operator would be confusing.

Storing `sf::Vector2f` as a key in a map is most likely a bad idea, since floats are subject to rounding errors, and you may not get the exact same key if you recompute it. For integers it's a different story, but even here, it's better to define your own comparator that you pass to `std::map`, or hasher that you pass to `std::unordered_map`.
