### ISSUE TITLE
sf::Text => ensureGeometryUpdate() => mistake in m_bounds saving, local bounds are wrong

### ISSUE THREAD

**Issue by wiktor8k** [SFML/SFML#1729]
### SFML 2.5.1, Visual Studio, newest version

At the end of `ensureGeometryUpdate()` in `sf::Text` there is this piece of code:
```
// Update the bounding rectangle
    m_bounds.left = minX;
    m_bounds.top = minY;
    m_bounds.width = maxX - minX;
    m_bounds.height = maxY - minY;
```
`m_bounds` is being returned from `sf::Text` using `getLocalBounds()` function and so because `m_bounds.left` and `m_bounds.right` do not have to be always `0.f` (at least I think that's the issue) local bounds can be moved sometimes.

```

        sf::Text text;
            text.setString(L"'\n\n We, are the men \nsheep among wolves");
            text.setFont(*ae::data.assetManager.GetFont("")); //gets default font
            text.setPosition(180,180);

        auto local_bounds = text.getLocalBounds();

        sf::Sprite new_sp;
            new_sp.setTexture(*ae::data.assetManager.GetTexture("")); //gets default texture
            new_sp.setColor({ 255,255,255,120 });
            new_sp.setTextureRect(sf::IntRect(local_bounds));
            new_sp.setPosition(180, 180);

        ae::data.window.draw(new_sp);
        ae::data.window.draw(text);


        // display & wait
        ae::data.window.display();
        std::cin.get();
```
above is a text, and a sprite representing the text's bounding rectangle. The code results in:
![obraz](https://user-images.githubusercontent.com/54490586/102527819-005c6e00-409e-11eb-90ba-f99af3fd9c3e.png)
as You can see, the sprite is a bit too short.

### Solution?
So I tried to replace this code with
```
// Update the bounding rectangle
     m_bounds.left = 0;
     m_bounds.top = 0;
     m_bounds.width = maxX;
     m_bounds.height = maxY;
```
and the renctangle now seems fine, but there are 2 problems:
**the strikethrought does not change the size of `m_bouds` (is this an implementation?)**
![obraz](https://user-images.githubusercontent.com/54490586/102529849-c6409b80-40a0-11eb-8d16-8c4e6e28b6e4.png)
**and the outline also does not affect the size, it just expands the text in top-left direction**
![obraz](https://user-images.githubusercontent.com/54490586/102530010-04d65600-40a1-11eb-8bfb-2cefb5984ed1.png)
Fortunately these two mistakes are hard to notice. I have also tested style, character size, letter spacing and line spacing with the new code. They seem fine.

**Comment by LaurentGomila** [comment]
Ok for strikethrough and outline not expanding the bounding rect, that was probably overlooked when these features were added (they were not part of the initial sf::Text implementation).

However I don't understand what the other issue is. Of couse the local bounds have a non-zero left and top coordinates, as glyphs align on the base-line, not on top, and the first character may not start at x = 0. In your example, the sprite is off because you don't use left/top (setTextureRect only gives the sprite a correct size, not the correct position).

This question is asked frequently on the forum, and using left/top correctly always solves the problem.

**Comment by wiktor8k** [comment]
Alright then, but shouldn't the text be aligned as such it starts with (0,0) point? That would remove the problem with moving it by an offset.

**Comment by LaurentGomila** [comment]
No it can't. Glyphs are aligned on the baseline, and the baseline has a fixed Y offset from the top. Ok, so let's say we adjust the offset of the baseline, so that the tallest glyph always reaches exactly the top, and the bounding rect has no vertical offset. Now, as the text changes, the baseline moves and the whole set of glyphs moves up and down -- definitely no what you want if you need predictable alignment. And imagine an interactive text field where the user can type...

The bounding rect offset on X should always be almost zero, as it's only produced by the first glyph's metrics. But we still need to account for it anyway, for the same reasons as above.

**Comment by wiktor8k** [comment]
I think, I understand, thank you for pointing me that out, and for your work on SFML. You guys are doing an amazing job!
