### ISSUE TITLE
setUniform("texture2", tex) on RenderTexture flipped.

### ISSUE THREAD

**Issue by oomek** [SFML/SFML#1733]
## Subject of the issue

When I draw a RenderTexture with a shader that has an additional texture bound to it it's drawn flipped. Checked the forum, but haven't found anything similar. Still not sure whether it is a bug or not, so please don't shout at me.

## Your environment

* Windows 10
* Your version of SFML (git master)
* Your compiler and compiler version used VS2015

## Steps to reproduce

```cpp
#include <SFML/Graphics.hpp>

int main()
{
	sf::RenderWindow window;
	window.create( sf::VideoMode::getDesktopMode(), "Flip bug", sf::Style::Fullscreen );
	window.setVerticalSyncEnabled( true );
	window.setMouseCursorVisible( false );

	sf::Vector2u size = window.getSize();

	sf::Texture texture;
	texture.loadFromFile( "a.png" );
	texture.setSmooth( true );

	sf::Sprite texture_sprite;
	texture_sprite.setTexture( texture );
	texture_sprite.setScale( (float)size.x / texture.getSize().x, (float)size.y / texture.getSize().y / 2.0 );

	sf::RenderTexture render;
	render.create( size.x, size.y / 2 );

	sf::Sprite render_sprite;
	render_sprite.setTexture( render.getTexture() );
	render_sprite.setPosition( 0, size.y / 2 );

	sf::Shader shader;
	shader.loadFromFile( "shader.frag", sf::Shader::Fragment );
	shader.setUniform( "texture2", texture );

	while (window.isOpen())
	{
		sf::Event event;
		while ( window.pollEvent( event ))
		{
			if (( event.type == sf::Event::Closed )
				|| ( event.key.code == sf::Keyboard::Escape ))
			{
				window.close();
			}
		}

		render.clear();
		render.draw( texture_sprite );
		render.display();

		window.clear();
		window.draw( texture_sprite, &shader );
		window.draw( render_sprite, &shader );
		window.display();
	}

	return 0;
}
```
shader.frag
```cpp
// This shader draws texture on the left using RB channels and
// texture2 on the right using G channel
uniform sampler2D texture;
uniform sampler2D texture2;

void main()
{
	vec4 color1 = texture2D( texture, gl_TexCoord[0].xy * vec2( 2.0, 1.0 ) + vec2( 0.0, 0.0 ));
	vec4 color2 = texture2D( texture2, gl_TexCoord[0].xy * vec2( 2.0, 1.0 ) + vec2( -1.0, 0.0 ));
	gl_FragColor = gl_Color * ( vec4(color2.x, color1.y, color2.z, 1.0 ));
}
```

## Expected behavior
![screenshot2](https://user-images.githubusercontent.com/2974860/103573056-7c8be980-4ec5-11eb-8e6a-6525e18393b8.png)

## Actual behavior
![screenshot](https://user-images.githubusercontent.com/2974860/103572922-48182d80-4ec5-11eb-962c-c24874d5ea65.png)

## Texture used

![a](https://user-images.githubusercontent.com/2974860/103572914-43ec1000-4ec5-11eb-836e-b372d5870f1c.png)

**Comment by eXpl0it3r** [comment]
@binary1248 can you take a look at this? I'm not sure if this is expected behavior or some issue with Shader and RT interaction. 🤔

**Comment by AKonia** [comment]
1) I suppose that it is UB, when you use uniform that you not set.
2) Problem happens because of
render.display() and you can change you SFML source by adding 
```cpp
shader.setUniform( "texture", texture );
```
and as I said remove this 
```cpp
render.display();
```
I don't is it bug, or not, but for some reason this display() function sets
this hint in `src/SFML/Grapics/RenderTexture.cpp`
```cpp
void RenderTexture::display()
{
//....
        m_texture.m_pixelsFlipped = true;
//....
}
```
so I guess changing this line will fix situation, but it's better to ask one, who knows sfml architecture features.

**Comment by binary1248** [comment]
"This is not a bug, it's a feature."®

The problem that you are facing is that you are sourcing from a "normal" texture and an inverted texture within a single shader invocation.

In OpenGL texture coordinate (0, 0) is in the bottom left corner, whereas SFML's texture coordinate (0, 0) is in the top left corner. This was a concious design decision to make it easier for beginners to learn to use the library since it corresponds to what most image manipulation software also use.

When loading image data into an image/texture it is loaded using top-left origin, this also corresponds to the texture coordinates that SFML feeds to OpenGL when specifying vertex data for e.g. sprites. As long as OpenGL reads from a texture, we can manipulate the way it interprets the texture coordinates using e.g. the texture matrix. However, when OpenGL writes to a texture e.g. when it is used as a render target, it will write to the texture using its native bottom-left origin and there is no way to influence that.

There would be 2 ways to solve this problem. The naive solution would be to read the texture back to CPU memory flip it and send it back to the GPU so it has the same orientation as the other texture data. Because GPU-CPU-GPU roundtrips will destroy performance this isn't really a viable solution when the `RenderTexture` has to be drawn to every frame. The smarter solution which does not have a significant effect on performance is to flip the texture coordinate when SFML knows that the texture being read from is flipped because it was written by OpenGL. This is the method SFML chose to use.

What is happening in your program is that SFML is trying to be helpful and automatically adjusting the texture matrix to flip the `RenderTexture` texture to the right orientation for you. Because there is only a single texture matrix, this would be applied to both textures that your fragment shader reads from. The flipped texture is flipped again so it appears the right way around, however the "normal" texture is also flipped by the same matrix and appears up-side-down.

There are multiple ways to solve this. Essentially you need to make sure that textures with differing orientations aren't sampled by texture coordinates that have been multiplied by the same flipping texture matrix. Remember, there is only a single texture matrix set per draw call. It can be flipping or not flipping and it applies to all textures bound to the shader for that draw call.

Here are some excerpts that should help to demonstrate:
```c++
sf::Shader shader;
shader.loadFromFile("shader.vert", "shader.frag");
shader.setUniform("texture2", texture);

while (window.isOpen())
{
    sf::Event event;
    while (window.pollEvent(event))
    {
        if ((event.type == sf::Event::Closed)
            || (event.key.code == sf::Keyboard::Escape))
        {
            window.close();
        }
    }

    render.clear();
    render.draw(texture_sprite);
    render.display();

    window.clear();
    shader.setUniform("unflip", 0);
    window.draw(texture_sprite, &shader);
    shader.setUniform("unflip", 1);
    window.draw(render_sprite, &shader);
    window.display();
}
```

```glsl
uniform int unflip;

varying vec4 texCoord2;

void main()
{
	mat4 texMat = gl_TextureMatrix[0];

	if (unflip == 1)
	{
		texMat[1][1] *= -1.0;
		texMat[3][1] = 0.0;
	}

	gl_Position = gl_ModelViewProjectionMatrix * gl_Vertex;
	gl_TexCoord[0] = gl_TextureMatrix[0] * gl_MultiTexCoord0;
	texCoord2 = texMat * gl_MultiTexCoord0;
	gl_FrontColor = gl_Color;
}
```

```glsl
// This shader draws texture on the left using RB channels and
// texture2 on the right using G channel
uniform sampler2D texture;
uniform sampler2D texture2;

varying vec4 texCoord2;

void main()
{
	vec4 color1 = texture2D( texture, gl_TexCoord[0].xy * vec2( 2.0, 1.0 ) + vec2( 0.0, 0.0 ));
	vec4 color2 = texture2D( texture2, texCoord2.xy * vec2( 2.0, 1.0 ) + vec2( -1.0, 0.0 ));
	gl_FragColor = gl_Color * ( vec4(color2.x, color1.y, color2.z, 1.0 ));
}
```
