### ISSUE TITLE
Create window in the sRGB colorspace

### ISSUE THREAD

**Issue by NicolBolas** [SFML/SFML#175]
It is often useful to create windows that use the sRGB colorspace natively. This is vital for maintaining a linear colorspace through to the screen. The WGL/GLX_framebuffer_sRGB (http://www.opengl.org/registry/specs/ARB/framebuffer_sRGB.txt) explains how to do this.

ContextSetting should have a boolean field for this.

**Comment by binary1248** [comment]
Just out of interest, since I might pick this up at some point: Does OS X support sRGB framebuffers? I know OS X supports the OpenGL extension, but the [pixel format documentation](https://developer.apple.com/library/mac//documentation/Cocoa/Reference/ApplicationKit/Classes/NSOpenGLPixelFormat_Class/index.html) doesn't provide any hints as to how an sRGB framebuffer would be created.

@mantognini do you have any ideas?

**Comment by mantognini** [comment]
I haven't found a clear answer but I *think* it is supported.

However, using OpenGL Extensions Viewer, with a Compatibility profile on a NVIDIA or Intel card, I could find those extensions (some might be aliased):

https://www.opengl.org/registry/specs/ARB/framebuffer_sRGB.txt
https://www.opengl.org/registry/specs/EXT/framebuffer_sRGB.txt
https://www.opengl.org/registry/specs/EXT/texture_sRGB.txt
https://www.opengl.org/registry/specs/EXT/texture_sRGB_decode.txt

Does it help you in some way?

**Comment by binary1248** [comment]
Like I said... I know those extensions are supported. What I want to know is whether I can select a pixel format that provides me with an sRGB framebuffer through the OS X API. If you look in the specification for ARB_framebuffer_sRGB, you will find the new tokens `GLX_FRAMEBUFFER_SRGB_CAPABLE_ARB` and `WGL_FRAMEBUFFER_SRGB_CAPABLE_ARB`. These can be used when specifying a pixel format using GLX (Unix) and Wgl (Windows). There are no tokens for OS X, because... well... OS X context management isn't described in any ARB specifications.

OS X describes its pixel formats through an NSOpenGLPixelFormat object, and its API is maintained by Apple. I've (briefly) read through the documentation and they don't mention sRGB support anywhere.

It could very well be that even in 2015, Apple systems still don't support sRGB OpenGL framebuffers, but if you ask me it is hard to believe. Maybe they do it automatically? I've read that in other areas (not related to OpenGL), Apple has given some thought to supporting sRGB in some way so it seems strange they didn't do it here as well. I was hoping you had come across some OS X OpenGL documentation I have not yet seen regarding this.

**Comment by mantognini** [comment]
Unfortunately no, I've never seen sRGB in the document I've read.

But maybe other libs such as sdl or glfw do implement that...

**Comment by binary1248** [comment]
It's always nice when you learn [something new](https://github.com/glfw/glfw/commit/69a900592e0ce28278ee3c8224838b7e499af698#diff-9e4ea39e73b983e33beb8ef73c8fb558R838). :grin:

I still find it strange though, that I couldn't find any official documentation/information from Apple.

**Comment by mantognini** [comment]
Why am I not even surprised that it was not documented? :unamused:

**Comment by elliotpotts** [comment]
Any progress on this issue? sRGB is also holding me back from using SFML.

**Comment by binary1248** [comment]
I'll probably look into this and the other OpenGL related stuff after gl_dev gets merged. Shouldn't be too long.

**Comment by dezzik** [comment]
Any news? Would be a nice feature to have.

**Comment by binary1248** [comment]
Work is scheduled to begin after pending pull requests affecting the same files have been merged.

**Comment by eXpl0it3r** [comment]
Merged in e00d160224fbdf519aa9e420e57cc8e29e244f31
