### ISSUE TITLE
More functionality for Vectors (2D)

### ISSUE THREAD

**Issue by rasoolZero** [SFML/SFML#1810]
## Subject of the issue

More functions and features for Vectors including but not limited to:

#### fromAngle
Calculates and returns a new 2D unit vector from the specified angle value
#### mag
Calculates the magnitude (length) of the vector and returns the result as a float
#### dist
Calculates the Euclidean distance between two points (considering a point as a vector object)
#### dot
Calculates the dot product of two vectors
#### cross
Calculates and returns a vector composed of the cross product between two vectors
#### normalize
Normalize the vector to length 1 (make it a unit vector)
#### limit
Limit the magnitude of the vector to the value used for the parameter
#### setMag
Set the magnitude of the vector to the value used for the parameter
#### heading
Calculates the angle of rotation for a vector
#### rotate
Rotates a vector by the specified angle while maintaining the same magnitude
#### angleBetween
Calculates and returns the angle between two vectors

I used the Processing PVector class as the reference, here's the link: [PVector](https://processing.org/reference/PVector.html)

**Comment by vittorioromeo** [comment]
I am personally in favour of adding these functions. They are commonly used in many projects, and we're just asking users to reimplement them over and over again if we do not provide them in SFML.

**Comment by Bromeon** [comment]
Maybe interesting: [**Thor/Vectors**](https://github.com/Bromeon/Thor/tree/master/include/Thor/Vectors)
API doc for [2D](https://bromeon.ch/libraries/thor/documentation/v2.1/_vector_algebra2_d_8hpp.html) and [3D](https://bromeon.ch/libraries/thor/documentation/v2.1/_vector_algebra3_d_8hpp.html).

**Comment by binary1248** [comment]
Having had to go through using many different linear algebra libraries over the years I know the pain. If you look at the Vulkan example I even had to implement some functions myself just to not have to drag in external dependencies which would make the example unnecessarily complex.

The nice thing about C++, especially when working with templated code is that you don't pay for what you don't use. Sure, having more facilities in the library will mean additional workload for maintainers, but there is zero cost for the user.

If we are to enrich `sf::Vector` then we should probably also consider doing something with `sf::Transform`. It is really just a matrix with a beginner-friendly name. I would even argue that it is "expert-unfriendly" since most experienced developers would be more familiar with the term "matrix" rather than "transform".

People can find quotes of me saying several years ago that the networking TS would make SFML networking obsolete. Judging by the current state, we are further away than we were 6 years ago (something only the C++ committee is able to achieve). There is a proposal for adding linear algebra to C++, but I'm not going to hold my breath any more after seeing what happened to the networking TS.

**Comment by Ishvina** [comment]
Hi! I am in an intro to swe class that is requiring me to work on my first open-source project. I was wondering if this issue is still open and if so is this beginner-friendly?

**Comment by juanrodl** [comment]
Hello, this is my first time contributing to an open-source project and I'd like to work on implementing some of these functions if possible.

**Comment by ngiridharan** [comment]
Hello, I am new to open-source contributions and would love the opportunity to work on implementing these functions.

**Comment by Bromeon** [comment]
> Maybe interesting: [**Thor/Vectors**](https://github.com/Bromeon/Thor/tree/master/include/Thor/Vectors) API doc for [2D](https://bromeon.ch/libraries/thor/documentation/v2.1/_vector_algebra2_d_8hpp.html) and [3D](https://bromeon.ch/libraries/thor/documentation/v2.1/_vector_algebra3_d_8hpp.html).

Before everyone else is starting an implementation from zero, please note that there has been quite some prior work on this topic. On one hand, people suggested small extensions in the forum over the years; on the other, based on user feedback I integrated vector algebra into my SFML extension library Thor. As ChrisTrasher noted, this task is rather involved and goes beyond just writing a few functions.

I thus wanted to share my work in the PR #1979, hoping that we can use a more complete implementation as a base and don't need to reinvent the wheel 🙂
