### ISSUE TITLE
Wrong directory for example binaries 

### ISSUE THREAD

**Issue by intjelic** [SFML/SFML#189]
Examples binaries shouldn't be placed in /usr/share (or /usr/local/share) since those directories are meant for architecture-independent data. I think /usr/lib/games is a more appropriate directory.

Source: http://www.pathname.com/fhs/pub/fhs-2.3.html#USRSHAREARCHITECTUREINDEPENDENTDATA

**Comment by eXpl0it3r** [comment]
So what should be changed?

**Comment by binary1248** [comment]
The option that I can think of that makes everyone happy for now is to split the install targets:
* The default install target installs the library and headers
* A separate install target installs the examples _somewhere of the user's choosing_
* Another install target installs the documentation _somewhere of the user's choosing_

I chose to separate installing the documentation as well, because let's face it, if you grab the source archive of an official release and build it, you would probably be more inclined to just go to the website than to browse your filesystem for some index.htm file. For master revisions, it's another story, but knowing what to look for (the potentially new stuff) already implies that you follow development which makes having to browse the documentation specially for that new feature irrelevant.

Maybe at some point in the future, examples can be split off into their own repository, but let's keep that discussion for another time and place.

**Comment by MarioLiebisch** [comment]
Yep, sounds very reasonable to me.

**Comment by eXpl0it3r** [comment]
So `CMAKE_INSTALL_PREFIX` is for libraries and headers, plus two options to activate doc/example installing as well as two paths to specify where to install them, right?
Or should building the docs/examples imply installing them?

**Comment by MarioLiebisch** [comment]
Building shouldn't imply installing, e.g. you might want to keep the CHM version only, not the raw HTML files.

**Comment by binary1248** [comment]
When support for separate building comes along, nothing speaks against having to separately install the products as well. We really shouldn't try to predict what the user ultimately wants to do :wink:. If they want more things to happen, let them do more for it.

**Comment by mantognini** [comment]
Does someone feel like implementing it? :-)

**Comment by TankOs** [comment]
AFAIK the typical situation in Linux distributions is to ship the example source code only, not binaries. That code resides in /usr/share/doc/SFML/example, for example, then.

Separating the targets makes sense in my opinion.

**Comment by binary1248** [comment]
Is this still valid considering #1335 has been merged?

**Comment by Bromeon** [comment]
Is this still relevant?

**Comment by ChrisThrasher** [comment]
I believe I recently spoke with @eXpl0it3r who told me that examples are no longer installed meaning we can close this issue, right?

**Comment by eXpl0it3r** [comment]
Examples are no longer installed following the #1576 PR, as such I close this.
