### ISSUE TITLE
Error handling in SFML 3

### ISSUE THREAD

**Issue by Bromeon** [SFML/SFML#2139]
Back in 2015, I created several forum threads around the topic of error handling/reporting:
* [to promote the use of assertions](https://en.sfml-dev.org/forums/index.php?topic=19427)
* [to discuss logging with `sf::err()`](https://en.sfml-dev.org/forums/index.php?topic=19282)

Some discussions around the topic date back to 2011 and 2013:
* [why SFML didn't use exceptions](https://en.sfml-dev.org/forums/index.php?topic=5228)
* [Exceptions in SFML 3?](https://en.sfml-dev.org/forums/index.php?topic=13240)

These are quite interesting, already to understand historic context and how SFML 1 and 2 evolved to be without exceptions.

---

# Error handling in SFML 3

Now the year is 2022, a lot has changed, and at last we have the option to introduce breaking changes and redesign the API for better userfriendlyness. Handling errors is an important topic, and there are different options to tackle them in SFML 3. I'll jump right into them:

1. **Boolean return types**
   E.g. SFML 2 `sf::Image::loadFromFile()`
   * ✔️ Simple.
   * ✔️ Easy to port to bindings.
   * :x: Can be forgotten (`[[nodiscard]]` is needed on every single method).
   * ❌ Needs separate output parameters.
   * ❌ No way to transport error messages, needs `sf::err()` side channel.

2. **Optionals**
   Basically all the disadvantages of `bool` except no need for output parameters.
   * ✔️ Simple to understand and document.
   * ✔️ Easy to port to bindings.
   * :x: Can be forgotten (`[[nodiscard]]` is needed on every single method).
   * ❌ No way to transport error messages.

3. **Assertions**
   Listed for completeness, but they are not really a solution for runtime errors. But we might want to use them more often to complement other error mechanisms in the case of logic errors.
   * ✔️ Immediate breakpoint, must be fixed.
   * ✔️ No runtime overhead in release.
   * :x: Only useful for errors that are bugs (not loading files etc).
   * ❌ Do not allow the user to be lenient about certain errors.

5. **Exceptions**
   * ✔️ User cannot ignore them.
   * ✔️ Automatically propagate upward.
   * ✔️ Can be polymorphic, allowing automatic fallbacks and higher-level handling.
   * ✔️ Can theoretically transport extra data beyond message, although rarely done in practice.
   * ✔️ Can be used in constructors.
   * ❌ Hard to document and follow, especially once multiple layers/callbacks/virtual functions are involved.
   * ❌ Exception safety can be hard to achieve, and we need to enter the whole `noexcept` rabbit hole.   
   * ❌ Need verbose `try/catch` block even in situations where the user explicitly wants to ignore them.
   * ❌ Not easy to map to bindings, especially due to polymorphism.
   * ❌ Small runtime overhead (more or less depending on exception mechanism).
   
4. **Result type**
    Inspired by [`std::expected`](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p0323r10.html) proposal or Rust's [`Result` type](https://doc.rust-lang.org/std/result/index.html). 
    Basically `std::variant<T, E>` but with a highly specialized API.
   * ✔️ User cannot forget them (`[[nodiscard]]` can be declared directly on the type).
   * ✔️ User can however explicitly and concisely ignore them (e.g. with `(void)` or an `ignore()` method).
   * ✔️ Allow to transport arbitrary data as part of the error (e.g. an enum, message, context info).
   * ✔️ Function signature makes immediately obvious which methods can fail, and how they can do so -- users are not surprised by unexpected errors and cannot miss any documentation.
   * ❌ No automatic propagation (could probably be made somewhat ergonomic as a library solution).
   * ❌ Require static factory functions such as `Image::fromFile()`, no constructor support (if this is truly a disadvantage).
   * ❌ Non-polymorphic unless explicitly designed.
   * ❌ Requires either custom-built type for SFML or use of an established library.

**Comment by vittorioromeo** [comment]
Good writeup. I think that the

> ❌ Can be forgotten ([[nodiscard]] is needed on every single method).

point in (1) is a bit overstated, as adding `[[nodiscard]]` to these functions is trivial and it completely solves the problem. Similarly, I also think it is overstated in (2), as returning `std::optional` does force the user to at least manually dereference the optional or check its state, which prevents it from "being forgotten".

**Comment by Bromeon** [comment]
Definitely, some points weigh heavier than others.

> [...] adding `[[nodiscard]]` to these functions is trivial and it completely solves the problem.

Still, I don't think that fully accounts for reality. We see how often it happens that developers forget things like `explicit` for constructors, despite "trivial".

My main point however is that `[[nodiscard]]` can not only be annotated to functions, but also to classes. A class `sf::Result` could be `[[nodiscard]]` on a type level, meaning that returning this type would _always_ mean it has to be handled. This not only solves the "forgetting" issue, but makes the method signature expressive without the use of any attributes.

**Comment by Chnossos** [comment]
Do note that using exceptions, it is possible to build a backtrace to add information at each level using [`std::nested_exception`][1]. I have built such a library myself for work which provides lots of assertion styles to make the user code readable while retaining a high quality of debug information. Sample code would like this:
```cpp
#include <exception/Exception.hpp>

void level2()
{
    B_ASSERT(someFuncThatReturnsFalse(), "Error during level2()");
}

void level1() try
{
    level2()
}
catch (...)
{
    THROW_WITH_NESTED("Error during level1()");
}

int main() try
{
    level1();
    return EXIT_SUCCESS;
}
catch (const std::exception & e)
{
    std::cerr << "Fatal error:\n";
    Exception::printExceptionStack(e);
    return EXIT_FAILURE;
}
```

Which prints (in debug mode):
```
Fatal error:
 * Error during level1() [main.cpp:level1():14]
  * Error during level2() [main.cpp:level2():5]
```

It is easy to add new assertions for third-party libraries, whether they use error codes or exception themselves, and use them internally. Main disadvantage is the use of the heavy try-catch notation but that's a given when using exceptions.

On the pros side, it makes the end code really easy to write and read, as well as making errors easy to locate without needing any non-standard libraries (except for `fmt` for much-needed error string formatting). You can let the error go up without having to write any line of code, compared to error-by-return methods that need to be handled at every level to propagate it back to the right level (pseudo-code):
```cpp
#include <expected/Expected.hpp>

[[nodiscard]] Expected<int> level2()
{
    if (someFuncThatReturnsFalse())
        return 42;
    else
        return fail("Error during level2()"); // Are file name, function name and line number added?
}

[[nodiscard]] Expected<int> level1()
{
    if (auto const & [value, error] = level2(); error.empty())
        return value;
    else
    {
        // Repackage to add level info + propagate, but what about file name, func name, etc?
        return fail("Error during level1(): {}", error);
    }
}

int main()
{
    if (auto const & [value, error] = level1(); error.empty())
    {
        std::cout << value << std::endl;
        return EXIT_SUCCESS;
    }
    else
    {
        std::cerr << "Fatal error: " << error << std::endl;
        return EXIT_FAILURE;
    }
}
```

[1]: https://en.cppreference.com/w/cpp/error/nested_exception

**Comment by ChrisThrasher** [comment]
TL;DR I vote for Option 2.

---

Option 1 is the same as Option 2 given the limitations of C++03. Option 2 is the natural modernization of what we're already doing. We can transition to this pattern easily and the library won't feel much different from how errors are treated in SFML 2. We're still returning truth-y values to indicate success or failure but we do so in a more expressive and idiomatic way that allows for shorter user code and better const-ness.

Assertions seem somewhat orthogonal to me. They're mostly a developer tool to catch invariant violations. Sure, users with debug builds of SFML can benefit from them but we cannot rely on users having access to debug builds so we cannot craft APIs around this assumption.

Exceptions are my preference in the general case. They're well understood and impossible to accidentally ignore. It's worth mentioning that I seldom see anyone handle `sf::Font::loadFromFile`'s failure other than returning from `main` or throwing. If the API already threw upon failure, users would still get the behavior they seemingly want. However I understand its shortcomings and how it may do a poor job serving the last ~10% of users who do want to take action if a resource fails to initialize.

`std::expected` is maybe the ideal solution. I've used [`tl::expected`](https://tl.tartanllama.xyz/en/latest/api/expected.html) (a clone of C++23's `std::expected`) and really like it. It gives me a lot of what I like about exceptions. The implementation is ~3,000 lines long so it's not reasonable to implement this ourselves. If we are to depend on `tl::expected` then that's a discussion unto itself. In the end I think that this is just out of our reach and not worth the marginal improvement over `std::optional`.

**Comment by JonnyPtn** [comment]
Id say option 5 is best - although we can't use the STL one the arguments for it still stand and for SFML's purposes it wouldn't be too hard to implement

**Comment by eXpl0it3r** [comment]
For me `std::optional` doesn't really solve the main issue of moving the error information into the user code. [Redirecting `sf:err()`](https://www.sfml-dev.org/documentation/2.5.1/group__system.php#ga7fe7f475639e26334606b5142c29551f) is a really poor solution (see [this ugly code for spdlog](https://gist.github.com/eXpl0it3r/507b24f9f65454916415678c8eac3830)) and `std::optional` doesn't address this in anyway.  
`std::optional` is an improvement in the way it ensures non-default constructability and invalid resource states, but in my opinion it makes the API much harder to use.

----

`std::exception` on the other hand solves the issue of passing error information, but it's not available in C++17. As this will be a fundamental "type" in C++23, I don't want to polyfill this, nor use `tl::expected`. General reasons against basic type polyfills:
- It takes a lot more effort to onboard people on a new language feature, being a front-runner with a polyfill would make this even harder, as there aren't even enough teaching resources around
- It partially satisfies people with "old" compilers, as they have to learn this pattern, that seems SFML specific, but actually isn't
- It doesn't satisfy people with "latest" compilers, as they really want to use `std::expected` and not `sf::Expected`
- Implementing and maintaining a polyfill can be a project on its own

----

Exceptions seem like the obvious choice to me (in absence of `std::expected`). They can carry any kind of error information and be as granular as we want them to be. They keep the API very simple. It's a concept widely taught and easily understood. You can handle them at the layer where you want to. IDEs support them with stacktrace displaying and more.

One point that seems a bit misunderstood even in the draft PR #2237 is that exception handling has to be done in a similar fashion as you would with a return error codes or error types (i.e. ADT which means for all the non fancy C++ terms speakers Abstract Data Type). But a feature of exceptions is that you can handle exceptions separately from your implementation code. You don't have to have a try-catch block around single function calls that can throw, instead you can pick the size of the wanted scope. For example having a top-level exception handler or handling load exceptions around multiple loading statements, sharing the error handling code for all of them and more. The reasons to have a minimal scope as touched on in #2237 seem to be to have better clarity on the origin of the error on a code level, i.e. what part of my code can throw an error. To me this seems to fall in the categories of arguments like having to know a given type of a variable at all times, sure it could sometimes be useful to know, but:
- You should handle specific exceptions (e.g. not `std::exception` but `sf::LoadException`), so the scope of what *could* throw this exception is drastically reduced
- The scope can most of the time be selected in a sensible way, which sometimes fails in a short code example (practically speaking one wouldn't handle exceptions in tiny examples anyways), as such it's usually clear what function will throw
- Knowing what specific function in the try block throws is more often than not information you don't even *need* to know, instead you want to log / retry / exit that whole code block up on failure, so it doesn't matter if it was line 15 or 16

**Comment by vittorioromeo** [comment]
Firstly, see [my comments](https://github.com/SFML/SFML/pull/2237#issuecomment-1272573154) and [@Bromeon](https://github.com/SFML/SFML/pull/2237#issuecomment-1272574404)'s comments on the issue.

I strongly dislike and discourage the use of exceptions for situations where the user wants to react to an error relatively quickly rather than having it bubble up a lot, and my claim is that the vast majority of functions fit in this description.

---

If a font (or any other resource, really) fails to be loaded, you want to immediately either:

1. Log the issue and continue with a fallback resource.

2. Exit the program. 

3. Interactively ask the user for the location (e.g. the resource is being loaded from a user-provided script rather than from the game engine itself).

All of these actions are to be taken immediately. Attempting to load a font in the middle of the game loop, as part of the game logic, and handling a possible failure in -- say -- `main` is just not good design and not something I'd like to promote.

Here's an analysis of some approaches when loading a single resources and trying to provide a fallback (real use case -- I used this "fallback" approach in real projects):

```cpp
//
//
// WITHOUT ANY ERROR HANDLING MECHANISM
sf::Font font = sf::Font::loadFromFile("abcd.ttf");
sf::Text text(font, "hello"); // Possible run-time issue (!)

//
//
// EXCEPTIONS, NO ERROR HANDLING
sf::Font font = sf::Font::loadFromFile("abcd.ttf");
sf::Text text(font, "hello"); // No run-time issue -- good.
                              // But the code looks exactly the same as before!
                              // The user forgot to handle the error, because
                              // it's not obvious that there is one.
                              
//
//
// EXCEPTIONS + FALLBACK
sf::Font font = [&]
{
    try 
    {
        return sf::Font::loadFromFile("abcd.ttf");
    }
    catch (const sf::LoadException& e)
    {   
        return globalDefaultFont;
    }
}(); // Verbose, poor code, requires IIFE or default-constructible font (bad).
     // Discourages people from handling errors where they should be.
     // Encourages unnecessary bubbling-up of errors.

sf::Text text(font, "hello"); 

//
//
// OPTIONAL, NO ERROR HANDLING
sf::Font font = sf::Font::loadFromFile("abcd.ttf").value();
sf::Text text(font, "hello"); // No run-time issue -- good.
                              // The code has a clear indication that something
                              // can go wrong -- the `.value()` call above.

//
//
// OPTIONAL + FALLBACK
sf::Font font = sf::Font::loadFromFile("abcd.ttf").value_or(globalDefaultFont);
sf::Text text(font, "hello"); // No run-time issue -- good.
                              // The code has a clear indication that something
                              // can go wrong, and visibly provides a fallback.
```

---

Note that the example above is realistic for smaller games, but in larger games you usually have some sort of resource manager, or load resources on demand. Let's see a basic example of a resource manager:

```cpp
class ResourceManager
{
private:
    std::unordered_map<std::string, sf::Font> m_fonts;
    // ...other resources...

public:
    void addFont(std::string_view key, sf::Font&& font);
    sf::Font const* getFont(std::string_view key) const; 
    // ...other resources...
};
```

Now, let's imagine we load all fonts at the beginning of the application, through a `loadFonts` function. How does the choice of error handling mechanism affect the correctness and verbosity of the code? 

```cpp
//
//
// EXCEPTIONS, NO ERROR HANDLING
void loadAllFonts()
{
    for (const auto& f : std::filesystem::recursive_directory_iterator(fontFolder))
    {
        if (!f.is_file() || !f.path().has_extension("ttf")) { continue; }
        
        resourceManager.addFont(f.path().filename(), 
                                sf::Font::loadFromFile(f.path()));
            // Whoops, the author completely forgot to address the error case,
            // yet the code compiles!
            //
            // In this case, the first failure will result in all the remaining
            // fonts *NOT* being loaded. 
            //
            // Is this what the author really intended...?
    }
}

//
//
// EXCEPTIONS, LOG AND CONTINUE, EVERYTHING IN THE TRY BLOCK
void loadAllFonts()
{
    for (const auto& f : std::filesystem::recursive_directory_iterator(fontFolder))
    {
        if (!f.is_file() || !f.path().has_extension("ttf")) { continue; }

        try // First issue: what error are we trying to catch? Could be anything
            // in the block below, including something thrown by `resourceManager`
            // or by `std::filesystem`. 
        {
            resourceManager.addFont(f.path().filename(), 
                                    sf::Font::loadFromFile(f.path()));
        }
        catch(const sf::LoadException& e) // Now we clarify what error we care 
                                          // about, but we still MANUALLY need
                                          // to figure out what part of the code
                                          // above throws this error.
        {
            errorLog() << "Couldn't load font from path " << f.path() 
                       << ", skipping it...\n";
        }
    }
}

//
//
// EXCEPTIONS, LOG AND CONTINUE, ISOLATE ERROR IN THE TRY BLOCK
void loadAllFonts()
{
    for (const auto& f : std::filesystem::recursive_directory_iterator(fontFolder))
    {
        if (!f.is_file() || !f.path().has_extension("ttf")) { continue; }

        sf::Font font = [&]
        {
            try // Now it is clear what can throw. But we had to use IIFE.
            {
                return sf::Font::loadFromFile(f.path())
            }
            catch(const sf::LoadException& e) 
            {
                errorLog() << "Couldn't load font from path " << f.path() 
                           << ", skipping it...\n";
            }
        }();

        resourceManager.addFont(f.path().filename(), std::move(font));
    }
}

//
//
// OPTIONAL, LOG AND CONTINUE
void loadAllFonts()
{
    for (const auto& f : std::filesystem::recursive_directory_iterator(fontFolder))
    {
        if (!f.is_file() || !f.path().has_extension("ttf")) { continue; }

        std::optional<sf::Font> maybeFont = sf::Font::loadFromFile(f.path());
            // Clearly forces the author of the code to THINK what should be
            // done in case of error, at THIS point in time.
        
        if (!maybeFont.has_value()) // Usual control flow.
        {
            errorLog() << "Couldn't load font from path " << f.path() 
                       << ", skipping it...\n";

            continue;
        }

        resourceManager.addFont(f.path().filename(), std::move(*maybeFont));
    }
}

//
//
// THEORETICAL SFML EXPECTED, LOG AND CONTINUE, WITH SOME SUGAR
void loadAllFonts()
{
    for (const auto& f : std::filesystem::recursive_directory_iterator(fontFolder))
    {
        if (!f.is_file() || !f.path().has_extension("ttf")) { continue; }

        sf::Font::loadFromFile(f.path())
            .onSuccess([](sf::Font& font)
            {
                resourceManager.addFont(f.path().filename(), std::move(font));
            })
            .onError([](const std::string& context)
            {
                errorLog() << "Couldn't load font from path " << f.path() 
                           << ", skipping it... context: " << context << '\n';
            });
    }
}
```

My personal preference and what I'd like everyone to use is either `std::optional` or `sf::Expected`. They *force* the author of the code to at least *think* about the error locally, and always give the option to propagate it upwards as an exception *if they want to*.

**Comment by ChrisThrasher** [comment]
We're solving a problem of a similar nature to the commitee when standardizing `<chrono>` or `<random>`. Those are both powerful, complicated APIs. For the vast majority of users, they could get by with a simpler and easier API. However, in the name of being inclusive to many use cases, the committee standardized two very verbose APIs that are incredibly flexible to a myriad of use cases.

On a scale of 
```cpp
srand(time(NULL));
return rand();
```

to

```cpp
auto seed_data = std::array<int, std::mt19937::state_size>();
auto random_device = std::random_device();
std::generate_n(std::data(seed_data), std::size(seed_data), std::ref(random_device));
auto sequence = std::seed_seq(std::begin(seed_data), std::end(seed_data));
auto rng = std::mt19937(sequence);
return std::uniform_int_distribution(0, std::numeric_limits<std::uint16_t>::max())(rng);
```

where does SFML land?

(Yes, this is what it looks like if you want to *very correctly* initialize a Mersenne twister random number generator and get a single integer out of it).

Using exceptions+constructors puts us very close to the "keep simple things simple" side of the continuum while the use of factory functions and ADTs is a big step towards the complexity (and power!) of something like the `<random>` API. There is no way to quantity our position on this continuum but hopefully it provides a nice mental model for reasoning about API design.

**Comment by therocode** [comment]
I don't agree that `expected` type VS `exceptions` is a matter of complexity VS simplicity where `exceptions` is the simple one. Both can have simple APIs and both are equally powerful IMO. 

If you just wanna exit the program and you don't care about handling the error recovery, with and `expected` type you'd just do `result.unwrap()` or whatever the method would be. 

So in my mind, the "`expected` is for the minority of people who want power, flexibility and complexity, whereas `exceptions` is for people who want simple newbie-friendly APIs" is a false dichotomy. 

The difference IMO is more just a difference in style, with concrete differences in how you use things. The initial post of this thread outlines it very well 👍. Both ways can also be idiomatic, depending on what flavour of C++ you subscribe to.

**Comment by therocode** [comment]
Some thoughts on the path to whatever ends up the desired goal. 

Atm SFML is at "run `t.load` on uninitialised `T`, and return `bool`" which we all seem to agree is not ideal. Changing this to `std::optional<T> loadT();` is a modernisation of the former, but has no extra error information. I think it's also easy to make the argument that we *should* have error information but that we don't know which style of this that we want and the question seems to mostly be around `expected` vs `exceptions`.

IMO we should focus on deciding which of these we want, thinking long-term future. I don't think we should take `exceptions` over `expected` becuase `std::expected` isn't available until C++23, as that's only a couple of years away but SFML is supposedly going to try and stay relevant for the foreseeable future, so that seems rather short-sighted IMO. Even if a polyfill is not ideal, a few years with a non-ideal polyfill (or even postponing this error discussion for post-C++23) is much better than ending up picking the suboptimal error handling style and living with that for the rest of the library's lifetime (if we would end up thinking that `expected` is preferred for SFML).

Also, going "return bool" -> "use exceptions" -> "use expected" is a quite jerky road, which fundamentally changes the error handling twice. To me anyway, "return bool" -> "return optional" -> "return expected" is a cleaner road, since the pattern is the same after the initial switch, we're just adding more information. Ideally personally for me, I'd want to see "return bool" -> ("return expected polyfill") -> "return expected" since that'd mean we get useful error info from the first change, and the second change becomes trivial. I think we should not go down the route of exceptions at all, unless we decide that expections is where SFML wants to be long term, and in that case we should go "return bool" -> "use exceptions" since that is possible to implement today, and has fewest steps.

And if it wasn't clear, my personal vote is `expected` and not `exceptions` with no extra arguments, it's all outlined above - and I do consider this more or less purely a choice of style/preference with no real critical dealmakers/dealbreakers on either side.

**Comment by Bromeon** [comment]
> We're solving a problem of a similar nature to the commitee when standardizing `<chrono>` or `<random>`. Those are both powerful, complicated APIs.

To be fair, _both_ those APIs are horribly overengineered, and most other programming languages were capable to find a much more reasonable middle ground. The problem with the C++ standard library that _doing things correctly_ and _doing things in a simple way_ are often contradictory goals. Good API design on the other hand would naturally guide users towards a good solution, making "wrong" approaches harder to use. Part of this can be explained with historic compatibility, but not all. Even nowadays it's notoriously difficult to get trivial things like insertion of (key, value) into a map done without knowing the trade-offs between countless alternatives.

And regarding the other parts, therocode summarized it nicely. Once working with a more rigorous error handling model like `std::expected`, it's often easier to understand and reason about, because errors are part of the type system and not some meta-information hidden inside documentation.

The example above:
```cpp
sf::Font::loadFromFile(f.path())
    .onSuccess([](sf::Font& font)
    {
        resourceManager.addFont(f.path().filename(), std::move(font));
    })
    .onError([](const std::string& context)
    {
        errorLog() << "Couldn't load font from path " << f.path() 
                   << ", skipping it... context: " << context << '\n';
    });
```
could also be written in a more procedural way as:
```cpp
auto loaded = sf::Font::loadFromFile(f.path());
if (sf::Font* font = loaded.ok())
{
    resourceManager.addFont(f.path().filename(), std::move(*font));
}
else if (sf::Error* e = loaded.error())
{
    errorLog() << "Couldn't load font from path " << f.path() 
               << ", skipping it... context: " << e->context() << '\n';
}
```
This would allow normal control flow (`return` etc) and is pretty straightforward to understand.

**Comment by ChrisThrasher** [comment]
This conversation is dominated by `std::expected` in spite of us having no clear path to getting our hands on an implementation of it. A polyfill for `std::span` was already shot down. Have we changed our mind on polyfills? Until we know how we're going to get `std::expected` it's not particularly useful to consider it as an alternative to `std::optional` or exceptions. I think we're getting ahead ourselves.

**Comment by JonnyPtn** [comment]
I don't think `std::span` was shot down and afaik there was no decision on polyfills so no minds need to be changed?

I'd say the opposite fwiw - we first need to work out what the preferred API is then worry about how it's implemented, although of course there's a bit of overlap

**Comment by ChrisThrasher** [comment]
I think this is the biggest API change remaining to make in SFML 3. Do we have any more thoughts to share on this matter? I really hope we can come to a concensus.

**Comment by JonnyPtn** [comment]
I think which error handling to use depends on the context so there’s not really a single one that fits them all. Perhaps best to look at individual parts of the API to make decisions for them individually

**Comment by therocode** [comment]
I can only re-iterate a bit from the previous summary.  The error handling style of a library is a pretty fundamental choice and should IMO be compatible with the long-term vision of the library.

- I assume that `returning bool with out-ref` and `option<bool>` are unanimously agreed as bad/not ideal, since they do not carry any error information. This means we need to change the API, and it's not going to be towards `option<bool>`.
- Also assuming it is true like @ChrisThrasher said that there is a majority of preference towards `std::expected`, but the problem with this approach is that it's `c++23`.

In that case the options kinda boil down to:
1. Use exceptions even though `std::expected` is more popular, because `std::expected` is C++23
2. Implement a polyfill for `std::expected` for a few years and later switch over to C++23
3. Wait with updating error handling until SFML uses C++23

IMO it'd be very short sighted to do #1. 
IMO #2 makes perfect sense, it's how SFML kinda did already with `sf::Thread` and some of the `chrono` stuff and I don't see that being particularly harmful. If anyone truly is against this path, it would be good if they spoke up with concrete arguments on why.
IMO #3 could also make sense, C++23 isn't that far away, and if SFML adopted a more rapid major-release cycle that doesn't contain very very many things, taking a decade+ to finish up, it would possibly mean waiting just some ~3-5 or so years which could be okay?

A further note on `std::expected` VS exceptions. A function that returns `std::expected` can easily be used as if it had exceptions as error handling by calling `.value()` on it which throws with the contained error. So people preferring exceptions could get very similar semantics/behaviour by doing that. The opposite is not true however, as there's no good way of turning an exception-based function call into something that returns an `std::expected`. With that + what @Bromeon said with "errors are part of the type system and not some meta-information hidden inside documentation", I feel that for a library that deals with building-block style APIs, making it return-value oriented is the more building-block style API that's ultimately more flexible as it can be used to achieve either approaches.

As for reaching a consensus - this is C++ error handling, so I doubt there will ever be one 😁

**Comment by Bromeon** [comment]
> The second is perhaps not ideal but it’s still one of our best options since it’s such a simple, straightforward improvement over the status quo.

It still leaves a major issue unaddressed though: the error message is written to a global stream `sf::err()`, with all the consequences such as [thread-safety bugs](https://github.com/SFML/SFML/pull/1724). For a user it's also very hard to get to this error message.

Apart from that, I think we should anticipate future breaking changes and keep them to a minimum. If we already know _today_ that we want to use `std::expected` once C++23 lands (and is supported), I don't see any point in going with an entirely different API in the meantime and letting every user rewrite all their error handling _again_ in SFML 4.

Maybe we should also look at a closely related question -- if we had all the possibilities available today, which would be the most ergonomic API for error handling? `std::expected`? exceptions? something else?

**Comment by ChrisThrasher** [comment]
> Maybe we should also look at a closely related question -- if we had all the possibilities available today, which would be the most ergonomic API for error handling? std::expected? exceptions? something else?

When it comes to file I/O, I think `std::expected<T, std::string>` is ideal. It's _expected_ that file I/O may fail so forcing users to reckon with that in their code makes sense to me. 

I want to put it out there that we could write our own `sf::Result<T>` type which contains a T _or_ a string representing the failure message. If we don't force ourself to design for generic error types, we can make a lot of simplifying assumptions. Under the hood it would be a `std::variant<T, std::string>` with a simple `expected`-like interface. While implementing a `std::expected` polypill is quite hard, I don't think `sf::Result<T>` would be especially difficult.

**Comment by Bromeon** [comment]
The problem with a `string` as error descriptor is that you cannot dispatch on it (unless you rely on exact wording). So it's purely informational for debugging, while from a code flow perspective, `sf::Result<T>` is equivalent to `std::optional<T>`.

So the question is: are there cases in SFML where we want to not just tell the user _that_ an error happened, but allow them to _differentiate_ errors? In that case, things may become more complex, and we'd need to go for a global error enum or `Result<T, E>`.

**Comment by ChrisThrasher** [comment]
> The problem with a string as error descriptor is that you cannot dispatch on it

What APIs are prone to fail for a variety of reasons? I thought we were only dealing with functions that have 1 possible failure mode.

**Comment by ChrisThrasher** [comment]
https://github.com/ChrisThrasher/SFML/commit/b461b661f287aed0f620102af5b68ae9a27efcb3

Here's a crude implementation of `sf::Result<T>`. There's a lot we can do to make it more sophisticated and up to par with `std::expected` but we don't really need to bother with much of that. `std::string` is the simplest error type I could think of it can easily be something else instead.

**Comment by eXpl0it3r** [comment]
> What APIs are prone to fail for a variety of reasons? I thought we were only dealing with functions that have 1 possible failure mode.

Quite a few APIs in SFML have different "failure modes", just two examples:
- https://github.com/SFML/SFML/blob/master/src/SFML/Graphics/Texture.cpp#L109
- https://github.com/SFML/SFML/blob/master/src/SFML/Graphics/Shader.cpp#L436

**Comment by ChrisThrasher** [comment]
> Quite a few APIs in SFML have different "failure modes", just two examples:

Be it exceptions or any other mechanism, how would you most prefer representing those multiple failure modes?

**Comment by ChrisThrasher** [comment]
Is anyone still interested in discussing this? I'd love it if we could come to an agreement and get something merged.

**Comment by eyalk1** [comment]
From what I read it seams that there's a concenseus towards ```std::expected```. In llvm 16 there's already an implementation, and there's ```tl:: expected``` as well. So in the mean time we can have the ```tl``` header just pasted in the code, and when the other major vendors implement the library ```tl``` can be replaced with minimal breaking changes.

I think that the next question is what the ```error_type``` should be.
Personally - ```std::string``` doesn't sound like an ergonomic type for recoverable errors. What I propose is using ```std::error_condition```. It covers a string message, an error category, and the specific error code in that category. It does come with a caveat: the error codes are not portable easily, unless we make our own.

**Comment by ChrisThrasher** [comment]
https://github.com/SFML/SFML/pull/2435#pullrequestreview-1392591878

It recently came up how string decoding is yet another fallible operation that should maybe express that failure result in its function signature. Add this to the list of APIs that may get changed once we make a decision on error handling.

**Comment by Bromeon** [comment]
https://github.com/SFML/SFML/pull/2537#discussion_r1176814701: `sf::Shape::getGeometricCenter` can fail when there are no points.

**Comment by eXpl0it3r** [comment]
While I'd have loved to solve the "missing information" problem with SFML 3 and personally would've gone with an exception API, it seems that `std::expected` is gaining a lot of support overall and as such, it may make sense to not introduce an API that has no specific future.

During the last maintainer meeting, the general consensus, which I support, is to go with `std::optional` in SFML 3 and hopefully we'll be ready for `std::expected` in SFML 4. The transition from `std::optional` to `std::expected` would be a lot more straight forward then.

As said, the downside is, that SFML 3 still doesn't provide an option to retrieve the actual errors beyond redirecting the `sf::err()` buffer.

**Comment by eXpl0it3r** [comment]
Closing this, as the direction has been decided and largely implemented.

**Comment by eXpl0it3r** [comment]
To close the circle and document the final outcome for stranded readers and our future selves after trying things out and further discussions on other platforms.

After changing the loading functions to use `std::optional` the discussion shifted more towards eliminating empty states, as an optional could be used to represent such a state. This lead to the rewriting of all loading functions into factory functions, which construct a new instance, if the loading was successful, otherwise returning `nullopt`, and the removal of default constructors.

Looking back at the created API, put `std::optional` at the very center of many of the SFML APIs, which not only made the use of those APIs (arguably) more complicated, but it also required every SFML users to be rather deeply familiar with `std::optional` and its usage pattern, while also putting quite some rewriting workload onto SFML 2 users when migrating to SFML 3.

From our own assessment it became clear that "two-phased initialization" (default construction + loading) has essentially never been an issue for SFML users, meaning users have not been struggling with the current concept for the past decade and more. While we as SFML could push for and potentially help with the adoption of `std::optional`, we currently don't see the benefit in taking on this "pioneer" role, nor do we want to invest the necessary time for supporting and creating teaching material to explain the new API and `std::optional`'s role.

Meaning: Removing empty states didn't actually solve problems that SFML users were/are having, but would have made it harder for (arguably) large subset of SFML users to migration to and use SFML 3.

As an alternative approach for those trying to avoid empty states, we've opted to provide throwing-loading constructors, this way the object construction will fail, leaving no empty state, and the error has to be handle through exceptions.

And `std::optional`s aren't banned, but they are used in cases where an empty state could cause issues.
