### ISSUE TITLE
Implement images as arrays of `sf::Color`, not arrays of `uint8_t`s.

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#2202]
https://github.com/SFML/SFML/blob/3a3935d00569c5cf3dbd684ab10e54e8480df167/include/SFML/Graphics/Image.hpp#L283

Images are currently represented as arrays of `uint8_t` where the assumption is that each array has a size equal to 4 times the width times the height. This invariant leads to code which is not obvious on its face and requires comments for the reader to understand it.

What if this:

```cpp
void Image::createMaskFromColor(const Color& color, std::uint8_t alpha)
{
    // Make sure that the image is not empty
    if (!m_pixels.empty())
    {
        // Replace the alpha of the pixels that match the transparent color
        std::uint8_t* ptr = m_pixels.data();
        std::uint8_t* end = ptr + m_pixels.size();
        while (ptr < end)
        {
            if ((ptr[0] == color.r) && (ptr[1] == color.g) && (ptr[2] == color.b) && (ptr[3] == color.a))
                ptr[3] = alpha;
            ptr += 4;
        }
    }
}
```

instead looked like this?

```cpp
void Image::createMaskFromColor(const Color& color, std::uint8_t alpha)
{
    for (auto& pixel : m_pixels)
        if (pixel == color)
            pixel.a == alpha;
}
```

Better data structures do so much to allow for more expressive code that effortlessly does the correct thing without need for extra checks and pointer arithmetic. In other words, this proposal results in lots of C-style code becoming C++-style code and from past PRs I think there is consensus that we don't want to write C.

---

This change also flows out into the API. Because we have interfaces that expect a `uint8_t*`, those interfaces will be forced to change to take a `Color*`. I prefer this change because it pushes users towards better data structures as well and makes it obvious upon inspect what the API really means.

One downside that Vittorio pointed out was that if users are using SFML alongside other image APIs that expect a pointer to a `uint8_t`, this new interface could cause them issues. I have no such experience with such situations so I cannot say how common this may be. I'm inclined to think that if we already use strong SFML types in our API, this should not be an exception. One might say that the old `(float, float)` interface was more flexible and friendly to 3rd party APIs than using `Vector2f` but such downsides are speculative whereas the gains of strong types are concrete.

---

_But what about undefined behavior?_

So this is a can of worms. I've tried to do my homework and have even asked an expert on computer images here at CppCon to get more feedback on this. The crux of the problem is that OpenGL is expecting a pointer to a `uint8_t` which is why the implementation looks the way it does. The question is whether or not we can reinterpret a `vector<Color>` as a `uint8_t*` without invoking UB. I believe the answer is no it is not UB because I think the standard allows you to read anything as a sequence of bytes and I think that's all that OpenGL is doing. 

It's preferable for us to prove that this is not UB but proving a negative is tricky. What I can say is that no compiler produces incorrect behavior, no compile warns on this, clang-tidy reports no issues, and even Undefined Sanitizer (UBSan) reports nothing. What I've been told (and what I would expect given my own personal experience) is that whether or not this is UB, it's such a common request that no compiler would ever reject this code which means we are safe to depend on this. If compilers no longer let you reinterpret some `uin32_t`s as an array of `uint8_t`, the whole programming world would collapse.

Luckily we can write tests to ensure that at least on the machines we test in CI, this behaves as expected. This is what those tests look like:

```cpp
    SUBCASE("Reinterpret as std::uint8_t*")
    {
        const std::vector<sf::Color> pixels = {{10, 11, 12, 13}, {14, 15, 16, 17}, {18, 19, 20, 21}};
        const std::uint8_t*          begin  = reinterpret_cast<const std::uint8_t*>(pixels.data());
        CHECK(begin[0] == pixels[0].r);
        CHECK(begin[1] == pixels[0].g);
        CHECK(begin[2] == pixels[0].b);
        CHECK(begin[3] == pixels[0].a);

        CHECK(begin[4] == pixels[1].r);
        CHECK(begin[5] == pixels[1].g);
        CHECK(begin[6] == pixels[1].b);
        CHECK(begin[7] == pixels[1].a);

        CHECK(begin[8] == pixels[2].r);
        CHECK(begin[9] == pixels[2].g);
        CHECK(begin[10] == pixels[2].b);
        CHECK(begin[11] == pixels[2].a);
    }
```

Of course these tests in isolation are not sufficient to justify this proposal but they do help provide the evidence required to make us comfortable making such a change.

**Comment by eXpl0it3r** [comment]
SFMLBuildMaster: Build this please.

**Comment by eXpl0it3r** [comment]
I can see how it can beautify some of the internal implementations, but that's IMHO a rather low goal and ways a lot less compared to API compatibility and usefulness. Said differently, I'm more than happy to have some "uglier" code in the library, if it means that the API provided is more useful and I can better operate with the APIs used internally. I'd even go as far as to say, the reason we are a library, is to hide some of the "ugly" code.

I am aware that it can be a bit more tricky for some people to work with a collection of "pixel color components", rather than collection of "pixel colors", but on the other hand, there are so many more direct transformations you can apply to collection of components rather than colors.  
From my understanding the current API breaks the "encapsulation" principle slightly by giving direct access to the data, exactly because it allows operations on the raw data itself.  
If we change the inner representation, I personally would question the `getPixelsPtr` API completely.

Can you provide a use-case where I'd want a `std::vector<sf::Color>`?

**Comment by ChrisThrasher** [comment]
> Can you provide a use-case where it would be more useful to have an std::vector<sf::Color> rather than a std::vector<std::uint8_t> outside of SFML's internal code?

You can already use `vector<Color>` today but it requires a `reinterpret_cast` because of SFML's C-style image API. It'd be nicer if I didn't have to make that ugly cast. Luckily I know that I can use an array of colors but most users will just use a vector (or array) of `uint8_t` because SFML's API pushes them that way thus causing their code to be uglier and more bug prone.

https://github.com/ChrisThrasher/mandelbrot/blob/master/src/Mandelbrot.cpp#L58

**Comment by ChrisThrasher** [comment]
See #2203 for tests that test this behavior across all platforms in our CI pipeline.

**Comment by ChrisThrasher** [comment]
https://godbolt.org/z/M5r8d5YM1

Here's a Godbolt version of these tests to experiment with or share with others who may be able to help answer our questions.

**Comment by vittorioromeo** [comment]
I also want to remind you of the issue we talked about yesterday, converting from `char*` to `Color*`. There might be projects that get a stream of bytes from some external source, and use it to e.g. create a `sf::Image`.

**Comment by ChrisThrasher** [comment]
> I also want to remind you of the issue we talked about yesterday,

Yep I gave you credit for that in the issue body.

**Comment by MatheusBonavite** [comment]
I'm so sorry to jump in the middle of the discussion out of the blue, but I really like SFML and wanted to contribute in some way (even if it is with just a comment)!
I don't know if you have considered but maybe the std::variant store, introduced in C++17, that holds a set of alternative types could help here! For example, the first color check could be done like this:

```C
int main() {
    /* Pixels can be of type std::vector<std::variant<Color, uint8_t>> pixels*/
    const std::vector<std::variant<Color, uint8_t>> pixels = {
        Color{10, 11, 12, 13}, Color{14, 15, 16, 17}, Color{18, 19, 20, 21}
    };
    const uint8_t* begin = reinterpret_cast<const uint8_t*>(pixels.data());
    if(std::holds_alternative<Color>(pixels[0])){
        CHECK(begin[0] == std::get<Color>(pixels[0]).r);
        CHECK(begin[1] == std::get<Color>(pixels[0]).g);
        CHECK(begin[2] == std::get<Color>(pixels[0]).b);
        CHECK(begin[3] == std::get<Color>(pixels[0]).a);
    } else {
        CHECK(begin[0] == std::get<uint8_t>(pixels[0]));
        CHECK(begin[1] == std::get<uint8_t>(pixels[1]));
        CHECK(begin[2] == std::get<uint8_t>(pixels[2]));
        CHECK(begin[3] == std::get<uint8_t>(pixels[3]));
    }
    /* ...and so on for the remainder of the tests */
}
```
In the above code both 'if' and 'else' clauses will work and tests pass (using -std=C++17, which I believe is enabled in SFML). However, it was not possible to remove the reinterpret_cast. A possibility would be doing something like:
```C
void check_pixels(Color pixels){
    const Color* begin = &pixels;
    if((*begin).r == pixels.r)
        std::cout << "First Hoooray (Color)" << std::endl;
}

void check_pixels(uint8_t pixels){
    const uint8_t* begin = &pixels;
    if(*begin == pixels)
        std::cout << "Final Hoooray (uint8_t)" << std::endl;
}

int main() {
    const std::vector<std::variant<Color, uint8_t>> pixels = {
        Color{10, 11, 12, 13}, Color{14, 15, 16, 17}, Color{18, 19, 20, 21}
    };
    std::vector<std::variant<Color, uint8_t>> pixels_2;
    for(unsigned char i = 10; i < 22; ++i)
        pixels_2.push_back(i);

    
    if(std::holds_alternative<Color>(pixels[0])){
        check_pixels(std::get<Color>(pixels[0]));
    }

    if(std::holds_alternative<uint8_t>(pixels_2[0])){
        check_pixels(std::get<uint8_t>(pixels_2[0]));
    }
}
```
Taking the snippet above as an example, exposing the SFML functions to other code could be done using function overload.
Again, sorry for jumping in! These are just some ideas I've had, hope I did not waste anybody's time.

**Comment by Bromeon** [comment]
@MatheusBonavite Thanks for your input! With
```cpp
std::vector<std::variant<Color, uint8_t>>
```
the problem is that _every single_ element needs to hold a discriminant (1 byte). This would be 25% overhead just in storage, while no one would want to differentiate on a per-element basis.

You also probably meant `std::array<uint8_t, 4>` instead of `uint8_t`, since 4 bytes are equivalent to 1 `sf::Color`.

I think even an outer variant (either a vector of bytes, or a vector of colors) would complicate the API. If we really want to provide both to the user, there should probably be two separate methods.

**Comment by ChrisThrasher** [comment]
We now have UBSan in CI and the `sf::Color` tests from #2203 are still passing. A year later and I still can't find reason to believe this is UB or otherwise problematic.

**Comment by MarioLiebisch** [comment]
Somehow completely missed this thread. When discussing changes here, I think it wouldn't even hurt to add/introduce one important extra property for processing raw pixel data: `stride`.

So for in-memory representation, the image data wouldn't fill `4 * width * height` bytes, it would actually be stored over `stride * height` bytes, where stride is the length of one row/line in memory.

A classic example would be non power of two textures:

* Let's assume the image size is 40x40 pixels.
* The next bigger power of two texture size would be 64x64 pixels.
* So one row/line inside the image is `40 * 4 = 160` bytes (or 40 color values).
* However, the stride would be `64 * 4 = 256` bytes (64 color values).

So when accessing raw bytes, I'd expect to retrieve the whole data, including random/unused bytes within the stride (since I'm using a memory address, not pixel coordinates inside the image). In other words: the accessible/used memory should be `64 * 64 * 4 = 16384` bytes long.

When accessing/reading individual pixels, I'd expect to retrieve only the actual image data, i.e. `40 * 40 = 1600` color values/pixels.

As such, I think it might be the best way to really just provide both approaches in separate functions, although I'm not 100% sure about using width or stride when interpreting user provided offsets (i.e. `offset = y * width + x` vs. `offset = y * stride + x`).

**Comment by ChrisThrasher** [comment]
The team has chosen to not add this to v3 so I’m going to close this issue.
