### ISSUE TITLE
Change output-parameter--based APIs to return by value

### ISSUE THREAD

**Issue by vittorioromeo** [SFML/SFML#2227]
Similarly to what we have done for `sf::IpAddress`, I suggest doing the same to classes such as `sf::Image`. In other words, `sf::Image`'s constructor would become private, and we'd have a `sf::Image::from` static member function that returns a `std::optional<sf::Image>`.

The same would apply to `sf::Music`, `sf::SoundBuffer`, and probably others.

Thoughts?

**Comment by ChrisThrasher** [comment]
Are you talking about replacing things like `sf::Image::loadFromFile` with named constructors so we can remove those member functions? I like that idea.

**Comment by eXpl0it3r** [comment]
As a C++ oldie, it still feels unnatural to me, but I'm up for a renewed API.

But maybe we'd first have to define an error handling strategy (see #2139), as that also has heavy influence on the selected API.

**Comment by ChrisThrasher** [comment]
I see this less as changing our error handling strategy and more than we're reimplementing the existing error handling strategy better. We're still returning truth-y values from functions but now we can do that with 1 function call instead of 2. I think that's a great improvement and very much in the style of SFML code as its been for so long.

**Comment by ChrisThrasher** [comment]
https://github.com/SFML/SFML/issues/2139#issuecomment-1931676032

We have decided that we will in fact go forward with this so this issue can be closed.
