### ISSUE TITLE
VS2019 and VS2022 Support

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [SFML/SFML#2292]
## Subject of the issue

Please provide newer versions for download.

## Your environment

Visual Studio 2019 or 2022

## Steps to reproduce

Look at the [download page](https://www.sfml-dev.org/download/sfml/2.5.1/).

## Expected behavior

There should be a download for Visual Studio 2019 and Visual Studio 2022.

## Actual behavior

There are downloads for Visual Studio 2013, 2015 and 2017.

**Comment by thomasw-mitutoyo-ctl** [comment]
Okay, how about writing 

> Visual C++ 15 (2017/2019/2022) - 32-bit

on the homepage then?

**Comment by Bambo-Borris** [comment]
If you'd like to see this change feel free to open a PR on the repository for the website (I believe it's under the same organisation). 2.5.1 is a very old release and the website is definitely in need of some TLC for newbies, but there's a lot of focus on 2.6.x and 3.0.0. Personally I think shipping prebuilt binaries is the wrong way to do this, we should make people build from source since I've lost count of the number of struggling mingw or msvc users downloading the wrong version.

**Comment by DreamHollow** [comment]
If you're not using CMake I could see how this might be a bit difficult.
If you decide to use CMake to build the libraries, it should be as simple as this:
Go to Tools > Command Line > Developer Command Prompt
Type in `cmake -S . -B build`

It should generate relevant files from there.

I don't really recommend other methods for building the SFML libraries. It's really much easier to use CMake.

That's why there isn't a download for VS 19 and VS 22, you're better off building the libraries from the source (for now.)

**Comment by DreamHollow** [comment]
> If you'd like to see this change feel free to open a PR on the repository for the website (I believe it's under the same organisation). 2.5.1 is a very old release and the website is definitely in need of some TLC for newbies, but there's a lot of focus on 2.6.x and 3.0.0. Personally I think shipping prebuilt binaries is the wrong way to do this, we should make people build from source since I've lost count of the number of struggling mingw or msvc users downloading the wrong version.

I'm seconding this.

I didn't have much trouble installing the CMake version of SFML to Linux, but I had a bit more difficult installing SFML to Windows and such. I'm hopeful when the new documentation releases, it will help clear up a lot of the confusion.

**Comment by eXpl0it3r** [comment]
In the meantime someone contributed an updated text for the download page, so hopefully this will reduce some of the confusion. SFML 2.6 is on the horizon, so I don't want to invest any time creating new binaries for SFML 2.5.1.

https://github.com/SFML/SFML-Website/pull/157
