### ISSUE TITLE
Replace Doctest with Catch2 v3

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#2353]
## Subject of the issue

SFML originally used Catch2 v2 but we switched to Doctest because Doctest had much better compile times. This was fair because Catch2 v2 was still a header-only library and its compile times were long enough to disrupt the flow of development. Since then Catch2 has released a new major version which fixes those compile time concerns by moving much of the implementation of the library into .cpp files that allow for better parallelization and shorter incremental build times.

Since the compile time concerns are no more, I think both libraries are relatively equal footing and we can reevaluate whether we want to keep using Doctest in the long run. Here's why I think we should switch back to Catch2:

1. The two libraries still have very similar interfaces so the work required to do this is minimum. I've done test implementations of this in the past and it was not particularly difficult. It's maybe 30 minutes of work.
2. Catch2 [generators](https://github.com/catchorg/Catch2/blob/devel/docs/generators.md) will let us more succinctly create large blocks of data that let us cover a wide range of inputs without a huge number of lines of code. [Here's](https://github.com/SFML/SFML/blob/cdce9f7147e01b0ef675cc5f115666bf09feeaec/test/Graphics/Transform.test.cpp#L70-L76) an example of where we might use them.
3. Catch2 [`STATIC_REQUIRE`](https://github.com/catchorg/Catch2/blob/devel/docs/other-macros.md) lets us better write tests for `constexpr` code. I find this more expressive than `static_assert`s and it should provide better feedback when failures occur too.
4. Catch2 [matcher expressions](https://github.com/catchorg/Catch2/blob/devel/docs/matchers.md#top) give us a powerful way to express test failure that includes things like regex matches and unit of least precision matching of floating point numbers.
5. Catch2 has built-in support for printing containers and `chrono` types which reduces how many custom printers we need to write and maintain.
6. Catch2's `SKIP` macro gives us another useful option for skipping tests that are not possible if certain hardware is not present. It's particularly useful for checking `sf::VertexBuffer::isAvailable` before attempting to run any tests.
7. Catch2 is generally a more feature-filled library than Doctest. I'm optimistic that we'll find more features that we can take advantage of in helpful ways.

It's also worth mentioning that I do personally prefer Catch2 and use it in many personal and professional projects so it's something Im more familiar with and that familiarity will help me get the most out of it. Conversely I don't use Doctest outside of SFML so I have no extra expertise to lend if we stick to it.

**Comment by eXpl0it3r** [comment]
A ping for @vittorioromeo who advocated strongly for Doctest

**Comment by ChrisThrasher** [comment]
> A ping for @vittorioromeo who advocated strongly for Doctest

https://github.com/SFML/SFML/pull/1921

Improved compile time was the only technical argument Vittorio provided so the fact that Catch2 v3 drastically improves the comple time situation should assuage his concerns somewhat.

**Comment by ChrisThrasher** [comment]
@Bromeon Curious if you have any thoughts on this

**Comment by ChrisThrasher** [comment]
https://github.com/ChrisThrasher/SFML/commit/3646e92651e0ba3d43f29bf71c5f97c3b7e8efb0

The transition is pretty straightforward.

Here's how long it took to build all 5 modules plus the tests:
```
real    0m17.038s
user    1m45.449s
sys     0m13.329s
```

And for `master`:
```
real    0m12.307s
user    1m11.657s
sys     0m9.383s
```

The difference in incremental build times is too small to reliably measure so this only affects CI and initial developer builds.

**Comment by ChrisThrasher** [comment]
https://github.com/ChrisThrasher/SFML/commit/ebcd4160d6c902c1b75a5e385cf73831d65e2b12

With access to `STATIC_CHECK` we can more easily test `constexpr` support and type traits. We still get the compiletime checking we want but we can optionally test them at runtime if we want via the `CATCH_CONFIG_RUNTIME_STATIC_REQUIRE` definition.

**Comment by JWStaiert** [comment]
Is Catch thread-safe? As someone interested in extending SFML to support Metal rendering on Mac and iOS platforms, off main-thread command encoding is a feature I’d like to test reliably at the unit level, which requires thread safe tests, as does concurrent test execution. Also, I’m fairly certain I can integrate doctest with Xcode unit testing UI (test discovery, single click jump to failures, single test level execution/disable). It’s not obvious to me if the same is true for Catch.

**Comment by ChrisThrasher** [comment]
> Is Catch thread-safe?

[It is not](https://github.com/catchorg/Catch2/blob/devel/docs/limitations.md#thread-safe-assertions). Apparently [parts of Doctest are thread-safe](https://github.com/doctest/doctest/blob/master/doc/markdown/faq.md#is-doctest-thread-aware) which I wasn't aware of.

> It’s not obvious to me if the same is true for Catch.

I believe Catch does all those things too. Go check out [this branch](https://github.com/ChrisThrasher/SFML/tree/catch2) to test that out yourself.

**Comment by vittorioromeo** [comment]
> 1. The two libraries still have very similar interfaces so the work required to do this is minimum. I've done test implementations of this in the past and it was not particularly difficult. It's maybe 30 minutes of work.

It's still work being done on a part of SFML that works perfectly fine and compiles fast, it would be more valuable to direct that work and even community effort/discussions towards user-facing issues and features.

---

> 2. Catch2 [generators](https://github.com/catchorg/Catch2/blob/devel/docs/generators.md) will let us more succinctly create large blocks of data that let us cover a wide range of inputs without a huge number of lines of code. [Here's](https://github.com/SFML/SFML/blob/cdce9f7147e01b0ef675cc5f115666bf09feeaec/test/Graphics/Transform.test.cpp#L70-L76) an example of where we might use them.

This is cool, but ultimately just makes our life a bit easier when writing test cases. Using nested range-based for loops works just as well, and I suspect that the complexity behind generators will not only slow compilation times but also might cause issues that are harder to debug. I've checked the source code and generators here are not general-purpose, they are deeply tied to the `REQUIRE` and `CHECK` macros and will only be useful inside of them. 

If we try to do something slightly out of the ordinary with generators, it will likely not work.

---

> 3. Catch2 [`STATIC_REQUIRE`](https://github.com/catchorg/Catch2/blob/devel/docs/other-macros.md) lets us better write tests for `constexpr` code. I find this more expressive than `static_assert`s and it should provide better feedback when failures occur too.

I don't see the problem with `static_assert`'s expressiveness or effectiveness. Can you elaborate on that?

Nevertheless, it's trivial to define a `STATIC_REQUIRE` macro in our test utilities `.hpp` without having to change the entire testing framework in its entirety -- it's basically a one-liner:
https://github.com/catchorg/Catch2/blob/1f881ab4641b866304b818a063164dae976dba5f/src/catch2/catch_test_macros.hpp#L154-L164

Still, I don't really see the point.

---

> 4. Catch2 [matcher expressions](https://github.com/catchorg/Catch2/blob/devel/docs/matchers.md#top) give us a powerful way to express test failure that includes things like regex matches and unit of least precision matching of floating point numbers.

Again, it's cool and could make our lives a bit easier when writing test drivers, but ultimately not impactful and not worth adding 15s-45s to the build job (source: https://github.com/SFML/SFML/pull/2452#issuecomment-1471069054).

---

> 5. Catch2 has built-in support for printing containers and `chrono` types which reduces how many custom printers we need to write and maintain.

Ditto, writing and "maintaining" these custom printers is in my opinion not a big deal and worth the compilation speed savings.

---

> 6. Catch2's `SKIP` macro gives us another useful option for skipping tests that are not possible if certain hardware is not present. It's particularly useful for checking `sf::VertexBuffer::isAvailable` before attempting to run any tests.

There is a `doctest::skip` decorator, why isn't that suitable? Even if it isn't, how about just defining the macro ourselves?

```cpp
#define SKIP_TEST_IF(condition) do { \
    if (condition) { \
        DOCTEST_INFO("Skipping test due to '", #condition, "' being true.\n"); \
        return;
    } \
} while(false)
```

---

> 7. Catch2 is generally a more feature-filled library than Doctest. I'm optimistic that we'll find more features that we can take advantage of in helpful ways.
> 
> It's also worth mentioning that I do personally prefer Catch2 and use it in many personal and professional projects so it's something Im more familiar with and that familiarity will help me get the most out of it. Conversely I don't use Doctest outside of SFML so I have no extra expertise to lend if we stick to it.

This is mostly a subjective point, I feel the opposite way. I'd rather have a simpler but faster-to-compile library, and I'm used more to doctest compared to Catch. If we really value a specific feature that Catch implements, I'd rather implement that specific feature in our test utility header instead of changing the entire framework.
