### ISSUE TITLE
Generate Export.hpp headers with CMake

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#2368]
## Subject of the issue

There is no need to write and maintain the 5 different Export.hpp headers when CMake can already generate them for us thanks to the built-in GenerateExportHeader module. I've had this implemented for a while. Check it out here:

https://github.com/SFML/SFML/compare/master...ChrisThrasher:SFML:generate_export_headers

The one downside I've heard of this is that it makes it harder on those who may be building SFML via some custom build system that isn't our own CMake scripts. I frankly don't think that's a worthwhile concern and shouldn't cause us to intentionally avoid improvements and simplifications. If someone wants to build SFML via an alternative method, they have always and will always be on their own in that endeavor.

**Comment by eXpl0it3r** [comment]
Copying my comment, from [the previous](https://github.com/SFML/SFML/pull/2177#issuecomment-1304862598) discussion on this topic:

I'm starting to lean (again?) more towards not generating source files with CMake.  
The benefits are not grand and I don't really want to explain to people, who want to use something else, that they'll have to manually write a config file, or copy an old one from before this PR, or still ***have to*** use CMake. I know this isn't a use case we're actively supporting, but at the same time we also don't have to actively make things harder/more complicated.

Maybe an image of how I view things currently:

![2022-11-06 - Source Dependency Graph](https://user-images.githubusercontent.com/920861/200188156-5dec8a9d-e8b8-4a98-925c-e1c9b7810716.png)

What we're now doing is going back in the basic Input / Process / Output chain and feed new things into the processing. This might be required in some cases, but here it's more of a "why not do it if we can" rather than "this is the only way to get big trade-off X" (simplified statements).

![2022-11-06 - Source Dependency Graph - Wrong Direction](https://user-images.githubusercontent.com/920861/200188141-a48e1c6c-6402-485b-9c53-e1f863b57f45.png)

The reasons that triggered me to post this here is that people are already trying to build SFML with other build systems, most recent examples: 
- Someone trying to use Bazel to build SFML: https://en.sfml-dev.org/forums/index.php?topic=27452.0
- Someone trying to use Premake to build SFML: https://discord.com/channels/175298431294636032/175298431294636032/1036795410771087433

**Comment by ChrisThrasher** [comment]
I'm not keen on those small number of users holding the build system hostage.

**Comment by eliasdaler** [comment]
I feel like this header can be both generated (as a custom target used by devs/CI) *and* committed. 
I agree that forcing people to use some build system to get the library/scripts into "compilable" state is not good. 

You already have this with things like glew… you can’t just clone the repo and include it into your build easily. 

Committing the generated header has the advantage of giving people choices to do what they want. But writing it by hand might be error-prone and not as portable as CMake generates. However, there’s also a problem that the output can change from version to version and it’ll be hard to tell which header will be considered "canonical".

**Comment by ChrisThrasher** [comment]
> I agree that forcing people to use some build system to get the library/scripts into "compilable" state is not good.

With how complex SFML is, good luck building anything without using our CMake scripts. I think it's unreasonable to assume any meaningful number of users are hand-rolling their own build system.

If we don't want to use CMake's built-in solution to this problem, the second best solution is the status quo. It's messy to try to commit generated code. Some local experiments show that my generated export headers contain no DLL information and change based on the value of `BUILD_SHARED_LIBS` so it's not possible to commit this generated code without it changing on everyone else's machine.

**Comment by ChrisThrasher** [comment]
I just realized something about how the generated export header works. Here is a copy of what CMake generates for me on macOS first with static libs then with shared.

`BUILD_SHARED_LIBS=OFF`
```cpp
#ifndef SFML_AUDIO_EXPORT_HPP
#define SFML_AUDIO_EXPORT_HPP

#ifdef SFML_STATIC
#  define SFML_AUDIO_API
#  define SFML_AUDIO_NO_EXPORT
#else
#  ifndef SFML_AUDIO_API
#    ifdef SFML_AUDIO_EXPORTS
        /* We are building this library */
#      define SFML_AUDIO_API 
#    else
        /* We are using this library */
#      define SFML_AUDIO_API 
#    endif
#  endif

#  ifndef SFML_AUDIO_NO_EXPORT
#    define SFML_AUDIO_NO_EXPORT 
#  endif
#endif

#ifndef SFML_AUDIO_DEPRECATED
#  define SFML_AUDIO_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef SFML_AUDIO_DEPRECATED_EXPORT
#  define SFML_AUDIO_DEPRECATED_EXPORT SFML_AUDIO_API SFML_AUDIO_DEPRECATED
#endif

#ifndef SFML_AUDIO_DEPRECATED_NO_EXPORT
#  define SFML_AUDIO_DEPRECATED_NO_EXPORT SFML_AUDIO_NO_EXPORT SFML_AUDIO_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef SFML_AUDIO_NO_DEPRECATED
#    define SFML_AUDIO_NO_DEPRECATED
#  endif
#endif
#include <SFML/Config.hpp>
#endif /* SFML_AUDIO_EXPORT_HPP */
```

`BUILD_SHARED_LIBS=ON`
```cpp
#ifndef SFML_AUDIO_EXPORT_HPP
#define SFML_AUDIO_EXPORT_HPP

#ifdef SFML_STATIC
#  define SFML_AUDIO_API
#  define SFML_AUDIO_NO_EXPORT
#else
#  ifndef SFML_AUDIO_API
#    ifdef SFML_AUDIO_EXPORTS
        /* We are building this library */
#      define SFML_AUDIO_API __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define SFML_AUDIO_API __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef SFML_AUDIO_NO_EXPORT
#    define SFML_AUDIO_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef SFML_AUDIO_DEPRECATED
#  define SFML_AUDIO_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef SFML_AUDIO_DEPRECATED_EXPORT
#  define SFML_AUDIO_DEPRECATED_EXPORT SFML_AUDIO_API SFML_AUDIO_DEPRECATED
#endif

#ifndef SFML_AUDIO_DEPRECATED_NO_EXPORT
#  define SFML_AUDIO_DEPRECATED_NO_EXPORT SFML_AUDIO_NO_EXPORT SFML_AUDIO_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef SFML_AUDIO_NO_DEPRECATED
#    define SFML_AUDIO_NO_DEPRECATED
#  endif
#endif
#include <SFML/Config.hpp>
#endif /* SFML_AUDIO_EXPORT_HPP */
```

This works perfectly fine since CMake knows what the correct contents for this file are depending on whether you're installing static or shared libraries. However, this means breaks our non-standard decision to support co-locating shared and static installs of SFML, something which CMake does not assume users will do. If you want both shared and static installed together, which version of this header do you want? You can't have both so only one or the other gets installed which might mean using the other library type no longer works. It just depends on which library type you install first and second.

I personally don't think this is a problem since SFML should not be going out of its way to allow for doing something like installing shared and static libraries in the same directory, but I know that I've lost that argument.

**Comment by JonnyPtn** [comment]
Personally don’t think the negligible benefit is worth the cost. The file almost never changes and it would break a bunch of things

**Comment by ChrisThrasher** [comment]
Exploiter has made is clear he doesn't want this so I'll close this issue. I hope we can reconsider in the future since this is the idiomatic way of dealing with shared library symbol visibility.
