### ISSUE TITLE
Consider using `std::shared_ptr` to improve object lifetime safety

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#2385]
## Subject of the issue

https://github.com/SFML/SFML/pull/2332 was a great step towards ensuring lifetime safety but it still feels lacking. I'm coming around to the idea that maybe the API ought to require a `std::shared_ptr` to the resource in question. If `sf::Text` actually owned the font it uses lifetime issues would vanish.

Pros:
 * No lifetime issues 🥳 
 * No need to delete the r-value overload of the same function which means less code to maintain
 * Less time spent consulting users online who are experiencing issues thus freeing up more time for other more important work

Cons:
 * Prohibits stack allocating certain resources (although many users are probably already head allocating such things for other reasons)
 * It adds an ugly asymmetry between types loaded from disk which are prone to cause lifetime issues (thus get put into a `shared_ptr`) versus those which aren't prone to cause lifetime issues like `sf::Music` which don't. This might make it harder to craft composable APIs where return types and parameter types are identical and complicates our error handling proposals. We're not going to return an `optional<shared_ptr<T>>` but also it's weird that some types are loaded into an `optional<T>` but others loaded into a `shared_ptr<T>`.
 * Ref counts are not free (I'm not actually concerned about this but it's worth mentioning as it's technically a runtime cost)
 * Makes it harder to reason about lifetimes. This is a classic `shared_ptr` issue. If you care about unloading resources to save memory, good luck doing that. However it's not as if the status quo makes it much easier because while you can more easily reason about when a type's lifetime ends, you'll still struggle to know how many types still refer to that destroyed type and the corresponding UB that entails.
 * It's just a bit gross. Even though it has real technical merit, it's annoying to work with and looks bad in general.

I haven't yet convinced myself I prefer this but I think it's worth opening an issue to hear what others have to think about this and flesh out the pros/cons list with anything I may have missed. Maybe the best solution is something more radically different so I'd love to hear what others think.

---

Here's what it would look like. No real surprises here. Internally to `sf::Text` we'd replace that raw pointer with a shared pointer to const.

```cpp
    ////////////////////////////////////////////////////////////
    /// \brief Construct the text from a string, font and size
    ///
    /// Note that if the used font is a bitmap font, it is not
    /// scalable, thus not all requested sizes will be available
    /// to use. This needs to be taken into consideration when
    /// setting the character size. If you need to display text
    /// of a certain size, make sure the corresponding bitmap
    /// font that supports that size is used.
    ///
    /// \param string         Text assigned to the string
    /// \param font           Font used to draw the string
    /// \param characterSize  Base size of characters, in pixels
    ///
    ////////////////////////////////////////////////////////////
    Text(const String& string, const std::shared_ptr<const Font>& font, unsigned int characterSize = 30);
```

---

I ought to mention that a totally different solution is to provide some type of resource manager class that safely holds resources like fonts and sound buffers and can return pointers/references to them to be safely used with classes like `sf::Text` and `sf::Sound`. That would greatly eliminate the need to make the `sf::Text` interface safer (and potentially uglier). It would let advanced users continue to do exactly what they want without overhead but give more casual users a safe, convenient option that also avoids lifetime issues.

**Comment by ChrisThrasher** [comment]
@Bromeon @eXpl0it3r @vittorioromeo I'd love to hear your input, particular how this would work alongside our error handling proposals.

**Comment by Bromeon** [comment]
> I ought to mention that a totally different solution is to provide some type of resource manager class that safely holds resources like fonts and sound buffers and can return pointers/references to them to be safely used with classes like `sf::Text` and `sf::Sound`.

Many years ago I implemented this in Thor, as [`thor::ResourceHolder`](https://bromeon.ch/libraries/thor/documentation/v2.1/classthor_1_1_resource_holder.html). You had two ownership strategies: 
* `CentralOwner`: the resource holder owns the resource, everyone around just keeps references. Works well for architectures that can guarantee that the resource holder outlives everything else.
* `RefCounted`: all resources are maintained via `shared_ptr` as discussed here.

---


> I haven't yet convinced myself I prefer this but I think it's worth opening an issue to hear what others have to think about this and flesh out the pros/cons list with anything I may have missed. Maybe the best solution is something more radically different so I'd love to hear what others think.

Slightly off-topic, but as someone who is working in Rust a lot, this looks like _the_ stereotypical use case for [lifetimes](https://doc.rust-lang.org/rust-by-example/scope/lifetime.html) -- a way to statically ensure that certain objects outlive others. In fact, this is exactly what the [Rust SFML binding](https://docs.rs/sfml/latest/sfml/graphics/struct.Text.html#method.new) is doing:
```rs
impl<'s> Text<'s> {
    pub fn new(
        string: S,
        font: &'s Font,
        character_size: u32
    ) -> Text<'s>
}
```
The `'s` is a _lifetime_, a generic parameter of the `Text` class. You see that the font parameter has type `&'s Font`, which is a reference bound to lifetime `'s`. The returned `Text<'s>` also carries that lifetime, meaning the font cannot be destroyed as long as a `Text` referencing it is alive.

From this perspective, `shared_ptr` looks a bit like a workaround, but it's what we have with C++. For it to be somewhat ergonomic, all the APIs would need to accept and return `shared_ptr`:
```rs
std::shared_ptr<Image> Image::loadFromFile(const string& file);
// nullptr on error? or explicitly wrapped in optional?
```

---

One issue with `shared_ptr` is that it can be null, so SFML would either need to make sure it never hands out null pointers, or constantly check them. You also have certain overhead due to thread-safety and dynamic deleters, but that shouldn't matter much in the case of heavyweight resources.

The main drawback I see is that it makes certain usage patterns more difficult. Let's say I have a pool of 5k sprites, pointing to a handful of textures. If I'm done with the scene (e.g. switch to main menu), I can just destroy all sprites (fast) and unload the texture. I can even do it in opposite order if I'm not rendering anymore. Now with `std::shared_ptr`, this would come with 5k atomic integers decrementing the ref-count in a synchronized way, and indirect function calls for each deletion. It's an admittedly rare usage pattern however, and we'd need to measure performance.

---

One option is also to use `std::weak_ptr` to counter the "texts keep font alive longer than necessary" issue -- it would mean that the user is still responsible of storing the `sf::Font` explicitly, like now, but safer.

Another approach, going in a similar direction, is that `sf::Font` itself would track all `sf::Text`s referencing it, and notify them about its destruction. Somewhat similar to intrusive pointers, this would come with quite some book-keeping, but would be quite effective at preventing UB while being _mostly_ transparent to the user. This could even be implemented as a debug-only mechanism to detect bugs.

**Comment by xparq** [comment]
From a less technical perspective (and somewhat orthogonally to the excellent insights), as a frugalist, I'd prefer if the heritage of "Simple, Fast" would ultimately drive this tough decision.

So, if an application is complex enough, it could _add_ a resorce manager. If it's so complex that even that won't help, maybe it's time to use a different lib.

**Comment by eXpl0it3r** [comment]
Lifetime management is one of C++ main pillar, whether it wants to or not. I believe SFML would take a wrong turn by slapping `share_ptr` onto any potential lifetime issue and call it a day - not our problem anymore.

For one, we do have a lot of new beginners, who often struggle the most with this, but that's not (just) because of SFML's design, but also because they're only slowly starting to understand scopes and lifetime in C++ itself. IMHO we would do them a disservice by circumventing the "problem" (and thus reduce support requests), by using a `shared_ptr`. Not only would they learn less (or nothing) about scopes and lifetime, but we also teach them, that using a `shared_ptr` will solve all their lifetime issues.

It's a bit like, if we would have designed the API with pointers everywhere previously and encouraged everyone to call `new X()` as much as possible - "you'll never have lifetime issues". Except now, we could finally get rid of those pesky memory leak issues with `shared_ptr`. 😉 

I don't have C++ project experience, so I can't really draw on that, but having work with SFGUI a bit, which uses `shared_ptr` everywhere, it can lead to some "fun" issues, where your widgets will keep existing, even if you had the widget handle (i.e. `shared_ptr`) get out of scope. That's just one anecdote, from what I hear from others, `shared_ptr` can cause quite a bit of pain. Thus, will it really reduce the amount of issues people have, or will it just shift the issues?

As for semantics, I don't think we have SFML classes as (shared) owner of resources. Yet, it's hard to express in C++ that a passed in reference, doesn't mean a "cheap object passing on interface", but really means "I'm continuously referencing this resource". Maybe, if we disallow default constructions of the resource-using class (e.g. `sf::Text`), it's a communicated slightly better, as one might realize that this other resource class is required for the resource-using class.

> One option is also to use `std::weak_ptr` to counter the "texts keep font alive longer than necessary" issue -- it would mean that the user is still responsible of storing the `sf::Font` explicitly, like now, but safer.

But then you'd still constrain the usage of the classes to `shared_ptr`, given that `weak_ptr` only accept `shared_ptr`, no?

> Another approach, going in a similar direction, is that `sf::Font` itself would track all `sf::Text`s referencing it, and notify them about its destruction.

Wouldn't that heavily couple the resource and resource-using classes? Wouldn't it at that point make more sense if the resource class became the owner of the resource-using classes and hands out instances as needed?

It sounds like an interesting approach, but also one that's probably rather complex, with many potential new failure modes...

---

If anyone has suggestions on how to more clearly communicate that a resource in use, needs to outlive a resource-using class,  would be interesting to hear. The emphasis is on communicate and not necessarily on enforcement/workaround.

**Comment by danieljpetersen** [comment]
I just want to shout my opinion into the ether here -- Please do not add shared_ptr's to the API. There is usually a clear chain of ownership for these resources, I'd go so far as to say that if you are having lifetime issues with something like sf::Font then there is something very wrong with your architecture. It may make things easier for new people, but I am not even convinced of that as I've seen new people come to the discord and ask questions regarding the syntax / semantics of shared_ptr. It'd increase surface complexity of the API while decreasing performance.

**Comment by ChrisThrasher** [comment]
A similar but less visually displeasing solution is to reimplement `sf::Texture` in terms of `std::shared_ptr`. This entails moving most of `sf::Texture`'s code into some private implementation class then changing `sf::Texture` to basically just a wrapper around a shared pointer that uses `make_shared` to construct it. This has similar runtime costs as the original proposal in this issue but it means we don't require users to write ugly code like `auto texture = std::make_shared<Texture>();`.

**Comment by MarioLiebisch** [comment]
Actually most code could probably stay as is and within `sf::Texture` (which would itself inherit from `std::shared_ptr<TextureData>`). Just instead of accessing local properties, these would be taken from the actual shared object. From my understanding this would reduce extra overhead significantly. SFML objects relying on passed resources (e.g. `sf::Sprite` using a `sf::Texture`) could then silently copy said reference.

**Comment by ChrisThrasher** [comment]
https://github.com/SFML/SFML/issues/2507#issuecomment-1501208439

I just learned that `sf::Sound` (which contains a pointer to `sf::SoundBuffer`) solves this lifetime problem by registering the sound within the sound buffer such that the sound buffer can nullify `sf::Sound::m_buffer` when the sound buffer's lifetime ends. This is an interesting solution and it also differs from the ownership model of `sf::Text` and `sf::Sprite` which don't do anything quite this sophisticated.

Do we want to replicate this model with pairs of types like `sf::Text` and `sf::Font`? Would we rather simplify `sf::SoundBuffer` to remove this sophistication for the sake of consistency?

**Comment by MarioLiebisch** [comment]
I'm not a big fan of the `sf::Sound` approach, mostly because it completely hides lifetime issues. Sounds will just stop or not play audible at all without ever telling users.

**Comment by ChrisThrasher** [comment]
I'm leaning towards removing that complexity from `sf::Sound` for the sake of simplicity and consistency with `sf::Text` and `sf::Sprite`. The code works and seldom gets touched so it's hard to claim it's a maintenance burden but there's an argument to be made that the overhead of all this extra bookkeeping is a cost that we ought not impose on users.

**Comment by Bromeon** [comment]
Yep, that's what I suggested here:

> Another approach, going in a similar direction, is that `sf::Font` itself would track all `sf::Text`s referencing it, and notify them about its destruction. Somewhat similar to intrusive pointers, this would come with quite some book-keeping, but would be quite effective at preventing UB while being _mostly_ transparent to the user. This could even be implemented as a debug-only mechanism to detect bugs.

I'm a big fan of preventing UB, even if it comes at a small runtime cost. If it's too expensive, an option is to have it disabled when `NDEBUG` is defined, so it would still help to detect bugs during development (similar to checked iterators).

That said, some things need to be considered:
* Move is now an extra register (moved-from is only unregistered in destructor)
* There can be a swap that wouldn't need to touch the resource pointers
* Sprites, Texts etc cannot be safely used on other threads (I don't think we supported that previously)
* We would need to use a data structure that allows fast insert/remove (e.g. `std::unorderered_set`)

**Comment by Bromeon** [comment]
> but there's an argument to be made that the overhead of all this extra bookkeeping is a cost that we ought not impose on users.

This may likely not matter compared to the "heavyness" of other sound-related operations, such as running an extra thread just to keep playing them. This being a performance problem has not been brought up during all the years it was implemented; while at the same time we had lots of bugs in user code regarding destroyed resources (famous "white square problem"). As such, I'd err on the side of user-friendlyness over performance, especially as long as we don't have evidence that we can't afford the latter.

**Comment by ChrisThrasher** [comment]
> As such, I'd err on the side of user-friendlyness over performance, especially as long as we don't have evidence that we can't afford the latter.

Do you think we should replicate this pattern elsewhere?

**Comment by eyalk1** [comment]
> A similar but less visually displeasing solution is to reimplement `sf::Texture` in terms of `std::shared_ptr`. This entails moving most of `sf::Texture`'s code into a private implementation class then changing `sf::Texture` to be little more than a wrapper around a shared pointer. This has similar runtime costs as the original proposal in this issue but it means we don't require users to write ugly code like `auto texture = std::make_shared<Texture>();`. Users can continue to write `Texture texture;` and the API will still only show `const Texture&` and the like.
--- 
> Many years ago I implemented this in Thor, as [`thor::ResourceHolder`](https://bromeon.ch/libraries/thor/documentation/v2.1/classthor_1_1_resource_holder.html). You had two ownership strategies:
> 
> * `CentralOwner`: the resource holder owns the resource, everyone around just keeps references. Works well for architectures that can guarantee that the resource holder outlives everything else.
> * `RefCounted`: all resources are maintained via `shared_ptr` as discussed here.

Maybe consider using a resource holder under the hood, instead of a shared_ptr?

**Comment by ChrisThrasher** [comment]
https://github.com/SFML/SFML/compare/master...lifetimes

I had another idea for managing lifetimes. First of all, the above branch does not remove the existing APIs for assigning a font to a text nor changes the semantics of those APIs. `sf::Text::setFont` behaves the same as it always has. Those using it will never notice anything changed. However there are new APIs that accept a `std::shared_ptr<const Font>`. When you use the shared_ptr API what happens is that it stores that `shared_ptr` inside the class and does what you'd expect which is ensure the font stays alive for the entire lifetime of the text.

The way this works is that when you use the conventional APIs that use a `const Font&`, the deleter for the shared pointer is set to a deleter which does nothing. However when you use the `shared_ptr<const Font>` APIs the default deleter is used which will free the pointer.

This dual-API approach lets users pick whether they want to manage lifetimes by hand (and thus are able to stack allocate their resources) or use shared pointers and let the machinery of shared pointers handle lifetimes automatically. I think this solution strikes a great balance and is one of my favorite options so far. As the implementation proves, this isn't even particularly complicated. I wrote the interface with docs and tests in about 10 minutes. I can easily do the same for `sf::Sprite` and `sf::Sound` if we so choose.

**Comment by dkosmari** [comment]
I like the `lifetimes` branch. Keeping both versions seems like the best compromise.
My suggestions:
- For every relevant type `Foo`, make a **public** type alias `FooPtr`for `std::shared_ptr<Foo>`, or perhaps `Foo::Ptr`. The user will need to hold that in a variable or container, so why not make it more convenient to type?
- Store a `std::weak_ptr` instead of a `std::shared_ptr`. This will avoid extending the lifetime of the object. User code will not be destroying the object between `getFooPtr()` and the usage of said pointer anyway.
  - If you choose to do so, the `setFoo()` methods should take a `std::weak_ptr` argument instead, signaling that a non-owning reference is being stored.

**Comment by ChrisThrasher** [comment]
I rebased my `lifetimes` branch on `master` and made some further simplifications.

**Comment by vittorioromeo** [comment]
Just wanted to share my thoughts on this idea, but unless someone really brings up some more compelling technical arguments, this is pretty much an "over my dead body" rejection from me.

As stated by several people, plainly replacing current APIs that take (using fonts as an example, but applies to any resource) a `sf::Font&` or a `sf::Font*` with APIs taking a `std::shared_ptr<sf::Font>` is a massive downgrade to the usability and simplicity of the library, and forces users to manage memory in a very specific way, even when not necessary.

The following code needs to always be valid to maintain SFML's simplicity and lack of unnecessary overhead:

```cpp
int main()
{
    sf::Font font;

    if (!font.loadFromFile("...path..."))
    {
        // ...handle error...
    }

    // ...use `font`...
}
```

Forcing users to unnecessarily use a `std::shared_ptr` there will:

- Introduce unnecessary complexity (we lose a nice linear and deterministic lifetime for `font`);
- Introduce an unnecessary dependency at compile-time on `<memory>`;
- Introduce a new possible unnecessary `nullptr` state for `font`;
- Introduce unnecessary overhead due to dynamic memory allocation;
- Introduce a new possible failure case due to dynamic memory allocation failure (`std::bad_alloc`).

Pedagogically speaking, SFML is also a library that's used to learn C++. We want to use best practices in our codebase internally, in our APIs, in our examples, and in our tests.

Teaching users, especially beginners, to use `std::shared_ptr` instead of understanding the concept of ownership and lifetime severely harms SFML's value as a teaching tool. 

The C++ ecosystem is already plagued by an overuse of `std::shared_ptr`, especially by developers coming from managed languages such as C# or Java, and we do not want to worsen the situation.

You mention a few "pros" of using `std::shared_ptr`, but I do not think they are entirely accurate or compelling:

> No lifetime issues 🥳

This is not true, it is still possible to get lifetime issues with `std::shared_ptr`. For example, moving a `std::shared_ptr` and then attempting to use it would result in undefined behavior. Improper use of `std::shared_ptr` in a large application can lead to ownership cycles, which might result in resources living more than necessary and memory leaks.

If anything, `std::shared_ptr` **hides** lifetime issues that should be otherwise fixed. 

> No need to delete the r-value overload of the same function which means less code to maintain

While technically true, it's just a one-liner -- e.g.:

```cpp
void setFont(Font&& font) = delete;
```

The tiny maintenance burden for functions like the above is miniscule compared to the drawbacks using a `std::shared_ptr`-based API would bring. I'd rather have those overloads completely removed from the codebase rather than switch to `std::shared_ptr` because they're too painful to maintain (which they're not), as I'm quite confident that it's hard to try to invoke `setFont` with an rvalue in the first place.

> Less time spent consulting users online who are experiencing issues thus freeing up more time for other more important work

Misuse of an API is a common reason for a cry of help from a library's users. If many users have the same issues, it warrants investigation, but it doesn't necessarily mean that the API is bad. It could also mean that the documentation is poor, or that the users are simply inexperienced.

From a pedagogical point of view, I'd rather have a user make a mistake and learn about lifetime and ownership from that mistake, compared to wrongfully learning that `std::shared_ptr` is a magic wand that solves everything.

I also don't think it's our duty to constantly help users out when they have issues -- SFML has a wider community of other users that can also offer help, we have tests and examples, there's StackOverflow, Discord, and more.

If anything, I'd research alternative ways of helping users out, maybe with more aggressive and smarter assertions in debug mode, or some sort of primitive lifetime tracking system that's also enabled only in debug mode.

All the same thoughts apply to the `lifetimes` branch -- it seems to add unnecessary complexity and dependencies, and to make SFML's pedagogical value worse, for no real compelling proposed benefit. 

The use of `std::variant<T*, std::shared_ptr<T*>>` turns the ownership problem from a compile-time one into a run-time one. Two objects of type `sf::Text` might have different semantics for the ownership of their `sf::Font`, and it is impossible to tell unless you track the code that creates them.

I really don't think that's an improvement over the status quo.

I think, however, that the idea in general is quite interesting, and warrants some extra investigation. But I strongly believe that SFML is not the right place to implement such an idea. I would recommend also thinking about adding a `T` directly to the variant, so you can have a generic "dependency container". In fact, I think that what you are implementing is a generic **dependency injection** mechanism, which I think is overkill for SFML:

```cpp
template <typename T>
class InjectedDependency
{
private:
    std::variant<T, T*, std::unique_ptr<T*>, std::shared_ptr<T*>> _data;
        // ...need to handle `const`-correctness, maybe also `std::weak_ptr`...

public:
    T& get(); 
    const T& get() const; 
    // ...
};
```

Such a model would give full freedom to the creator of a dependency to decide how its dependant manages the dependency's ownership. But that freedom comes at the costs I described above, so I think that an abstraction like this one should be very strongly motivated before being implemented and propagated throughout an entire API.

One more thing I want to mention, is that you can already achieve the "extra safety" that you desire with the current API, as a user:

```cpp
class TextWithSharedFont
{
private:
    std::shared_ptr<sf::Font> _font;
    sf::Text _text;

public:
    // ...
};
```

With the proper constructors and member functions, the above design would guarantee the same `sf::Font` resource to be shared between multiple `sf::Text` instances and to be released when all `TextWithSharedFont` instances go out of scope.

Before doing anything as drastic as proposed in this issue, I would recommend deeply exploring the following options:

- Reviewing and improving documentation to make it clear how lifetime and ownership is supposed to work in SFML APIs. This might include also directly embedding examples of common mistakes in the documentation, completely solving your problem with having to explain users what they did wrong -- just point them to the docs!

- Looking into debug-only abstractions that can track the lifetime of a resource, and cleanly terminate execution with a helpful error message when that happens. For example, we could track how many dependants are depending on a resource:

```cpp
class Font
{
private:
#ifndef NDEBUG
    std::vector<sf::Text*> _dependants;
#endif

public:
    ~Font()
    {
#ifndef NDEBUG
        if (!_dependants.empty())
        {
             assert(false && "Font object went out of scope 
                              before all dependant texts were destroyed!");
        }
#endif
    } 
};
```

**Comment by vittorioromeo** [comment]
I've created an example branch showing my idea for debug-only lifetime safety checks:

- https://github.com/SFML/SFML/compare/master...vittorioromeo:SFML:experimental/debug_resource_checking

The following program:

```cpp
////////////////////////////////////////////////////////////
// Headers
////////////////////////////////////////////////////////////
#include <SFML/Graphics.hpp>

#include <stdexcept>

////////////////////////////////////////////////////////////
/// Helper function
////////////////////////////////////////////////////////////
sf::Text makeText()
{
    sf::Font font;
    if (!font.loadFromFile("resources/tuffy.ttf"))
        throw std::runtime_error("Could not find font :(");

    return sf::Text(font, "Definitely not a bug!");
}

////////////////////////////////////////////////////////////
/// Entry point of application
///
/// \return Application exit code
///
////////////////////////////////////////////////////////////
int main()
{
    sf::Text text = makeText();
    sf::RenderWindow window(sf::VideoMode(sf::Vector2u(800, 600)), "Boom");

    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
                window.close();
        }

        window.clear();
        window.draw(text);
        window.display();
    }

    return EXIT_SUCCESS;
}
```

Results in the following output:

```cpp
Assertion failed: m_dependantTextCount == 0 && "FATAL ERROR: font object was destroyed before its dependants." "Please ensure that all text objects using this font are destroyed prior to this font to avoid lifetime issues." "In practice, this can happen if a font object is created as a local variable and its address is given to a text." "If the text object is returned from that same scope, the given address will now point to an invalid memory location.", file C:/OHWorkspace/SFML/src/SFML/Graphics/Font.cpp, line 133
```

**Comment by eXpl0it3r** [comment]
I don't think there's enough support for this. Should we close this issue or is there still some alternative approach to helping with lifetime issues?

> I've created an example branch showing my idea for debug-only lifetime safety checks:

Adding such debug facilities seems to add quite a bit complexity to the code and can easily break if not updated at the right place. Given the "solution" to ensure the correct lifetime handling, I don't exactly see this as something I'd want to add to SFML.

**Comment by ChrisThrasher** [comment]
> Should we close this issue or is there still some alternative approach to helping with lifetime issues?

The lack of consensus leads me to believe SFML 3 won't change anything to address lifetime safety issues. I think this issue has run its course and you can close it if you'd like.
