### ISSUE TITLE
Stop changing the default value of `BUILD_SHARED_LIBS`

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#2389]
[Here](https://github.com/SFML/SFML/blob/master/CMakeLists.txt#L47) we default to building shared libraries for most platforms. Not only is this unnecessary to specify, it actively causes lots of pain for Windows users who routinely struggle to understand how DLLs work. Such users would be better off if we stuck to the CMake default of static libraries so they didn't have to try so hard to get their programs building. We can achieve this by simply removing any reference to `BUILD_SHARED_LIBS` and letting it return to its default false-y state.

It's been discussed on the forums [here](https://en.sfml-dev.org/forums/index.php?topic=27996.msg175824#msg175824).

Are there any benefits to defaulting to shared libraries that I'm missing?

**Comment by ChrisThrasher** [comment]
@eliasdaler You may be interested in this issue.

**Comment by eliasdaler** [comment]
I don't use SFML anymore, but I approve. :+1: 

Dynamic linking is only good when you're linking against something which can be installed on your system and be updated from time to time. libcurl, libz, libpng and so on.
Does anyone install libsfml* and update it independently of their games? I very much doubt it (and it would cause serious problems since SFML breaks ABI from time to time).

**Comment by ChrisThrasher** [comment]
CC'ing @Bromeon @vittorioromeo

**Comment by eXpl0it3r** [comment]
This will only partially solve the struggles user have with shared libraries, because:
- OpenAL still needs to be shipped as shared library when using the audio module
- Runtime libraries continue to be shared libraries by default, so they'd still get libgcc and libstdc++ (and libwinpthread) errors

The last part you can "ignore" if you're just interested in making it easier to use SFML for development, because they'll probably have those DLLs in PATH.

**Comment by ChrisThrasher** [comment]
> This will only partially solve the struggles user have with shared libraries

I'm fine with improving the situation even if we can't yet make it perfect. I still think we can find a way to make that OpenAL DLL less annoying to work with.

**Comment by texus** [comment]
I don't really know which option is best to have as a default, but I'll share my thoughts on this matter anyway.

Static libraries aren't super easy to use for novice programmers either:
- They have to remember to define `SFML_STATIC`
- They have to link to all of SFML's dependencies in their project

I've seen enough beginners in the past with tons of linker errors because they forgot about those.
That being said, I do prefer static linking on Windows myself (but I always link dynamically on Linux).

One extra advantage to static linking is that you can't accidentally update the .lib files to a newer version while still using the older .dll files, leading to difficult to solve issues.

One question that I feel should be asked is what the default value of `SFML_USE_STATIC_STD_LIBS` should be. Most arguments for static libs instead of dynamic ones can also be used to argue that `SFML_USE_STATIC_STD_LIBS` should be ON for static libs. Personally I see very little reason to link dynamically to the std lib while linking statically to all other libraries (especially when the exe has to be distributed to other computers).

The main argument that I can think of to have `SFML_USE_STATIC_STD_LIBS` set to OFF is that you need to add extra compiler/linker flags to your project to make it work otherwise (e.g. change /MD to /MT in Visual Studio), but that is just because the default isn't what I imagine most novice Windows users would want these days. And if you already want people to add `SFML_STATIC` and all SFML's dependencies in the project, why not go all in on static linking and also require them to link statically to the std lib by default?

I can provide one argument in favor for shared libraries on Windows: they improve compatibility when combining with other libraries. All libraries in your project should probably be build with the same /MD or /MT setting, which means that it is more work to combine dependencies if one precompiled lib uses /MD and the other uses /MT for its static libraries. All dynamic libraries would be built with /MD so they won't cause such conflicts.

**Comment by eliasdaler** [comment]
> They have to remember to define SFML_STATIC
[They don't need to do it](https://github.com/SFML/SFML/blob/5cd8a164dd7311710f53d12efcf01009a5b2107d/cmake/Macros.cmake#L253).

> Personally I see very little reason to link dynamically to the std lib while linking statically to all other libraries (especially when the exe has to be distributed to other computers).

AFAIK in most cases BUILD_SHARED_LIBS=OFF in many libraries still dynamically links to stdlib. In my opinion, this is not a problem since I think it's not a usual thing to do. 

> I can provide one argument in favor for shared libraries on Windows: they improve compatibility when combining with other libraries. [...]
You can still easily link everything dynamically if you set BUILD_SHARED_LIBS=ON, so it's for the user to decide.

We're talking here about the defaults. The default for CMake (and many other libraries who use it) is not to set any additional CMake variables (which are not a part of lib's CMakeLists.txt) by default. If CMake had BUILD_SHARED_LIBS=ON by default, I wouldn't call to override it in SFML's CMake and set it to "OFF" by default. It's for users to decide what they want.

**Comment by eliasdaler** [comment]
> I'm fine with improving the situation even if we can't yet make it perfect. I still think we can find a way to make that OpenAL DLL less annoying to work with.

Using non-LGPL library as an "alternative backend" can help with that, e.g. [miniaudio](https://github.com/mackron/miniaudio). Then *everything* would be linkable statically without any problem. But that would require a big rewrite, maybe...

**Comment by ChrisThrasher** [comment]
Here's a real world example how this decision is an inconvenience. 

```cmake
# Always build 3rd party deps as static libraries
set(OLD_BUILD_SHARED_LIBS ${BUILD_SHARED_LIBS})
set(BUILD_SHARED_LIBS OFF CACHE BOOL "Build shared libs" FORCE)

# Add examples
option(BUILD_EXAMPLES "Build examples" OFF)
if(BUILD_EXAMPLES)
    add_subdirectory(examples)
endif()

# Add tests
option(BUILD_TESTING "Build tests" OFF)
if(BUILD_TESTING)
    enable_testing()
    add_subdirectory(tests)
endif()

# Restore existing cache value to not alter subsequent builds
set(BUILD_SHARED_LIBS ${OLD_BUILD_SHARED_LIBS} CACHE BOOL "Build shared libs" FORCE)
```

I have to do this extra magic to make sure that shared libraries are disabled when building the examples. The examples build ImGui-SFML and ImGui cannot be built as a shared library. That's a configuration unsupported by the library on Windows. In fact many C++ libraries don't do the required work to make shared libraries work but basically all C++ libraries can be built statically.

SFML changes the default value of `BUILD_SHARED_LIBS` to something which only works with _some_ C++ libraries but not all. Further, it turns `BUILD_SHARED_LIBS` into a cache variable which it typically is not. I can't simply write `set(BUILD_SHARED_LIBS OFF)` anywhere in my build script because that will set the cache variable to `OFF` and on subsequent builds of the library I'll be back to static libraries even though I initially requested shared libs.

We can't expect users to know how to do this correctly.

If we stop messing with `BUILD_SHARED_LIBS` then all I need to do is write `set(BUILD_SHARED_LIBS OFF)` before I download those external sources and everything works exactly how I need it to. That's as easy as we can expect things to work.

**Comment by eXpl0it3r** [comment]
> In fact many C++ libraries don't do the required work to make shared libraries work but basically all C++ libraries can be built statically.

That sounds quite odd, given that all libraries on Linux are shipped as shared libraries. Did the package maintainers patch all these libraries to support shared libs, or was that statement for Windows specifically?

(Btw just commenting on this claim, it doesn't reflect my opinion on the whole topic)

**Comment by ChrisThrasher** [comment]
> That sounds quite odd, given that all libraries on Linux are shipped as shared libraries. Did the package maintainers patch all these libraries to support shared libs, or was that statement for Windows specifically?

It's a Windows thing because MSVC hides all symbols in shared libraries by default whereas GCC and Clang choose to automatically make all symbols visible by default.

**Comment by ChrisThrasher** [comment]
https://github.com/SFML/SFML/pull/2642

Now that we're using CMake presets, we have a mechanism for changing the value of this variable for developer builds and user builds. We can keep specifying `BUILD_SHARED_LIBS=ON` in the preset if we'd like but remove it from user builds. It's perfectly fine to change these variables from presets. It's expected that presets will make opinionated choices. Presets are where you're supposed to encode that opinions.

**Comment by eXpl0it3r** [comment]
We'll be breaking some scripts for SFML 3 for people, then again we'll be breaking a lot of stuff with SFML 3 anyways.

I think it makes sense to keep the "default"/common behavior, especially since it can interfere with other CMake scripts in the "pipeline".

Let's try and see how it performs for users. We've been having struggling users for both dynamic and static linking, I don't think this change will increase the struggle in general.
