### ISSUE TITLE
Ability to choose which SFML modules to use on Android

### ISSUE THREAD

**Issue by Zombieschannel** [SFML/SFML#2394]
## Subject of the issue

Currently, on Android, in the file SFMLActivity.cpp in SFML/Main, there is a function loadLibrary() which loads all SFML modules + openal. If it fails, exit(1) is called. Unfortunately, there is no way to remove loading these libraries without modifying SFML code itself. For example, if there is no audio in an app, sfml-audio, and openal aren't needed. Removing these in the final apk/aab, can reduce the file size quite a bit. If you don't use sfml-audio anywhere, removing the loadLibrary("sfml-audio"...); does not effect the app, it works anyway.

![image](https://user-images.githubusercontent.com/54750550/217066889-3b25af46-4c85-4266-8125-9703c271e0c1.png)

A quick idea of how to fix this:

Just remove the line exit(1);

- if those ".so" files are actually needed, and they are just missing, the app will crash anyway but you'll still be able to see that they are missing in the logs
- if it isn't needed, the app will still complain, but at least it won't get stuck in a reboot while loop

## Your environment

Android Studio 2022.1.1 on Windows 10
SFML 2.6.x branch
Used CMake, Ninja, Android NDK 25

## Steps to reproduce

Just don't use sfml-audio anywhere and don't include the sfml-audio and openal in the final apk/aab.

## Expected behavior

It should ignore the fact that sfml-audio is missing since it isn't needed anyway.

## Actual behavior

It gets stuck in a forever loop.

**Comment by ChrisThrasher** [comment]
> if those ".so" files are actually needed, and they are just missing, the app will crash anyway but you'll still be able to see that they are missing in the logs

What logs do you get when it crashes this way? Is it still clear what went wrong?

**Comment by Zombieschannel** [comment]
If I have that exit(1) line commented out:

So first of all, when I remove sfml-audio and openal from cmakelists in the project, as expected, it does not include these files in the final apk. 

- Now if I don't use anything from sfml-audio in my code, compilation is successful, running on the device works, you just get those warnings that it was unable to find libsfml-audio.so and libopenal.so.
- If I #include <SFML/Audio.hpp> and write some basic code that opens an audio file and plays it, compilation is not successful, and I get errors. 
- If I add sfml-audio to the cmakelists so that it adds the libsfml-audio.so to the final project, and do everything in the step above, compilation is successful, it does not mention that openal was missing. In the final apk, libopenal.so isn't included, but libsfml-audio.so is. Running this version throws out the following errors, and the app freezes again (probably Android rebooting the app when it crashes or something):
```
dlopen("/data/app/~~lAoO4pQp-_2_Zl_HxfXlzw==/com.ChainReaction.debug-fgcFgDyRbxJbRIZ2fiJ2Ow==/lib/arm64/libexample.so"): dlopen failed: library "libopenal.so" not found: needed by /data/app/~~lAoO4pQp-_2_Zl_HxfXlzw==/com.ChainReaction.debug-fgcFgDyRbxJbRIZ2fiJ2Ow==/lib/arm64/libsfml-audio-d.so in namespace classloader-namespace
dlopen("/data/app/~~lAoO4pQp-_2_Zl_HxfXlzw==/com.ChainReaction.debug-fgcFgDyRbxJbRIZ2fiJ2Ow==/lib/arm64/libopenal.so"): dlopen failed: library "/data/app/~~lAoO4pQp-_2_Zl_HxfXlzw==/com.ChainReaction.debug-fgcFgDyRbxJbRIZ2fiJ2Ow==/lib/arm64/libopenal.so" not found
dlopen("/data/app/~~lAoO4pQp-_2_Zl_HxfXlzw==/com.ChainReaction.debug-fgcFgDyRbxJbRIZ2fiJ2Ow==/lib/arm64/libsfml-audio-d.so"): dlopen failed: library "libopenal.so" not found: needed by /data/app/~~lAoO4pQp-_2_Zl_HxfXlzw==/com.ChainReaction.debug-fgcFgDyRbxJbRIZ2fiJ2Ow==/lib/arm64/libsfml-audio-d.so in namespace classloader-namespace
dlopen("/data/app/~~lAoO4pQp-_2_Zl_HxfXlzw==/com.ChainReaction.debug-fgcFgDyRbxJbRIZ2fiJ2Ow==/lib/arm64/libsfml-network-d.so"): dlopen failed: library "/data/app/~~lAoO4pQp-_2_Zl_HxfXlzw==/com.ChainReaction.debug-fgcFgDyRbxJbRIZ2fiJ2Ow==/lib/arm64/libsfml-network-d.so" not found
```

**Comment by texus** [comment]
I also believe that it would be better to just continue than to call exit(1) if you don't know whether the app will need the library or not.

For the sake of having an alternative method to think about, what about the following?
- Require that sfml-system exists in the apk. If this is not found then print a clear error. This should catch all cases where SFML is completely missing. Either call exit(1) in this case, or just let it continue and crash later.
- Search all other components, but DON'T print a warning when the component isn't found. Since the libraries should always be copied in the .apk automatically (which is likely working as sfml-system existed), we assume that you aren't using this component. If this assumption would still be wrong, the program will crash later in the same way that you would also get from this PR.
- If sfml-audio is found, require that openal is also found. Print an error message about its absence and fail in the same way as you would for a missing sfml-system library.

I would thus add a bool return type to loadLibrary and add an additional bool parameter that specifies whether the library is required or not (i.e. whether it prints an error when missing or not). Something like this:
```c++
loadLibrary("sfml-system", lJNIEnv, ObjectActivityInfo, true); // required
loadLibrary("sfml-window", lJNIEnv, ObjectActivityInfo, false);
loadLibrary("sfml-graphics", lJNIEnv, ObjectActivityInfo, false);
loadLibrary("sfml-network", lJNIEnv, ObjectActivityInfo, false);
if (loadLibrary("sfml-audio", lJNIEnv, ObjectActivityInfo, false))
    loadLibrary("openal", lJNIEnv, ObjectActivityInfo, true); // required, if sfml-audio was found
```

**Comment by kimci86** [comment]
This was solved on main branch so this issue probably should not belong to 2.6.2 milestone.
