### ISSUE TITLE
SFML 3 tests compile error

### ISSUE THREAD

**Issue by dustdfg** [SFML/SFML#2413]
## Subject of the issue

Compile error on tests.

## Your environment

* Debian 10
* gcc 8.3.0
* sfml git master

## Steps to reproduce

Compile sfml3 with tests

## Expected behavior

Compilation and linking

## Actual behavior

All the tests are compiling but linker has another opinion.

I tried to disable the tests one by one, the problems targets all sfml modules.  Looks like it needs c++17 because they are all counting on std::filesystem

Error message 1:

```
[ 62%] Linking CXX executable ../bin/test-sfml-system
/usr/bin/ld: CMakeFiles/test-sfml-system.dir/System/FileInputStream.test.cpp.o: in function `DOCTEST_ANON_FUNC_2()':
FileInputStream.test.cpp:(.text+0x555): undefined reference to `std::filesystem::temp_directory_path[abi:cxx11]()'
/usr/bin/ld: FileInputStream.test.cpp:(.text+0x55d): undefined reference to `std::filesystem::__cxx11::path::has_root_directory() const'
/usr/bin/ld: FileInputStream.test.cpp:(.text+0x6ed): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: FileInputStream.test.cpp:(.text+0x6fc): undefined reference to `std::filesystem::__cxx11::path::has_root_directory() const'
/usr/bin/ld: FileInputStream.test.cpp:(.text+0x860): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: FileInputStream.test.cpp:(.text+0xc8e): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: FileInputStream.test.cpp:(.text+0x121e): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: FileInputStream.test.cpp:(.text+0x1226): undefined reference to `std::filesystem::remove(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: FileInputStream.test.cpp:(.text+0x12fc): undefined reference to `std::filesystem::__cxx11::path::has_filename() const'
/usr/bin/ld: FileInputStream.test.cpp:(.text+0x1386): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: FileInputStream.test.cpp:(.text+0x14e3): undefined reference to `std::filesystem::__cxx11::path::has_root_directory() const'
/usr/bin/ld: FileInputStream.test.cpp:(.text+0x1674): undefined reference to `std::filesystem::__cxx11::path::has_filename() const'
/usr/bin/ld: FileInputStream.test.cpp:(.text+0x16fe): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: CMakeFiles/test-sfml-system.dir/System/FileInputStream.test.cpp.o: in function `TemporaryFile::~TemporaryFile()':
FileInputStream.test.cpp:(.text._ZN13TemporaryFileD2Ev[_ZN13TemporaryFileD5Ev]+0x75): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: FileInputStream.test.cpp:(.text._ZN13TemporaryFileD2Ev[_ZN13TemporaryFileD5Ev]+0x7d): undefined reference to `std::filesystem::remove(std::filesystem::__cxx11::path const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [test/CMakeFiles/test-sfml-system.dir/build.make:244: bin/test-sfml-system] Error 1
make[1]: *** [CMakeFiles/Makefile2:464: test/CMakeFiles/test-sfml-system.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

Error message 2:
```
[ 98%] Linking CXX executable ../bin/test-sfml-audio
/usr/bin/ld: ../lib/libsfml-audio.so.3.0.0: undefined reference to `std::filesystem::__cxx11::path::_M_find_extension() const'
/usr/bin/ld: ../lib/libsfml-audio.so.3.0.0: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: ../lib/libsfml-audio.so.3.0.0: undefined reference to `std::filesystem::absolute(std::filesystem::__cxx11::path const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [test/CMakeFiles/test-sfml-audio.dir/build.make:245: bin/test-sfml-audio] Error 1
make[1]: *** [CMakeFiles/Makefile2:457: test/CMakeFiles/test-sfml-audio.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

**Comment by eXpl0it3r** [comment]
Yes, SFML 3 is moving to C++17, as such it's a requirement to build SFML, not just the tests.

According to the [Compiler Support page](https://en.cppreference.com/w/cpp/compiler_support/17), GCC 8 should however support `std::filesystem`.

**Comment by dustdfg** [comment]
> Yes, SFML 3 is moving to C++17, as such it's a requirement to build SFML, not just the tests.
> 
> According to the [Compiler Support page](https://en.cppreference.com/w/cpp/compiler_support/17), GCC 8 should however support `std::filesystem`.

You don't understand the issue not about c++17 support its entirely about tests that don't want to compile. I can compile sfml itself without any troubles but I can't compile tests

**Comment by eXpl0it3r** [comment]
For GCC < 9.1 you'll need to link libc++fs

> Using this library may require additional compiler/linker options. GNU implementation prior to 9.1 requires linking with -lstdc++fs and LLVM implementation prior to LLVM 9.0 requires linking with -lc++fs.

https://en.cppreference.com/w/cpp/filesystem

We'll have to see if this is something we'd want to manage in SFML.

**Comment by dustdfg** [comment]
As I knew, GCC prior to version 9 separates std::filesystem symbols to a separate library stdc++fs which must be also linked. When I changed the CMake file of tests:

```diff
@@ -14,6 +14,7 @@ get_target_property(DOCTEST_INCLUDE_DIRS doctest INTERFACE_INCLUDE_DIRECTORIES)
 target_include_directories(doctest SYSTEM INTERFACE ${DOCTEST_INCLUDE_DIRS})
 
 add_subdirectory(install)
+target_link_libraries(test-sfml-install PUBLIC stdc++fs)
 set_target_warnings(test-sfml-install)
 
 add_library(sfml-test-main STATIC
@@ -26,7 +27,7 @@ add_library(sfml-test-main STATIC
 )
 target_include_directories(sfml-test-main PUBLIC TestUtilities)
 target_compile_definitions(sfml-test-main PUBLIC DOCTEST_CONFIG_REQUIRE_STRINGIFICATION_FOR_ALL_USED_TYPES)
-target_link_libraries(sfml-test-main PUBLIC SFML::System doctest::doctest_with_main)
+target_link_libraries(sfml-test-main PUBLIC SFML::System doctest::doctest_with_main stdc++fs)
 set_target_warnings(sfml-test-main)

```

It works with it. I greped main CMake file to found something like this and I didn't found why I can compile sfml as library...

**Comment by eXpl0it3r** [comment]
I'd guess it might start failing when liking SFML itself, while still being able to build the library without referencing the lib

**Comment by dustdfg** [comment]
> I'd guess it might start failing when liking SFML itself, while still being able to build the library without referencing the lib

In this case it is a problem of a library and we need a centralized way to catch it. I guess it can be done inside `cmake/Macros.cmake`

**Comment by dustdfg** [comment]
> > We'll have to think whether we really want to add such compiler workarounds
> 
> If we don't, then maybe we should treat gcc 8 as "officially unsupported" (possibly with a check in CMake).
> 
> @dustdfg Do you know how complex it would be to support this in SFML's CMake?

I was looking for a solution. I found something like good (?) solution https://stackoverflow.com/questions/58545562/what-is-the-correct-way-to-link-c17-filesystem-with-cmake (see links in an answer)

**Comment by ChrisThrasher** [comment]
Given Debian 10's 2019 release date it's stretching the limits of what Linux distributions SFML 3 will support. If you asked me, I'd say that even Ubuntu 20 should be on the chopping block to drop before SFML 3's release since it's holding us back in some ways.

A quick search shows that GCC 4.8.5 and 8.3 seem to be the only two GCC versions that Debian 10 ships. SFML 3 is targeting the current state of and the future of OSes so I'm reluctant to add workarounds for compilers and/or platforms that are fading from popularity. It's the job of SFML 2 to continue to support these aging OSes.

It's worth mentioning that you can solve this yourself by modifying `CMAKE_CXX_FLAGS` when configuring SFML. CMake allows you to inject compiler or linker flags into any project you build without having to modify the source code. Please try this to confirm that it works since it may inform future changes.

That being said I don't necessarily veto such an addition. It would probably only take 3 lines of CMake to conditionally link `stdc++fs` for GCC 8. It wouldn't even be [the only GCC 8 workaround in the codebase.](https://github.com/SFML/SFML/blob/9d0b2ba592db496dc46bb3ff0ea920d3f2b26ad5/cmake/CompilerWarnings.cmake#L72) If we do add this however, it should not mean that we promise to maintain effortless GCC 8 support for the lifetime of SFML 3. That doesn't mean GCC 8 will be impossible to use, it just means that users on old platforms may have to add some extra configuration options to make it work.

**Comment by ChrisThrasher** [comment]
I'm going to close this issue since there is a workaround that does not involve modifying the source code and by the time SFML 3 is released GCC 8 will be 5 or more years out of date. Also in the time since this issue was opened a new Debian version has been released so GCC 8 is further waning from relevance.
