### ISSUE TITLE
Make randomness easy with new `sf::rng()` API

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#2434]
## Subject of the issue

https://github.com/SFML/SFML/pull/2433 shows that we need randomness in 1 location in the library and in 2 examples. Further, it's common that users want a random number generator for use in their games. It's also well established that the C++ randomness API in the `<random>` header is not beginner friendly so we can safely assume that many SFML users are getting it wrong either by using `rand()` or by misusing the `<random>` interface.

I propose we solve these problems with a new API with the following signature that returns a `thread_local` `std::mt19937&`:

```cpp
namespace sf
{
std::mt19937& rng();
}
```

Here's what this API does for us:

1. Increases code reuse by letting us define a random number generator in 1 place instead of 3.
2. Does the hard work to [initialize a random number generator the right way](https://github.com/ChrisThrasher/boids/blob/master/src/Boid.cpp#L8-L14) [[citation](https://docs.google.com/presentation/d/1-XT-NpoBj8W3OBv7I5I8TXyxZhcFI78QhYj2FrPAlxg/edit#slide=id.g11bbcd2da87_0_308) from Ben Deane]
3. Encourages users to use C++ random number distributions instead of hand-rolling modulo expressions with `rand()` to approximate a particular distribution which is [fraught with issues](https://stackoverflow.com/a/49880109/17884691)
4. Eliminates concurrency issues and improves performance by using `thread_local` random number generators. [[citation](https://youtu.be/1KTgc2SEt50?t=1452)]

This will not be hard to implement and test so if this proposal is well-received, I can implement it real quick so we can see what it would look like in practice.

**Comment by ChrisThrasher** [comment]
There was a concern about determinism discussed in #2433. This does not get in the way of users who want deterministic randomness. If someone wants to create a deterministic RNG for their game, they can still do that. This API is focused on the majority of users with relaxed requirements who are fine with randomness that changes with each invocation of their program.

We could potentially add a default argument to `rng()` that lets users specify their own seed sequence so that they have full control over the initial state of the `mt19937`. This would make the API no more complicated for the simple use case but would give more control to those who do care about determinism. I didn't include this in my initial proposal because I think it's bit overkill but [I have already implemented and tested this if you'd like to see it](https://github.com/PickNikRobotics/RSL/blob/ecd88708f5b4742aa484c87127a1d0f36d2c310d/src/random.cpp#L11-L30).

**Comment by eXpl0it3r** [comment]
This doesn't really fit the scope of SFML in my opinion, nor should SFML try to be an API prettifier of the standard library. The goal of SFML really isn't to simplify C++, but it's to offer easily accessible, cross-platform APIs for windowing, audio, 2D graphics and networking. In the past SFML also provided some "utility" functionalities that weren't provided by C++, but they exists primarily, because SFML needed them internally (like `sf::Thread` or `sf::Clock`).

We had a lot of discussion on whether `sf::Clock` & `sf::Time` are really justified in SFML 3 and by my own scoping it probably wouldn't, however since it's an existing feature, still used internally and closely connected to real-time application development, we decided to keep it. `sf::rng()` would not fit that criteria.

I think it's important to differentiate between usages in example code and library code. We use a random number generator in one place in the library code, which doesn't really warrant the extraction into a public interface.

If SFML was to have support for random number generation (which it btw. did in SFML 1.x), it would provide facilities to actually generate random numbers, instead of just constructing standard library utilities, which can then be used to generate random numbers. So even if we did decide that this falls into the SFML scope, the proposed API, wouldn't really fit what I'd expect from an SFML API.

Additionally, it's quite an imbalanced API, that can just create one out of many different random number generation engines. The mersenne twister is pretty good, but it's just really odd to have a single function for that one engine and nothing else.
