### ISSUE TITLE
Compiler errors with gcc 5

### ISSUE THREAD

**Issue by jcar87** [SFML/SFML#2594]
## Subject of the issue

Cannot build sfml 2.6.0 from source with gcc 5.

## Your environment

sfml 2.6.0, Linux with gcc 5

## Steps to reproduce

Build with the cmake option `WARNINGS_AS_ERRORS` set to `OFF`

## Expected behavior

A successful build (perhaps with warnings)

## Actual behavior

```
g++: error: unrecognized command line option ‘-Wnull-dereference’
g++: error: unrecognized command line option ‘-Wmisleading-indentation’
g++: error: unrecognized command line option ‘-Wduplicated-cond’
make[2]: *** [src/SFML/System/CMakeFiles/sfml-system.dir/Clock.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
g++: error: unrecognized command line option ‘-Wnull-dereference’
g++: error: unrecognized command line option ‘-Wmisleading-indentation’
g++: error: unrecognized command line option ‘-Wduplicated-cond’
g++: error: unrecognized command line option ‘-Wnull-dereference’
g++: error: unrecognized command line option ‘-Wmisleading-indentation’
g++: error: unrecognized command line option ‘-Wduplicated-cond’
make[2]: *** [src/SFML/System/CMakeFiles/sfml-system.dir/Err.cpp.o] Error 1
make[2]: *** [src/SFML/System/CMakeFiles/sfml-system.dir/Lock.cpp.o] Error 1
make[1]: *** [src/SFML/System/CMakeFiles/sfml-system.dir/all] Error 2
make: *** [all] Error 2
```

I can't find a mention in the documentation about gcc5 not being supported, clarification would be appreciated, thanks!

**Comment by ChrisThrasher** [comment]
We never made an intentional decision to stop supporting GCC 5. It's simply a matter of nobody using GCC 5 and reporting this issue until now. In theory GCC 5 works if you stop applying those warnings.

Is there a GCC 5 flag that lets you ignore unknown warnings?

**Comment by jcar87** [comment]
I see, thanks @ChrisThrasher ! Indeed removing the warnings actually works successfully - but it's a bit unergonomic as the only way is to patch the CMake scripts rather than via a configuration.
I can't find a universal option gcc that would ignore _all_ unknown warnings, if my understanding of the gcc documentation is correct I think you still need to know the _name_ of the warning to disable it.

https://gcc.gcc.gnu.narkive.com/Xd4IjTKh/feature-request-wno-unknown-warnings-to-silently-ignore-unknown-warning-control-flags

**Comment by ChrisThrasher** [comment]
Given [the last GCC 5 release was in 2017](https://gcc.gnu.org/gcc-5/), I'm not inclined to add the CMake generator expressions required to fix this. I'm sorry but I think for the sake of supporting GCC 5, patching the source is your best bet. I believe what Conan Center decided was that SFML 2.6 simply doesn't work on GCC 5 and that's not unreasonable either. I can't imagine there's a huge crossover between SFML 2.6 users and GCC 5 users.

Here is the one line you have to remove to disable all compiler warnings.

https://github.com/SFML/SFML/blob/11b73743c42cf7ecd7c596ba83fdbf1150ffa96c/cmake/Macros.cmake#L69

This was a good issue to raise though and I appreciate you bringing it up. I am thinking more lately about how SFML applies compiler warnings. The fundamental problem remains that so long as we're always applying warnings to all builds all the time, we always have to be sure that we don't apply invalid warnings to an otherwise valid compiler. I have some ideas for improving this situation but it's safe to say such changes won't land in SFML 2. They'll happen sometime in the SFML 3 release series.
