### ISSUE TITLE
clang compile error: argument unused during compilation: '-stdlib=libc++'

### ISSUE THREAD

**Issue by pierr3** [SFML/SFML#2623]
## Subject of the issue

Compiling SFML on macOS sonoma with any version of clang through vcpkg fails, due to attemtping to compile C files with '-stdlib=libc++' argument. It also seems like that version ignores the compiler used by VCPKG and will always call the system default.

## Your environment

* macOS Sonoma Public Beta
* 2.6.0
* Using VCPKG in Manifest Mode
* Tried with all available versions of apple clang + llvm clang through homebrew

## Steps to reproduce

Compile the below using CMake and the following vcpkg.json manifest, with vcpkg installed:

```
{
    "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg-tool/main/docs/vcpkg.schema.json",
    "name": "test-issue",
    "version": "1.0.0",
    "dependencies": [
        "sfml"
    ]
  }
```

```cpp
#include <SFML/Graphics.hpp>

int main()
{
    sf::RenderWindow window(sf::VideoMode({1280, 720}), "Minimal, complete and verifiable example");
    window.setFramerateLimit(60);

    while (window.isOpen())
    {
        for (sf::Event event; window.pollEvent(event);)
        {
            if (event.type == sf::Event::Closed)
                window.close();
        }

        window.clear();
        window.display();
    }
}
```

## Additional information

Attached is build log which shows the error. See lines 40 to 43.

Also see issue in vcpkg: https://github.com/microsoft/vcpkg/issues/32574

Thanks for the help! Let me know if I can support.

[install-arm64-osx-dbg-out.log](https://github.com/SFML/SFML/files/12135363/install-arm64-osx-dbg-out.log)

**Comment by ChrisThrasher** [comment]
https://github.com/SFML/SFML/compare/2.6.x...libc++

Can you try out this branch to confirm it fixes your problem?

**Comment by texus** [comment]
While I imagine just removing those lines would fix the issue, I think it might break some older versions.

libc++ has been the default since macOS 10.9 (released in 2013), so passing `-stdlib=libc++` to clang isn't really needed anymore (unless you would still want to support older versions).

However, Xcode was still passing `-stdlib=libstdc++` until Xcode 13.3 (https://developer.apple.com/documentation/xcode-release-notes/xcode-13_3-release-notes). So from what I understood from the documentation when I researched this a while back, you still need `sfml_set_xcode_property(${target} CLANG_CXX_LIBRARY "libc++")` if CMAKE_GENERATOR equals Xcode to support Xcode version older than 13.3 (which was released in March 2022).

So you may also want to test with only dropping the `else()` case in that code instead of dropping that entire if-else block.

**Comment by ChrisThrasher** [comment]
https://github.com/SFML/SFML/actions/runs/5631416810/job/15258344565#step:5:9

This CI job uses Xcode 13.2 and thus libstdc++ and it still works. What problem are we solving by requiring that Xcode users use libc++?

**Comment by texus** [comment]
That CI job is probably also using libc++, as I don't think libstdc++ is even supported anymore. The documentation is just very limited and vague. Apple has deprecated libstdc++ in clang a long time ago already, so we definitely need to use libc++ on mac, it's just a matter of whether it is enabled by default or whether we still need to manually specify it.

It wouldn't really make sense for Xcode 13.2 to still use libstdc++ by default, so I probably misinterpreted the release notes. It would make more sense that they just removed the ability to specify `CLANG_CXX_LIBRARY=libstdc++` and are just always passing `libc++` now instead of allowing you to override it. The line `Xcode no longer passes -stdlib=libstdc++ to Clang` would then simply mean that they no longer pass it even if you request it, and not that they used to pass it as default (like I previously interpreted it).

I did read something earlier that suggested that the default stdlib is actually dependent on the deployment target (set with [CMAKE_OSX_DEPLOYMENT_TARGET](https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html)), not on the Xcode version. So I'm starting to think it is fine to completely remove the `sfml_set_xcode_property(${target} CLANG_CXX_LIBRARY "libc++")` line, as it should work as long as the deployment target isn't set to an old version (e.g. 10.8).

**Comment by ChrisThrasher** [comment]
https://github.com/SFML/SFML/pull/2234/commits/e4ed6ef0d9d5cd5865969fe9fb655888b3837956

Looks I already fixed this in SFML 3 a year ago. We can cherry-pick this onto 2.6.x so long as someone is able to confirm that it fixes this problem. I don't yet have access to macOS Sonoma.

**Comment by pierr3** [comment]
I manually changed the vcpkg portfile to the libc++ branch (see below if interested) and it nows builds fine on apple clang14-arm64!

It'd be good if someone else could confirm as I'd perfer to make sure it wasn't only on my side.

Thanks for the quick reply on this!

<details>
  <summary>vcpkg config</summary>

```
vcpkg_from_github(OUT_SOURCE_PATH SOURCE_PATH
    REPO SFML/SFML
    REF cef335a342cad3a0bebc96fdace679c80913926b
    HEAD_REF libc++
    SHA512 16e3ddebda53b0652a293a7cfb09a9487496cb574c67f865d36e953d1b51b61bbed7ad023dc42638abbe8592f5ff4d96b4343166a4a0a55fdf8c9553a1c37920
    PATCHES
        fix-dependencies.patch
)
```

</details>

**Comment by ChrisThrasher** [comment]
https://github.com/SFML/SFML/pull/2625

I tweaked my original patch to leave the Xcode property in place just in case that was still needed. Seems safe to keep that there and it should be unrelated to the original problem.

**Comment by ChrisThrasher** [comment]
Thank you for the bug report!
