### ISSUE TITLE
Add Native Support for SVG's

### ISSUE THREAD

**Issue by DimensionalSpace** [SFML/SFML#2793]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [x] I understand [SFML's scope](https://www.sfml-dev.org/contribute.php#general-considerations) and believe the feature fits it

### Describe your feature request here

A way which users can import SVG's in SFML without the use of other libraries.

### Use Cases

When one wants to render non-pixellated graphics

### API Example

```cpp
#include <SFML/Graphics.hpp>

int main()
{
    sf::Sprite sprite;
    sf::SVGTexture svg;
    svg.loadFromFile("/svg.svg");
    sprite.setTexture(svg.raster());
    sf::RenderWindow window(sf::VideoMode({1280, 720}), "Minimal, complete and verifiable example");
    window.setFramerateLimit(60);

    while (window.isOpen())
    {
        for (sf::Event event; window.pollEvent(event);)
        {
            if (event.type == sf::Event::Closed)
                window.close();
        }

        window.clear();
        window.draw(sprite);
        window.display();
    }
}
```

**Comment by BrokenShards** [comment]
I really like the idea of being able to rasterize and render vector images using just SFML, but would that not mean we would either have to write an SVG parser and rasterizer, or add a library that does so as a dependency? (And the for other vector file formats that would be wanted).
I don't want to be a wet sock, and I would love that functionality, but I'm not so sure if this should be included in SFML itself. Although old, this library seems to do what you want and shouldn't be too hard to make it use more modern SFML. https://github.com/kamirr/sf-svg

**Comment by ChrisThrasher** [comment]
> would that not mean we would either have to write an SVG parser and rasterizer, or add a library that does so as a dependency?

Yes it would require doing one or the other, neither of which sounds particularly appealing.

**Comment by eXpl0it3r** [comment]
Old requests on the forum:
- https://en.sfml-dev.org/forums/index.php?topic=7667.0 (2012)
- https://en.sfml-dev.org/forums/index.php?topic=16381.0 (2014)

Projects / libraries mentioned in discussions:
- https://github.com/kamirr/sf-svg
- https://github.com/VL-Impact/SFML-SVGTexture
- https://github.com/degski/svg2png
- https://github.com/memononen/nanosvg

I see two main approaches to SVG support:
1. Render the SVG at a specified size into a texture
2. Create an "object tree" of some sorts that contain modifiable lines and Bezier curves, etc.

In either case, we would need to have support of the following, either natively or through a library:
- SVG/XML parsing
- Bezier curve drawing

---

I currently also see some more important topics, especially since I don't see SFML being a limiting factor in writing an extension library that would just do that, as proven by the examples.

Until someone champions this beyond just a rough draft, I recommend to convert the SVGs beforehand into PNGs and/or vertex data.

**Comment by eXpl0it3r** [comment]
Found an interesting resource, written by the author of resvg, highlighting just how hard it is to get SVG "right" or even "best effort": https://razrfalcon.github.io/notes-on-svg-parsing/

**Comment by MarioLiebisch** [comment]
I remember looking this one of the first times this idea came up. On paper it's a neat solution to avoid having lots and many big textures, but once you realize how many features and possibilities SVGs have, rendering them in realtime becomes a problem. So I'd totally opt for using a third party library to render textures just in time, akin to Fonts (maybe even using a similar atlas approach?).

**Comment by eXpl0it3r** [comment]
Given the size of SVG, I don't think we'll ever effectively support SVG in SFML. Meaning that while it's possible to provide *some* support, I don't see the added value of having a rather surface level implementation and would rather leave that as extension library.
