### ISSUE TITLE
Raw input for mouse movement

### ISSUE THREAD

**Issue by madeso** [SFML/SFML#304]
SFML currently uses WM_MOUSEMOVE and this smooths out the movement and is dependent on the resolution. Smoothing is preferred when the game integrates with the desktop. However when the mouse controls a 3d camera smoothing is less desired.

There should therefore be a option to enable non-smoothed  "raw" input. The solution seems to be WM_INPUT http://msdn.microsoft.com/en-us/library/windows/desktop/ee418864%28v=vs.85%29.aspx

WM_INPUT also provides a resolution independent movement that might be good if the game needs to be run at low resolutions and/or sub-pixel movements are needed.

The forum thread where this issue originated from: http://en.sfml-dev.org/forums/index.php?topic=9426

**Comment by JonnyPtn** [comment]
Using raw input for keyboard (and also joysticks I think) would be beneficial too

**Comment by sro5h** [comment]
I'm also interested in this feature. I got a linux version and the windows implementation of hornta to work ([link to my fork](https://github.com/sro5h/sfml/tree/feature/raw_input)).
The linux version is using xinput to get the raw mouse data and is inspired by the implementation of SDL2. I basically took over hornta's `MouseMotionEvent` but changed the member method to `setRawMouseEnabled`.
I'm not that familiar with cmake and couldn't figure out how to add xinput as a dependency (You need to link the project using sfml on linux with `-lXi` for now). The attached file shows how to use the feature, basically:
```c++
window.setRawMouseEnabled(true);

while (window.isOpen())
{
    while(window.pollEvent(ev))
    {
        if (ev.type == sf::Event::MouseMotion)
        {
            std::cout << "x = " << ev.mouseMotion.x << ", y = " << ev.mouseMotion.y << std::endl;
        }
    }
    window.clear();
    window.display();
}
```

**Comment by sro5h** [comment]
I figured out how to add xinput as a dependency, you no longer need to link the final project with `-lXi` on Linux :)

**Comment by Foaly** [comment]
This is great! Thank you for contributing!

Maybe I missed something here, but I was wondering why did you chose to make another event? There is already an event for mouse motion `sf::MouseMoved`. I think it would be a better design to just have one event and use `setRawMouseEnabled()` to set the "resolution".

**Comment by sro5h** [comment]
Thank you for your feedback. I wasn't sure if it would make sense for some people to have access to both the raw mouse deltas and the pixel position. So i took over the the interface from hornta's Windows implementation. On the other hand one could still get the pixel position through `sf::Mouse::getPosition`.
I guess you make a valid point and i think that having both a `MouseMotion` and `MouseMoved` Event could lead to confusion.

**Comment by mantognini** [comment]
Could you clarify what does `setRawMouseEnabled` exactly do? I haven't looked at your implementation but the header doesn't include the expected documentation. :)

**Comment by sro5h** [comment]
Yes i haven't documented it yet, i will add some documentation comments later this evening :)
Essentially `setRawMouseEnabled` enables/disables the generation of `MouseMoved` events. On hornta's implementation for Windows it (un)registeres a `RAWINPUTDEVICE` and for Linux it (un)registers for the `XI_RawMotion` event. So you will only receive `MouseMotion` events if you want to.

**Comment by mantognini** [comment]
Those are really technical details I don't understand (not being a Windows/Linux dev). ;)

So, does `setRawMouseEnabled(true)` mean the cursor doesn't move anymore on the screen and we get only relative movement? ("FPS-style cursor")

**Comment by sro5h** [comment]
No it does not hide the cursor or lock it in a specific place. It gives you the relative movement, even if your cursor hits the edge of your screen.

**Comment by mantognini** [comment]
So, why not simply always add this information to the existing event? Is
there a side effect to this feature on Linux/Windows?

**Comment by sro5h** [comment]
You mean i should add something like `rawX` and `rawY` to `MouseMoved`?
The problem is that `MouseMoved` uses a different event (MotionNotify vs XI_RawMotion on Linux and WM_MOUSEMOVED vs WM_INPUT on Windows) than `MouseMotion`. I think it would make sense to keep them seperated. Though i am not really happy with the name `MouseMotion` but can't think of a better one.

**Comment by mantognini** [comment]
This isn't a problem on macOS so that's why I got confused. With that in
mind, having a second kind of event for motion is fine, I guess, because
one would use one of them, not both at the same time.

As for the name, what about RelativeMouseMove?

**Comment by sro5h** [comment]
Ok, a MacOs implementation is still missing, do you know how to do it? I searched on the internet yesterday and found some hints but nothing concrete. But i haven't got access to a mac so i wouldn't be able to try it anyway

Yeah that sounds clearer than MouseMotion. Then i would also make sense to use a different name for the method in `sf::Window`. Maybe something like `setMouseCursorRelative` to follow the likes of `setMouseCursorVisible` and `setMouseCursorGrabbed`?

**Comment by mantognini** [comment]
Don't worry too much about macOS, this feature is simple enough that I can provide the mac implementation when the API is stable. ;-)

About `setMouseCursorRelative`, I'm still wondering whether we should simply always have the feature on and remove this function altogether. What do you think?

**Comment by sro5h** [comment]
Ok that's nice, then i can close all the chrome tabs i kept open ;D

About `RelativeMouseMove`: I think its kind of long and it would be nicer if it began with 'Mouse' like all other mouse related events, wouldn't it? `MouseRelativeMove` sounds kind of weird though

Sure, that would be the best way.If someone doesn't care about those events he can just ignore them.
If we can settle on a name for the Event i will update my fork with the points we discussed and add documentation comments :)

**Comment by mantognini** [comment]
MouseRelativeMove or MouseMoveRelative? The latter seems more consistent with other event names but... What do you think @SFML/sfml?

**Comment by eXpl0it3r** [comment]
Since this issue is about "raw input", is raw mouse data always relative?

I'd go for `MouseMovedRelative` so it's the same as `MouseMoved` except for the suffix. (Or would `MouseMovedRaw` make sense as well?

**Comment by sro5h** [comment]
Yes it is relative

I think both would make sense.

**Comment by hornta** [comment]
I like MouseMovedRelative. And I like to rename the event properties from x and y to something like deltaX and deltaY.

Another idea is to instead of introduction a new event, we could add two new properties to the MouseMoveEvent called `deltaX` and `deltaY`.
So when `.setRawMouseEnabled(true)` the MouseMoveEvent will be created from the WM_INPUT event and populate `deltaX` and `deltaY`, while still having the mouse position relative to upper left corner in `x` and `y`.

**Comment by sro5h** [comment]
I like that too.

I like it more to separate `MouseMoved` and the raw data :)

**Comment by hornta** [comment]
It makes sense to separate it because it is a completely different event behind, but wouldn't it be more understandable having a single MouseMove event that includes the change in the mouse movement?
I think it makes sense to abstract away the different events.

**Comment by sro5h** [comment]
I think it does make sense to separate it because the data is different. The position is in pixel coords and the delta movement is just the raw data without any unit (am i right?). So in most cases the delta movement doesn't correspond to the new position in pixel coords due to acceleration and smoothing. That's why i think it is better to keep it separate.
Furthermore SFML stops emitting `MouseMoved` events if the cursor leaves the window, but (at least in my opinion) `MouseMovedRaw/Relative` events should still get emitted.

**Comment by eXpl0it3r** [comment]
If the "delta" is not pixel based, then I'd go with `MouseMovedRaw` as it would otherwise be misleading.

Having it separated makes sense, since as said the data isn't the same and it quickly can lead to confusion.

**Comment by sro5h** [comment]
No it gives the "logical coordinates for the mouse based on the mouse's native resolution" ([source]()). For example on Windows i have mouse acceleration disabled and the mouse cursor matches my mouse movements. But if i enable it again it does not match anymore, the same is on Linux. So yes it can match but you need to explicitely disable acceleration and smoothing (and i don't know if even then it is garantueed to be the same because it could still be scaled by some amount). So yes i would definitely keep it separate to avoid confusion.

I'm gonna update my fork with `MouseMovedRaw` and will enable the generation of those events by default :)

**Comment by sro5h** [comment]
Updated [my fork](https://github.com/sro5h/sfml)
The event is now called `MouseMovedRaw` and raw mouse input will be enabled when the window is created. There is no more option to disable it. Usage example:
```c++
#include <SFML/Graphics.hpp>
#include <iostream>

int main()
{
    sf::RenderWindow window(sf::VideoMode(400, 400), "Raw Input Example");

    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
                window.close();

            else if (event.type == sf::Event::MouseMovedRaw)
            {
                std::cout << "raw movement, x = " << event.mouseMoveRaw.dx;
                std::cout << " y = " << event.mouseMoveRaw.dy << std::endl;
            }
        }

        window.clear();
        window.display();
    }

    return EXIT_SUCCESS;
}
```

**Comment by mantognini** [comment]
I don't know, *raw* doesn't really convey a meaning to me. It's used for so many things that it's too vague IMO. *Relative*, on the other hand, clearly identifies the data we're talking about. Maybe the data is unprocessed, but it still is relative, so I'd argue it is more appropriate here.

As for the data members, I'd either call them `deltaX/Y`, or simply `x/y` as the datatype (if we agree on *relative*) already holds the idea of relative distances. We haven't used abbreviations in SFML so far (right?), that's mainly why I'm objecting to `dx/y`.

The fact that the data is "raw", and therefore has no unit, might be a problem -- or not. I guess it all depends on how people want to use this feature, but the issue with unit-less distance is that we have no abstraction over hardware and therefore SFML cannot help developer correctly handle the data they receive. Maybe this is okay if people want to have "x/y sensibility factors" and let the users of their applications set its value for their own hardware. But maybe having a distance in actual pixel would be better?

In any case, I would include some explanation in the doc about what the data represents in an unambiguous manner.

**Comment by sro5h** [comment]
Ok i can change it to _Relative_

I think so too, iff we settle on `MouseMovedRelative` x/y should be enough.

Well i think that's exactly what this issue is about, having the mouse deltas without mouse acceleration etc. To convert it to a meaningful value in pixels you would have to take mouse acceleration into consideration again, but then this defeats the whole point of this feature. With mouse acceleration enabled you can't simply convert from the raw data to pixel values because it does not only depend on the distance the mouse covered but also the time it covered that distance in :)
But of course it has to be made clearer what kind of data you have to expect from `MouseMoveRelative` and that simply adding this relative data up might not corespond to the onscreen cursor movement.

**Comment by sro5h** [comment]
My use case would be a fps like camera and i don't care about the unit of the data. But i would allow the user to specify a multiplier (sensitivity i guess) so he can adjust the speed of the movement to his liking.
I think that is how most games handle it, but i might be wrong.

**Comment by eXpl0it3r** [comment]
> I don't know, raw doesn't really convey a meaning to me. It's used for so many things that it's too vague IMO. Relative, on the other hand, clearly identifies the data we're talking about. Maybe the data is unprocessed, but it still is relative, so I'd argue it is more appropriate here.
> The fact that the data is "raw", and therefore has no unit, might be a problem -- or not. I guess it all depends on how people want to use this feature, but the issue with unit-less distance is that we have no abstraction over hardware and therefore SFML cannot help developer correctly handle the data they receive. Maybe this is okay if people want to have "x/y sensibility factors" and let the users of their applications set its value for their own hardware. But maybe having a distance in actual pixel would be better?

If you read between the lines, you're actually saying that `Raw` is the better fitting word, because we do get raw, unit-less, unprocessed data.

Intuitive understanding of the property | Raw | Relative
---------|-----|----------
Relative                                    | ✖ | ✔
Unprocessed                                | ✔ | ✖
No specific unit                            | ✔ | ✖
Not comparable with exiting positional data | ✔ | ✖
More likely to make you check the docs to fully understand it | ✔ | ✖
People who know what raw input means understand it | ✔ | ✖
Same naming as the OS use | ✔ | ✖

I don't see the point "normalizing" the raw data, just for the argument-sake that maybe someone doesn't know what to do with the raw data. Fact is, this is a feature that all OS (I assume) support and a feature people do want to use. It's an advanced feature for people that care about precision and continues data stream.

**Comment by sro5h** [comment]
I totally agree, a normal user that wants relative cursor movement can store the position himself and calculate the difference since the last event.

What should we do with the members of the event? @mantognini mentioned `dx` doesn't go well with the existing api because it is an abbreviation, should we just call it `x` or go with something like `deltaX` to emphasize its relative nature?

**Comment by mantognini** [comment]
I won't argue that the data need a unit -- mainly because I have no use case for that. Any sane application will let the user define their motion factor.

However, the name *raw*, really? I mean, if the majority wants that, sure, but... 

> More likely to make you check the docs to fully understand it

This is no argument for either direction. Everybody **must** read the documentation. Full stop. ;-)

> Unprocessed

If one reads the doc, as one should, one would know what we're talking about. Raw is still ambiguous for me: it could simply ignore DPI scaling, or ignore y-axis flip, ...


> People who know what raw input means understand it

People who know what relative motion in SFML is certainly understand it. This is not an argument either.

> Same naming as the OS use

As far as I know, this is not a generality. And if we have a better name, we should use it instead of following head down what others did.

> should we just call it x or go with something like deltaX to emphasize its relative nature?

I think the five little extra characters of `delta` don't hurt, but I don't have a strong opinion on this one.

[implementation details] BTW, on mac, I'm not sure we can get un-accelerated data. I've seen a few applications attempting to solve this at the system level (i.e. can work with any application), and all the graphics libraries I've looked at use the default value (i.e. probably always accelerated, unless the cursor is detached from the mouse motion, but I don't have confirmation for this). Maybe we could do something at the USB level, but it's not yet clear that it will work.

**Comment by sro5h** [comment]
I agree with what @eXpl0it3r said but i wouldn't mind if you would better like to call it relative so i'm not going to comment on all of that :)

> [implementation details] BTW, on mac, I'm not sure we can get un-accelerated data. ...
I got that feeling when i searched for it a little bit. If i am not mistaken SDL2 doesn't provide unaccelerated data on macOs either (only on Windows and Linux) [1](https://forums.libsdl.org/viewtopic.php?p=51127). But there seem to be some [ideas](https://discourse.libsdl.org/t/macos-raw-mouse-woes/22895) and [manymouse](https://github.com/NoobsArePeople2/manymouse) might also be worth a look (don't know if it provides unaccelerated data on macOs, it might) :)

**Comment by Foaly** [comment]
I think it would be great if you could send a pull request, so we can move forward in the process of merging this :)

**Comment by Keeo** [comment]
Just link to the [pull request](https://github.com/SFML/SFML/pull/1383).

**Comment by naezith** [comment]
Software of a Logitech mouse eliminates the mouse acceleration on Mac.
