### ISSUE TITLE
Proposal: Allow different input pixels data types to Texture::update

### ISSUE THREAD

**Issue by Lorenzooone** [SFML/SFML#3296]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I understand [SFML's scope](https://www.sfml-dev.org/contribute.php#general-considerations) and believe the feature fits it

### Describe your feature request here

Add the ability to specify a different type from GL_RGBA for the pixels given in input to Texture::update.

Currently, only GL_RGBA is supported for input. If one wants to use a different type, they need to copy Texture::update, which is not a viable solution because 1) it's not easily mantainable, and 2) not all the calls done inside the update method of Texture can be executed in an external context.

I propose adding an enum or similar to specify the input data type of pixels, with the default being set to GL_RGBA, to mantain compatibility with old code.

Different from https://github.com/SFML/SFML/issues/166 , as this is not a change of the texture type used in general, but of the data input found in pixels that is used in update.

### Use Cases

Using different input data types could allow lower memory usage.

Skipping manual CPU conversions and making it so the GPU/driver does them can be a source for lower CPU usage: on lower end platforms this can lead to improved FPS counts (like a Raspberry Pi 3 going from 46 fps to 60+ just because I don't need to do that conversion, from my tests).

### API Example

```cpp
texture.update(buffer, {width, height}, {0, 0}); // GL_RGBA conversion
texture.update(buffer, {width, height}, {0, 0}, SFML_PIXELS_RGB); // GL_RGB conversion
```

**Comment by ChrisThrasher** [comment]
What specific pixel formats are you interested in using?

**Comment by Lorenzooone** [comment]
In particular:
- GL_RGB (24 bits)
- GL_BGR (24 bits)
- GL_RGBA (32 bits)
- GL_BGRA (32 bits)

If possible, also these:
- GL_RGB +  GL_UNSIGNED_SHORT_5_6_5 (16 bits)
- GL_BGR +  GL_UNSIGNED_SHORT_5_6_5 (16 bits)

These bottom ones can be achieved by using  the type parameter of glTexSubImage2D, though I understand it complicates a bit the method.

**Comment by eXpl0it3r** [comment]
Can you provide use cases as to why one would need different pixel data types?

**Comment by Lorenzooone** [comment]
In general, it would be when you receive input data from a source, and you cannot control the format of what is being sent to you.
Skipping the conversions helps a ton with CPU usage.

Let me make the example of my use case.

In my application I receive video input data from various USB devices.
They do not have a common protocol, so I have to make specific code for each of them.

Two devices send data in GL_RGB, another two in GL_BGR and one in GL_RGB + GL_UNSIGNED_SHORT_5_6_5.

Having to convert all of this data to GL_RGBA is slow and takes a ton of CPU time.

If I instead use the proper GL enums to specify the input data type to glTexSubImage2D, I see a substantial performance improvement, and I am able to achieve 1080p60 even on underpowered hardware like a Raspberry Pi 3 (something not possible when doing the conversion to GL_RGBA in code myself).

**Comment by ChrisThrasher** [comment]
> If I instead use the proper GL enums to specify the input data type to glTexSubImage2D, I see a substantial performance improvement, and I am able to achieve 1080p60 even on underpowered hardware like a Raspberry Pi 3 (something not possible when doing the conversion to GL_RGBA myself. 

Did you fork SFML to achieve this or did you write out the OpenGL calls yourself?

**Comment by Lorenzooone** [comment]
I duplicated the update method into my own code and changed the parameters of the call to fit my needs.
But, as I said before, it's not a mantainable way to do this, and externally I do not have access to certain calls the original update method uses, like certain locks.

**Comment by binary1248** [comment]
Regardless of what the input format is, until we change it, the texture is always stored internally as GL_RGBA, so anything other than that will have to be converted.

What I don't understand is the performance discrepancy between the driver doing the conversion and you doing the conversion in your own code. AFAIK format conversions are always performed on the CPU so in whose code it takes place shouldn't really matter. The driver doesn't have access to compute resources that user code doesn't.

As an example, the Mesa code that takes care of it can be found at:
- https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/mesa/main/texstore.c#L678
- https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/mesa/main/image.c#L857

It isn't magic, and is just about what anyone would expect it to look like.

When discussing performance, it is useful to provide enough information so that others can reproduce the results themselves as well, even if it is on other platforms. If the performance gain you are seeing is solely from the change you made it should be reproducible in a minimal example.

While adding new features to the library always seems nice at first, we mustn't lose sight of the fact that the use case described here is very niche. Typically, when rendering a video or some other streamed data, we resort to PBOs instead of constantly updating a bunch of textures every frame. Texture objects were really meant to be upload-once-use-many-times and thus have heavy overhead due to the synchronization that is required. PBOs on the other hand allow transferring data into graphics memory asynchronously using DMA. Taking advantage of asynchronous transfers also means having to rethink where and how time is spent in your code, performance optimizations seldom come for free.

Generally, the GPU is more capable of performing a large number of primitive operations in parallel than the CPU is. It will have no issue converting between the selected internal format and whatever the actual hardware requires the data to ultimately be in. The most performance gain will be seen when creating textures whose internal format more or less matches the incoming data and transferring this data via PBOs. To query OpenGL for the recommended optimal internal format, [`glGetInternalformat`](https://registry.khronos.org/OpenGL-Refpages/gl4/html/glGetInternalformat.xhtml) can be used with `GL_GET_TEXTURE_IMAGE_FORMAT` and `GL_GET_TEXTURE_IMAGE_TYPE`.

My recommendation is to write this in OpenGL instead of using the current SFML graphics API. We have known for a fairly long time that SFML graphics performance was never its main selling point and that's why we always supported the possibility for interoperating with user OpenGL code when performance becomes a severe bottleneck as in your case. SFML natively supporting video rendering could be a mid- to long-term goal, but we must be wary of the patent minefield that is video formats.

See also:
https://www.khronos.org/opengl/wiki/Pixel_Buffer_Object
https://www.khronos.org/opengl/wiki/Pixel_Transfer
https://www.khronos.org/opengl/wiki/Image_Format

**Comment by Lorenzooone** [comment]
Hmm...
Okay.
I do not know what I am doing so weirdly that the mesa routine is so much better than mine...

Regardless, thanks for the pointers!
