### ISSUE TITLE
.bdf and .pcf fonts do not work

### ISSUE THREAD

**Issue by vittorioromeo** [SFML/SFML#448]
Loading them with `sf::Font::loadFromFile` returns true, but nothing is displayed when a `sf::Text` uses them.

**Comment by neagix** [comment]
I tried 2.2 and 2.3.2, this issue is still present. For example use `-Misc-Fixed-Medium-R-Normal--10-100-75-75-C-60-ISO10646-1` from https://www.cl.cam.ac.uk/~mgk25/ucs-fonts.html and try to set size to anything different than 10: nothing is rendered. I have also tried converting the font first to PCF, same result.
