### ISSUE TITLE
fatal error: ft2build.h: No such file or directory on windows

### ISSUE THREAD

**Issue by lamogui** [SFML/SFML#916]
Hi

SFML 2.3 have a compile error under windows caused by cmake (I'm under Cmake 3.x)
I think this line is missing somewhere in CMakeLists.txt (SFML/Graphics/CMakeLists.txt) :
include_directories(${CMAKE_INCLUDE_PATH}) 
(or better target_include_directories)

I can't find this line anywhere in the sources I added it and it's worked fine...

**Comment by binary1248** [comment]
Cannot reproduce... even in a cleanroom environment.

**Comment by eXpl0it3r** [comment]
We like to use the issue tracker for confirmed issues, so please report things like that on the forum.

I'm pretty sure this just comes from the fact that you have some old cached things lying around. FreeType has been updated for SFML 2.3 and the include directories changed because of that.
Use a clean setup and try again.

**Comment by zsbzsb** [comment]
I can confirm that it is due to CMake caching stuff, as I have ran into this myself and then needed to clean the cache.
