### ISSUE TITLE
CMake uses it's own FindFreetype.cmake

### ISSUE THREAD

**Issue by danijar** [SFML/SFML#946]
I try to build SFML with CMake 2.8.12 on Ubuntu 12.04. For some reason, CMake chooses the built-in find script rather than the one inside the SFML repository at `cmake/Modules/FindFreetype.cmake`. I think this is the reson for this error. However, I don't quite understand the error message. It says both *found freetype2* and *Could NOT find Freetype*.

    -- Found UDev: /usr/lib/x86_64-linux-gnu/libudev.so
    --    include: /usr/include
    -- Found GLEW: /home/travis/build/danijar/modurale/install/glew/lib64/libGLEW.so  
    -- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so  
    -- checking for module 'freetype2'
    --   found freetype2, version 14.0.8
    CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
      Could NOT find Freetype (missing: FREETYPE_INCLUDE_DIRS) (found version
      "14.0.8")
    Call Stack (most recent call first):
      /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
      /usr/share/cmake-2.8/Modules/FindFreetype.cmake:131 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
      src/SFML/Graphics/CMakeLists.txt:131 (find_package)

**Edit:** I installed `libfreetype6-dev` using apt. With CMake 2.8.8 it worked fine.

**Comment by eXpl0it3r** [comment]
The issue is for confirmed issues only, see the [contribution guidelines](http://www.sfml-dev.org/contribute.php).

If I remember correctly the older versions of FreeType ship with a FindFreetype.cmake module that is incompatible with newer versions of CMake. And since the OS defined Find module should always be preferred the behavior here is more related to your OS's package manager and versions "conflict" rather than SFML itself.

**Comment by danijar** [comment]
Thanks for the answer. In case someone is looking for the answer, creating a symlink helps CMake find the new header location.

```
# Workaround for CMake 2.8.12 to find Freetype
sudo ln -s /usr/include/freetype2/freetype /usr/include/freetype
```
