### ISSUE TITLE
setPlayingOffset should check the passed value

### ISSUE THREAD

**Issue by eXpl0it3r** [SFML/SFML#966]
As reported on the [forum](http://en.sfml-dev.org/forums/index.php?topic=18995.msg136884#msg136884), the value passed to `setPlayingOffset()` doesn't get checked and instead gets simply applied. If the offset is longer than the sound, the sound will start from the beginning, but the counter will keep counting from the non-existent offset.

**Comment by Bromeon** [comment]
Note: The semantics may change with https://github.com/SFML/SFML/pull/629. If that pull request is merged, wrap-arounds will make sense, and we could consider allowing modulo semantics in `setPlayingOffset()`.

**Comment by Foaly** [comment]
Working on #1041 I noticed that if you set an offest bigger than the length of the sound for OGG and FLAC the file will simply play from the beginning. The WAV reader correctly stops the stream if the offset is too big. None of the `sf::SoundFileReader*::seek()` handle this properly though. The WAV reader just works because the underlying `sf::FileInputStream::seek()` has this behaviour. Note that this contradicts the documentation of `seek()` in [`sf::InputSoundFile`](http://www.sfml-dev.org/documentation/2.3.2/classsf_1_1InputSoundFile.php#aaf97be15020a42e159ff88f76f22af20) and [`sf::SoundFileReader`](http://www.sfml-dev.org/documentation/2.3.2/classsf_1_1SoundFileReader.php#a1e18ade5ffe882bdfa20a2ebe7e2b015)

I know this is subject to change, but I just wanted to updated that this problem still exists.

**Comment by BionicFelps** [comment]
Just hit something similar (using version 2.3.2), applying an offset stored earlier from getPlayingOffset(), it restarts from the beginning, note that this is an attempt to essentially make my own pause functionality so that I don't have to keep the object alive while the music is paused... When I play it uses setPlayingOffset(<earlier offset>); I've checked in debugging, the value of the sf::Time object is very close to the 25 seconds that I slept the thread for in my test (25703764 microseconds (this was while debugging so there was a couple seconds of me hitting the step over button, but should be well within my several minute music sample)).

I have similar code for the buffered sound object, but I haven't tested it yet...

**Comment by eXpl0it3r** [comment]
> Just hit something similar (using version 2.3.2), applying an offset stored earlier from getPlayingOffset(), it restarts from the beginning

Issues like you describe have already been fixed. Check out the master branch.

**Comment by eXpl0it3r** [comment]
So what exactly should the behavior be if the offset is too long? Should it start playing from the beginning or should it seek to the end and stop?

**Comment by Bromeon** [comment]
For the current version, I wouldn't apply a wrap-around. For offsets longer than the duration, we could either stop, or -- more aggressively -- have an assertion.

Because this behavior will likely change as I stated above, I wouldn't document it as a feature, it merely fixes a bug with currently unvalidated arguments.

**Comment by eXpl0it3r** [comment]
Having dug a bit deeper, this is something we'll have to address at the bottom, that is at the file stream readers. But I think, it makes more sense to define the behavior once and it for all the supported formats instead of patching random pieces of code. As such I removed the 2.4 tag.

**Comment by eXpl0it3r** [comment]
Fixed by #1162
