### ISSUE TITLE
sf::Image::saveToMemory

### ISSUE THREAD

**Issue by Starl1ght** [SFML/SFML#988]
There was feature request http://en.sfml-dev.org/forums/index.php?topic=2164.msg14166#msg14166 - which was closed. But few weeks ago stb_image_write.h was updated, and we have stbi_write_%FORMAT%_to_func(...) functions, that can achieve this functionality with ease. Can it be considered for release?

**Comment by MarioLiebisch** [comment]
Actually sounds interesting and would be in line with loading images I guess.

**Comment by eXpl0it3r** [comment]
Question is, does libjpeg support this as well?

**Comment by gexclaude** [comment]
What are plans on this one? I would be more than happy to see this feature - I like to use SFML to create a rasterized output (PNG), but would like to avoid writing to a file and then read it again.

**Comment by LaurentGomila** [comment]
See this forum post: https://en.sfml-dev.org/forums/index.php?topic=25005.0

**Comment by gexclaude** [comment]
Thanks Laurent for the very fast reply! Wow, this topic is more actively discussed as I expected due to this feature request state :)

I will now try to do proof-of-concept development using SFML and a temp-file approach. If everything looks good I assume this feature will be added rather soon? A 2.5.x or 2.6.x version would be very nice. 

BTW: if I am going to use SFML I will be more than happy to drop a donation.

**Comment by eXpl0it3r** [comment]
Implemented with #1669
